This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by ABINIT configure 7.2.1, which was
generated by GNU Autoconf 2.68.  Invocation command line was

  $ ./configure --enable-mpi --with-mpi-prefix=/usr/lib64/openmpi/ --with-tardir=/home/weitong/.abinit/tarballs

## --------- ##
## Platform. ##
## --------- ##

hostname = magnetics
uname -m = x86_64
uname -r = 2.6.32-358.6.1.el6.x86_64
uname -s = Linux
uname -v = #1 SMP Tue Apr 23 19:29:00 UTC 2013

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/lib64/qt-3.3/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /sbin
PATH: /home/weitong/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:3605: checking build system type
configure:3619: result: x86_64-unknown-linux-gnu
configure:3639: checking host system type
configure:3652: result: x86_64-unknown-linux-gnu
configure:3672: checking target system type
configure:3685: result: x86_64-unknown-linux-gnu
configure:3727: checking for a BSD-compatible install
configure:3795: result: /usr/bin/install -c
configure:3806: checking whether build environment is sane
configure:3856: result: yes
configure:3997: checking for a thread-safe mkdir -p
configure:4036: result: /bin/mkdir -p
configure:4049: checking for gawk
configure:4065: found /usr/bin/gawk
configure:4076: result: gawk
configure:4087: checking whether make sets $(MAKE)
configure:4109: result: yes
configure:4569: checking whether make sets $(MAKE)
configure:4591: result: yes
configure:4601: checking whether ln -s works
configure:4605: result: yes
configure:4612: checking for a sed that does not truncate output
configure:4676: result: /bin/sed
configure:4685: checking for gawk
configure:4712: result: gawk
configure:4723: checking for grep that handles long lines and -e
configure:4781: result: /bin/grep
configure:4788: checking for egrep
configure:4850: result: /bin/grep -E
configure:5843: not loading options (no config file available)
configure:7770: ABINIT version 7.2.1
configure:7780: M4 010416 - Autoconf 026800 - Automake 011100 - Libtool 020204
configure:7791: reporting user interface changes:
configure:7794:  * --enable-mpi has been modified
configure:7796:    (changed default value to no)
configure:7798:    please check that --enable-mpi="yes" is OK for you
configure:7801:  * --enable-mpi-io has been modified
configure:7803:    (changed default value to no)
configure:7805:    please check that --enable-mpi-io="no" is OK for you
configure:7808:  * new option --with-libpspio-incs is available
configure:7811:  * new option --with-libpspio-libs is available
configure:7814:  * --with-trio-flavor has been modified
configure:7816:    (changed permitted values (added 'libpspio'))
configure:7818:    please check that --with-trio-flavor="netcdf+etsf_io" is OK for you
configure:7855: checking consistency of library-related options
configure:7886:  |---> all OK
configure:7889: 
configure:7898: checking consistency of experimental options
configure:7913:  |---> all OK
configure:7916: 
configure:7925: checking consistency of maintainer options
configure:7941:  |---> all OK
configure:7944: 
configure:7953: parsing command-line options
configure:9101: Initializing MPI support
configure:9105: looking for MPI in /usr/lib64/openmpi/
configure:9129: checking for a MPI C compiler
configure:9139: result: /usr/lib64/openmpi//bin/mpicc
configure:9143: checking for a MPI C++ compiler
configure:9156: result: /usr/lib64/openmpi//bin/mpicxx
configure:9160: checking for a MPI Fortran compiler
configure:9170: result: /usr/lib64/openmpi//bin/mpif90
configure:9174: checking for a MPI runner
configure:9190: result: /usr/lib64/openmpi//bin/mpirun
configure:9726: GPU support disabled from command-line
configure:9769: checking for sh
configure:9787: found /bin/sh
configure:9800: result: /bin/sh
configure:9810: checking for mv
configure:9828: found /bin/mv
configure:9841: result: /bin/mv
configure:9851: checking for perl
configure:9869: found /usr/bin/perl
configure:9882: result: /usr/bin/perl
configure:9892: checking for rm
configure:9910: found /bin/rm
configure:9923: result: /bin/rm
configure:9936: checking for patch
configure:9952: found /usr/bin/patch
configure:9963: result: patch
configure:9978: checking for tar
configure:9994: found /bin/tar
configure:10005: result: tar
configure:10363: checking for gcc
configure:10390: result: /usr/lib64/openmpi//bin/mpicc
configure:10619: checking for C compiler version
configure:10628: /usr/lib64/openmpi//bin/mpicc --version >&5
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:10639: $? = 0
configure:10628: /usr/lib64/openmpi//bin/mpicc -v >&5
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) 
configure:10639: $? = 0
configure:10628: /usr/lib64/openmpi//bin/mpicc -V >&5
gcc: '-V' option must have argument
configure:10639: $? = 1
configure:10628: /usr/lib64/openmpi//bin/mpicc -qversion >&5
gcc: unrecognized option '-qversion'
gcc: no input files
configure:10639: $? = 1
configure:10659: checking whether the C compiler works
configure:10681: /usr/lib64/openmpi//bin/mpicc    conftest.c  >&5
configure:10685: $? = 0
configure:10733: result: yes
configure:10736: checking for C compiler default output file name
configure:10738: result: a.out
configure:10744: checking for suffix of executables
configure:10751: /usr/lib64/openmpi//bin/mpicc -o conftest    conftest.c  >&5
configure:10755: $? = 0
configure:10777: result: 
configure:10799: checking whether we are cross compiling
configure:10807: /usr/lib64/openmpi//bin/mpicc -o conftest    conftest.c  >&5
configure:10811: $? = 0
configure:10818: ./conftest
./conftest: error while loading shared libraries: libmpi.so.1: cannot open shared object file: No such file or directory
configure:10822: $? = 127
configure:10829: error: in `/home/weitong/setup/abinit/abinit-7.2.1':
configure:10831: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_ARFLAGS_DEBUG_set=
ac_cv_env_ARFLAGS_DEBUG_value=
ac_cv_env_ARFLAGS_EXTRA_set=
ac_cv_env_ARFLAGS_EXTRA_value=
ac_cv_env_ARFLAGS_OPTIM_set=
ac_cv_env_ARFLAGS_OPTIM_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_LDFLAGS_DEBUG_set=
ac_cv_env_CC_LDFLAGS_DEBUG_value=
ac_cv_env_CC_LDFLAGS_OPTIM_set=
ac_cv_env_CC_LDFLAGS_OPTIM_value=
ac_cv_env_CC_LDFLAGS_set=
ac_cv_env_CC_LDFLAGS_value=
ac_cv_env_CC_LIBS_DEBUG_set=
ac_cv_env_CC_LIBS_DEBUG_value=
ac_cv_env_CC_LIBS_OPTIM_set=
ac_cv_env_CC_LIBS_OPTIM_value=
ac_cv_env_CC_LIBS_set=
ac_cv_env_CC_LIBS_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_DEBUG_set=
ac_cv_env_CFLAGS_DEBUG_value=
ac_cv_env_CFLAGS_EXTRA_set=
ac_cv_env_CFLAGS_EXTRA_value=
ac_cv_env_CFLAGS_OPTIM_set=
ac_cv_env_CFLAGS_OPTIM_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_DEBUG_set=
ac_cv_env_CPPFLAGS_DEBUG_value=
ac_cv_env_CPPFLAGS_EXTRA_set=
ac_cv_env_CPPFLAGS_EXTRA_value=
ac_cv_env_CPPFLAGS_OPTIM_set=
ac_cv_env_CPPFLAGS_OPTIM_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_DEBUG_set=
ac_cv_env_CXXFLAGS_DEBUG_value=
ac_cv_env_CXXFLAGS_EXTRA_set=
ac_cv_env_CXXFLAGS_EXTRA_value=
ac_cv_env_CXXFLAGS_OPTIM_set=
ac_cv_env_CXXFLAGS_OPTIM_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_LDFLAGS_DEBUG_set=
ac_cv_env_CXX_LDFLAGS_DEBUG_value=
ac_cv_env_CXX_LDFLAGS_EXTRA_set=
ac_cv_env_CXX_LDFLAGS_EXTRA_value=
ac_cv_env_CXX_LDFLAGS_OPTIM_set=
ac_cv_env_CXX_LDFLAGS_OPTIM_value=
ac_cv_env_CXX_LDFLAGS_set=
ac_cv_env_CXX_LDFLAGS_value=
ac_cv_env_CXX_LIBS_DEBUG_set=
ac_cv_env_CXX_LIBS_DEBUG_value=
ac_cv_env_CXX_LIBS_OPTIM_set=
ac_cv_env_CXX_LIBS_OPTIM_value=
ac_cv_env_CXX_LIBS_set=
ac_cv_env_CXX_LIBS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_FCFLAGS_DEBUG_set=
ac_cv_env_FCFLAGS_DEBUG_value=
ac_cv_env_FCFLAGS_EXTRA_set=
ac_cv_env_FCFLAGS_EXTRA_value=
ac_cv_env_FCFLAGS_OPENMP_set=
ac_cv_env_FCFLAGS_OPENMP_value=
ac_cv_env_FCFLAGS_OPTIM_set=
ac_cv_env_FCFLAGS_OPTIM_value=
ac_cv_env_FCFLAGS_set=
ac_cv_env_FCFLAGS_value=
ac_cv_env_FC_LDFLAGS_DEBUG_set=
ac_cv_env_FC_LDFLAGS_DEBUG_value=
ac_cv_env_FC_LDFLAGS_EXTRA_set=
ac_cv_env_FC_LDFLAGS_EXTRA_value=
ac_cv_env_FC_LDFLAGS_OPTIM_set=
ac_cv_env_FC_LDFLAGS_OPTIM_value=
ac_cv_env_FC_LDFLAGS_set=
ac_cv_env_FC_LDFLAGS_value=
ac_cv_env_FC_LIBS_DEBUG_set=
ac_cv_env_FC_LIBS_DEBUG_value=
ac_cv_env_FC_LIBS_OPTIM_set=
ac_cv_env_FC_LIBS_OPTIM_value=
ac_cv_env_FC_LIBS_set=
ac_cv_env_FC_LIBS_value=
ac_cv_env_FC_set=
ac_cv_env_FC_value=
ac_cv_env_FPPFLAGS_DEBUG_set=
ac_cv_env_FPPFLAGS_DEBUG_value=
ac_cv_env_FPPFLAGS_EXTRA_set=
ac_cv_env_FPPFLAGS_EXTRA_value=
ac_cv_env_FPPFLAGS_OPTIM_set=
ac_cv_env_FPPFLAGS_OPTIM_value=
ac_cv_env_FPPFLAGS_set=
ac_cv_env_FPPFLAGS_value=
ac_cv_env_FPP_set=
ac_cv_env_FPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MPI_RUNNER_set=
ac_cv_env_MPI_RUNNER_value=
ac_cv_env_SERIAL_RUNNER_set=
ac_cv_env_SERIAL_RUNNER_value=
ac_cv_env_XPPFLAGS_DEBUG_set=
ac_cv_env_XPPFLAGS_DEBUG_value=
ac_cv_env_XPPFLAGS_EXTRA_set=
ac_cv_env_XPPFLAGS_EXTRA_value=
ac_cv_env_XPPFLAGS_OPTIM_set=
ac_cv_env_XPPFLAGS_OPTIM_value=
ac_cv_env_XPPFLAGS_set=
ac_cv_env_XPPFLAGS_value=
ac_cv_env_XPP_set=
ac_cv_env_XPP_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_BOURNE_SHELL=/bin/sh
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_GREP=/bin/grep
ac_cv_path_MV=/bin/mv
ac_cv_path_PERL=/usr/bin/perl
ac_cv_path_RM=/bin/rm
ac_cv_path_SED=/bin/sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_PATCH=patch
ac_cv_prog_TAR=tar
ac_cv_prog_ac_ct_CC=/usr/lib64/openmpi//bin/mpicc
ac_cv_prog_make_make_set=yes
ac_cv_target=x86_64-unknown-linux-gnu

## ----------------- ##
## Output variables. ##
## ----------------- ##

ABINIT_BINARY_PACKAGE=''
ABINIT_TARGET=''
ABINIT_VERSION='7.2.1'
ABINIT_VERSION_BASE='7.2'
ABINIT_VERSION_BUILD='20130511'
ABINIT_VERSION_MAJOR='7'
ABINIT_VERSION_MICRO='1'
ABINIT_VERSION_MINOR='2'
ABI_CPPFLAGS=''
ACLOCAL='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/missing --run aclocal-1.11'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/missing --run tar'
AR=''
ARFLAGS=''
ARFLAGS_64BITS=''
ARFLAGS_CMD='rc'
ARFLAGS_DEBUG=''
ARFLAGS_EXTRA=''
ARFLAGS_HINTS=''
ARFLAGS_OPTIM=''
ATOMPAW_BIN=''
AUTOCONF='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/missing --run autoconf'
AUTOHEADER='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/missing --run autoheader'
AUTOMAKE='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/missing --run automake-1.11'
AWK='gawk'
BAZAAR=''
BOURNE_SHELL='/bin/sh'
CC='/usr/lib64/openmpi//bin/mpicc'
CCDEPMODE=''
CC_LDFLAGS=''
CC_LDFLAGS_64BITS=''
CC_LDFLAGS_DEBUG=''
CC_LDFLAGS_EXTRA=''
CC_LDFLAGS_GPU=''
CC_LDFLAGS_HINTS=''
CC_LDFLAGS_OPTIM=''
CC_LIBS=''
CC_LIBS_64BITS=''
CC_LIBS_DEBUG=''
CC_LIBS_EXTRA=''
CC_LIBS_GPU=''
CC_LIBS_HINTS=''
CC_LIBS_OPTIM=''
CFLAGS=''
CFLAGS_64BITS=''
CFLAGS_DEBUG=''
CFLAGS_EXTRA=''
CFLAGS_GPU=''
CFLAGS_HINTS=''
CFLAGS_OPTIM=''
CPP=''
CPPFLAGS=''
CPPFLAGS_64BITS=''
CPPFLAGS_DEBUG=''
CPPFLAGS_EXTRA=''
CPPFLAGS_GPU=''
CPPFLAGS_HINTS=''
CPPFLAGS_HINTS_EXT=''
CPPFLAGS_OPTIM=''
CXX='/usr/lib64/openmpi//bin/mpicxx'
CXXDEPMODE=''
CXXFLAGS=''
CXXFLAGS_64BITS=''
CXXFLAGS_DEBUG=''
CXXFLAGS_EXTRA=''
CXXFLAGS_GPU=''
CXXFLAGS_HINTS=''
CXXFLAGS_OPTIM=''
CXX_LDFLAGS=''
CXX_LDFLAGS_64BITS=''
CXX_LDFLAGS_DEBUG=''
CXX_LDFLAGS_EXTRA=''
CXX_LDFLAGS_GPU=''
CXX_LDFLAGS_HINTS=''
CXX_LDFLAGS_OPTIM=''
CXX_LIBS=''
CXX_LIBS_64BITS=''
CXX_LIBS_DEBUG=''
CXX_LIBS_EXTRA=''
CXX_LIBS_GPU=''
CXX_LIBS_HINTS=''
CXX_LIBS_OPTIM=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DO_BUILD_01_GSL_EXT_FALSE=''
DO_BUILD_01_GSL_EXT_TRUE=''
DO_BUILD_01_MACROAVNEW_EXT_FALSE=''
DO_BUILD_01_MACROAVNEW_EXT_TRUE=''
DO_BUILD_02_CLIB_FALSE=''
DO_BUILD_02_CLIB_TRUE=''
DO_BUILD_15_GPU_TOOLBOX_FALSE=''
DO_BUILD_15_GPU_TOOLBOX_TRUE=''
DO_BUILD_32_CONTRACT_FALSE=''
DO_BUILD_32_CONTRACT_TRUE=''
DO_BUILD_52_MANAGE_CUDA_FALSE=''
DO_BUILD_52_MANAGE_CUDA_TRUE=''
DO_BUILD_BINDINGS_FALSE=''
DO_BUILD_BINDINGS_TRUE=''
DO_BUILD_CCLOCK_FALSE=''
DO_BUILD_CCLOCK_TRUE=''
DO_BUILD_DOC_FALSE=''
DO_BUILD_DOC_TRUE=''
DO_BUILD_EXPORTS_FALSE=''
DO_BUILD_EXPORTS_TRUE=''
DO_BUILD_GUI_FALSE=''
DO_BUILD_GUI_TRUE=''
DO_BUILD_MACROAVE_FALSE=''
DO_BUILD_MACROAVE_TRUE=''
DO_BUILD_TESTS_FALSE=''
DO_BUILD_TESTS_TRUE=''
DO_TEST_MPI_FALSE=''
DO_TEST_MPI_TRUE=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
EXEEXT=''
F77=''
FC='/usr/lib64/openmpi//bin/mpif90'
FCFLAGS=''
FCFLAGS_64BITS=''
FCFLAGS_DEBUG=''
FCFLAGS_EXTRA=''
FCFLAGS_F90=''
FCFLAGS_FIXEDFORM=''
FCFLAGS_FREEFORM=''
FCFLAGS_HINTS=''
FCFLAGS_MODDIR=''
FCFLAGS_OPENMP=''
FCFLAGS_OPTIM=''
FCLIBS=''
FC_LDFLAGS=''
FC_LDFLAGS_64BITS=''
FC_LDFLAGS_DEBUG=''
FC_LDFLAGS_EXTRA=''
FC_LDFLAGS_HINTS=''
FC_LDFLAGS_OPTIM=''
FC_LIBS=''
FC_LIBS_64BITS=''
FC_LIBS_DEBUG=''
FC_LIBS_EXTRA=''
FC_LIBS_HINTS=''
FC_LIBS_OPTIM=''
FC_NOWRAP=''
FFLAGS=''
FPP=''
FPPFLAGS=''
FPPFLAGS_DEBUG=''
FPPFLAGS_EXTRA=''
FPPFLAGS_HINTS=''
FPPFLAGS_OPTIM=''
GRAPHATOM_BIN=''
GREP='/bin/grep'
GSL_CONFIG=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JAVA=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LN_S='ln -s'
LTLIBOBJS=''
LTXFLAGS=''
MAKEINFO='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/missing --run makeinfo'
MDFLAGS=''
MKDIR_P='/bin/mkdir -p'
MODEXT=''
MPI_RUNNER='/usr/lib64/openmpi//bin/mpirun'
MV='/bin/mv'
NVCC=''
NVCC_CFLAGS=''
NVCC_CPPFLAGS=''
NVCC_LDFLAGS=''
NVCC_LIBS=''
OBJEXT=''
PACKAGE='abinit'
PACKAGE_BUGREPORT='https://bugs.launchpad.net/abinit/'
PACKAGE_NAME='ABINIT'
PACKAGE_STRING='ABINIT 7.2.1'
PACKAGE_TARNAME='abinit'
PACKAGE_URL=''
PACKAGE_VERSION='7.2.1'
PATCH='patch'
PATH_SEPARATOR=':'
PDFFLAGS=''
PERL='/usr/bin/perl'
PYTHON=''
PYTHON_CPPFLAGS=''
RANLIB=''
RM='/bin/rm'
SED='/bin/sed'
SERIAL_RUNNER=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
TAR='tar'
TRUE_CPP=''
VERSION='7.2.1'
WANNIER90_X_BIN=''
XPP=''
XPPFLAGS=''
XPPFLAGS_DEBUG=''
XPPFLAGS_EXTRA=''
XPPFLAGS_OPTIM=''
abi_ac_version='026800'
abi_am_version='011100'
abi_cc_path=''
abi_cc_vendor=''
abi_cc_version=''
abi_cpp_path=''
abi_cpu_64bits='yes'
abi_cpu_bits='64'
abi_cpu_model='xeon'
abi_cpu_platform='unknown'
abi_cpu_spec='intel_xeon'
abi_cpu_vendor='intel'
abi_cxx_path=''
abi_cxx_vendor=''
abi_cxx_version=''
abi_fc_path=''
abi_fc_vendor=''
abi_fc_version=''
abi_fc_wrap='no'
abi_fpp_path=''
abi_lt_version='020204'
abi_m4_version='010416'
abi_mpi_runner_works=''
abi_sys_spec='linux-x86_64'
abi_test_atompaw=''
abi_test_bigdft=''
abi_test_etsf_io=''
abi_test_fox=''
abi_test_gui=''
abi_test_libxc=''
abi_test_netcdf=''
abi_test_wannier90=''
abinit_bindir='/usr/local/bin'
abinit_builddir='/home/weitong/setup/abinit/abinit-7.2.1'
abinit_chkdir='/usr/local/share/abinit/tests'
abinit_datdir='/usr/local/share/abinit'
abinit_docdir='/usr/local/doc/abinit'
abinit_incdir='/usr/local/include'
abinit_libdir='/usr/local/lib'
abinit_mandir='/usr/local/share/man'
abinit_moddir='/home/weitong/setup/abinit/abinit-7.2.1/src/mods'
abinit_prefix='/usr/local'
abinit_srcdir='/home/weitong/setup/abinit/abinit-7.2.1'
abinit_tardir=''
ac_ct_CC='/usr/lib64/openmpi//bin/mpicc'
ac_ct_CXX=''
ac_ct_FC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
bzr_branch=''
bzr_clean=''
bzr_revno=''
cc_for_timeout=''
cc_info_string=''
cxx_info_string=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
enable_64bit_flags='no'
enable_bindings='no'
enable_bse_unpacked='no'
enable_cclock='no'
enable_clib='no'
enable_config_file='yes'
enable_connectors='yes'
enable_debug='basic'
enable_dev_timer='no'
enable_exports='no'
enable_fallbacks='yes'
enable_fast_check='no'
enable_fc_wrapper='no'
enable_gpu='no'
enable_gui='no'
enable_gw_dpc='no'
enable_hints='yes'
enable_macroave='yes'
enable_maintainer_checks='no'
enable_memory_profiling=''
enable_mpi='yes'
enable_mpi_inplace='no'
enable_mpi_io='no'
enable_mpi_trace='no'
enable_openmp='no'
enable_optim='standard'
enable_pkg_check='no'
enable_shared=''
enable_static=''
enable_stdin='yes'
enable_test_timeout='no'
enable_vdwxc='no'
enable_zdot_bugfix='no'
exec_prefix='NONE'
fallbacks_incs=''
fallbacks_instdir=''
fc_info_string=''
fc_mod_incs=''
fc_timing=''
fcflags_opt_01_gsl_ext=''
fcflags_opt_01_interfaces_ext=''
fcflags_opt_01_linalg_ext=''
fcflags_opt_01_macroavnew_ext=''
fcflags_opt_02_clib=''
fcflags_opt_10_defs=''
fcflags_opt_11_memory_mpi=''
fcflags_opt_11_qespresso_ext=''
fcflags_opt_12_hide_mpi=''
fcflags_opt_14_hidewrite=''
fcflags_opt_15_gpu_toolbox=''
fcflags_opt_16_hideleave=''
fcflags_opt_18_timing=''
fcflags_opt_27_toolbox_oop=''
fcflags_opt_28_numeric_noabirule=''
fcflags_opt_32_util=''
fcflags_opt_41_geometry=''
fcflags_opt_42_nlstrain=''
fcflags_opt_42_parser=''
fcflags_opt_43_ptgroups=''
fcflags_opt_43_wvl_wrappers=''
fcflags_opt_44_abitypes_defs=''
fcflags_opt_45_geomoptim=''
fcflags_opt_45_psp_parser=''
fcflags_opt_47_xml=''
fcflags_opt_49_gw_toolbox_oop=''
fcflags_opt_51_manage_mpi=''
fcflags_opt_52_fft_mpi_noabirule=''
fcflags_opt_52_manage_cuda=''
fcflags_opt_53_abiutil=''
fcflags_opt_53_ffts=''
fcflags_opt_53_spacepar=''
fcflags_opt_56_mixing=''
fcflags_opt_56_recipspace=''
fcflags_opt_56_xc=''
fcflags_opt_57_iovars=''
fcflags_opt_59_io_mpi=''
fcflags_opt_61_ionetcdf=''
fcflags_opt_62_cg_noabirule=''
fcflags_opt_62_iowfdenpot=''
fcflags_opt_62_occeig=''
fcflags_opt_62_poisson=''
fcflags_opt_62_wvl_wfs=''
fcflags_opt_63_bader=''
fcflags_opt_64_atompaw=''
fcflags_opt_65_nonlocal=''
fcflags_opt_65_psp=''
fcflags_opt_66_paw=''
fcflags_opt_66_wfs=''
fcflags_opt_67_common=''
fcflags_opt_68_dmft=''
fcflags_opt_68_recursion=''
fcflags_opt_68_rsprc=''
fcflags_opt_69_wfdesc=''
fcflags_opt_70_gw=''
fcflags_opt_71_bse=''
fcflags_opt_72_response=''
fcflags_opt_77_ddb=''
fcflags_opt_77_lwf=''
fcflags_opt_77_suscep=''
fcflags_opt_79_seqpar_mpi=''
fcflags_opt_83_cut3d=''
fcflags_opt_95_drive=''
fcflags_opt_98_main=''
fcflags_opt_algo=''
fcflags_opt_atompaw=''
fcflags_opt_bigdft=''
fcflags_opt_etsf_io=''
fcflags_opt_fox=''
fcflags_opt_libpspio=''
fcflags_opt_libxc=''
fcflags_opt_linalg=''
fcflags_opt_netcdf=''
fcflags_opt_wannier90=''
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/weitong/setup/abinit/abinit-7.2.1/config/gnu/install-sh'
lib_algo_fcflags=''
lib_algo_flavor=''
lib_algo_incs=''
lib_algo_ldflags=''
lib_algo_libs=''
lib_atompaw_bins=''
lib_atompaw_fcflags=''
lib_atompaw_incs=''
lib_atompaw_ldflags=''
lib_atompaw_libs=''
lib_bigdft_fcflags=''
lib_bigdft_incs=''
lib_bigdft_ldflags=''
lib_bigdft_libs=''
lib_dft_flavor=''
lib_etsf_io_fcflags=''
lib_etsf_io_incs=''
lib_etsf_io_ldflags=''
lib_etsf_io_libs=''
lib_fft_fcflags=''
lib_fft_flavor=''
lib_fft_incs=''
lib_fft_ldflags=''
lib_fft_libs=''
lib_fox_fcflags=''
lib_fox_incs=''
lib_fox_ldflags=''
lib_fox_libs=''
lib_gpu_fcflags=''
lib_gpu_flavor='none'
lib_gpu_incs=''
lib_gpu_ldflags=''
lib_gpu_libs=''
lib_libpspio_fcflags=''
lib_libpspio_incs=''
lib_libpspio_ldflags=''
lib_libpspio_libs=''
lib_libxc_fcflags=''
lib_libxc_incs=''
lib_libxc_ldflags=''
lib_libxc_libs=''
lib_linalg_fcflags=''
lib_linalg_flavor=''
lib_linalg_incs=''
lib_linalg_ldflags=''
lib_linalg_libs=''
lib_math_fcflags=''
lib_math_flavor=''
lib_math_incs=''
lib_math_ldflags=''
lib_math_libs=''
lib_mpi_fcflags=''
lib_mpi_incs=''
lib_mpi_ldflags=''
lib_mpi_libs=''
lib_netcdf_fcflags=''
lib_netcdf_incs=''
lib_netcdf_ldflags=''
lib_netcdf_libs=''
lib_timer_fcflags=''
lib_timer_flavor=''
lib_timer_incs=''
lib_timer_ldflags=''
lib_timer_libs=''
lib_trio_flavor=''
lib_wannier90_bins=''
lib_wannier90_fcflags=''
lib_wannier90_incs=''
lib_wannier90_ldflags=''
lib_wannier90_libs=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
nightly_timeout=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
run_atompaw=''
run_etsf_io=''
run_fox_config=''
run_graphatom=''
run_nc_config=''
run_nccopy=''
run_ncdump=''
run_ncgen3=''
run_ncgen=''
run_wannier90_x=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
src_01_gsl_ext_incs='-I$(top_builddir)/src/01_gsl_ext -I$(top_srcdir)/src/01_gsl_ext'
src_01_interfaces_ext_incs='-I$(top_builddir)/src/01_interfaces_ext -I$(top_srcdir)/src/01_interfaces_ext'
src_01_linalg_ext_incs='-I$(top_builddir)/src/01_linalg_ext -I$(top_srcdir)/src/01_linalg_ext'
src_01_macroavnew_ext_incs='-I$(top_builddir)/src/01_macroavnew_ext -I$(top_srcdir)/src/01_macroavnew_ext'
src_02_clib_incs='-I$(top_builddir)/src/02_clib -I$(top_srcdir)/src/02_clib'
src_10_defs_incs='-I$(top_builddir)/src/10_defs -I$(top_srcdir)/src/10_defs'
src_11_memory_mpi_incs='-I$(top_builddir)/src/11_memory_mpi -I$(top_srcdir)/src/11_memory_mpi'
src_11_qespresso_ext_incs='-I$(top_builddir)/src/11_qespresso_ext -I$(top_srcdir)/src/11_qespresso_ext'
src_12_hide_mpi_incs='-I$(top_builddir)/src/12_hide_mpi -I$(top_srcdir)/src/12_hide_mpi'
src_14_hidewrite_incs='-I$(top_builddir)/src/14_hidewrite -I$(top_srcdir)/src/14_hidewrite'
src_15_gpu_toolbox_incs='-I$(top_builddir)/src/15_gpu_toolbox -I$(top_srcdir)/src/15_gpu_toolbox'
src_16_hideleave_incs='-I$(top_builddir)/src/16_hideleave -I$(top_srcdir)/src/16_hideleave'
src_18_timing_incs='-I$(top_builddir)/src/18_timing -I$(top_srcdir)/src/18_timing'
src_27_toolbox_oop_incs='-I$(top_builddir)/src/27_toolbox_oop -I$(top_srcdir)/src/27_toolbox_oop'
src_28_numeric_noabirule_incs='-I$(top_builddir)/src/28_numeric_noabirule -I$(top_srcdir)/src/28_numeric_noabirule'
src_32_util_incs='-I$(top_builddir)/src/32_util -I$(top_srcdir)/src/32_util'
src_41_geometry_incs='-I$(top_builddir)/src/41_geometry -I$(top_srcdir)/src/41_geometry'
src_42_nlstrain_incs='-I$(top_builddir)/src/42_nlstrain -I$(top_srcdir)/src/42_nlstrain'
src_42_parser_incs='-I$(top_builddir)/src/42_parser -I$(top_srcdir)/src/42_parser'
src_43_ptgroups_incs='-I$(top_builddir)/src/43_ptgroups -I$(top_srcdir)/src/43_ptgroups'
src_43_wvl_wrappers_incs='-I$(top_builddir)/src/43_wvl_wrappers -I$(top_srcdir)/src/43_wvl_wrappers'
src_44_abitypes_defs_incs='-I$(top_builddir)/src/44_abitypes_defs -I$(top_srcdir)/src/44_abitypes_defs'
src_45_geomoptim_incs='-I$(top_builddir)/src/45_geomoptim -I$(top_srcdir)/src/45_geomoptim'
src_45_psp_parser_incs='-I$(top_builddir)/src/45_psp_parser -I$(top_srcdir)/src/45_psp_parser'
src_47_xml_incs='-I$(top_builddir)/src/47_xml -I$(top_srcdir)/src/47_xml'
src_49_gw_toolbox_oop_incs='-I$(top_builddir)/src/49_gw_toolbox_oop -I$(top_srcdir)/src/49_gw_toolbox_oop'
src_51_manage_mpi_incs='-I$(top_builddir)/src/51_manage_mpi -I$(top_srcdir)/src/51_manage_mpi'
src_52_fft_mpi_noabirule_incs='-I$(top_builddir)/src/52_fft_mpi_noabirule -I$(top_srcdir)/src/52_fft_mpi_noabirule'
src_52_manage_cuda_incs='-I$(top_builddir)/src/52_manage_cuda -I$(top_srcdir)/src/52_manage_cuda'
src_53_abiutil_incs='-I$(top_builddir)/src/53_abiutil -I$(top_srcdir)/src/53_abiutil'
src_53_ffts_incs='-I$(top_builddir)/src/53_ffts -I$(top_srcdir)/src/53_ffts'
src_53_spacepar_incs='-I$(top_builddir)/src/53_spacepar -I$(top_srcdir)/src/53_spacepar'
src_56_mixing_incs='-I$(top_builddir)/src/56_mixing -I$(top_srcdir)/src/56_mixing'
src_56_recipspace_incs='-I$(top_builddir)/src/56_recipspace -I$(top_srcdir)/src/56_recipspace'
src_56_xc_incs='-I$(top_builddir)/src/56_xc -I$(top_srcdir)/src/56_xc'
src_57_iovars_incs='-I$(top_builddir)/src/57_iovars -I$(top_srcdir)/src/57_iovars'
src_59_io_mpi_incs='-I$(top_builddir)/src/59_io_mpi -I$(top_srcdir)/src/59_io_mpi'
src_61_ionetcdf_incs='-I$(top_builddir)/src/61_ionetcdf -I$(top_srcdir)/src/61_ionetcdf'
src_62_cg_noabirule_incs='-I$(top_builddir)/src/62_cg_noabirule -I$(top_srcdir)/src/62_cg_noabirule'
src_62_iowfdenpot_incs='-I$(top_builddir)/src/62_iowfdenpot -I$(top_srcdir)/src/62_iowfdenpot'
src_62_occeig_incs='-I$(top_builddir)/src/62_occeig -I$(top_srcdir)/src/62_occeig'
src_62_poisson_incs='-I$(top_builddir)/src/62_poisson -I$(top_srcdir)/src/62_poisson'
src_62_wvl_wfs_incs='-I$(top_builddir)/src/62_wvl_wfs -I$(top_srcdir)/src/62_wvl_wfs'
src_63_bader_incs='-I$(top_builddir)/src/63_bader -I$(top_srcdir)/src/63_bader'
src_64_atompaw_incs='-I$(top_builddir)/src/64_atompaw -I$(top_srcdir)/src/64_atompaw'
src_65_nonlocal_incs='-I$(top_builddir)/src/65_nonlocal -I$(top_srcdir)/src/65_nonlocal'
src_65_psp_incs='-I$(top_builddir)/src/65_psp -I$(top_srcdir)/src/65_psp'
src_66_paw_incs='-I$(top_builddir)/src/66_paw -I$(top_srcdir)/src/66_paw'
src_66_wfs_incs='-I$(top_builddir)/src/66_wfs -I$(top_srcdir)/src/66_wfs'
src_67_common_incs='-I$(top_builddir)/src/67_common -I$(top_srcdir)/src/67_common'
src_68_dmft_incs='-I$(top_builddir)/src/68_dmft -I$(top_srcdir)/src/68_dmft'
src_68_recursion_incs='-I$(top_builddir)/src/68_recursion -I$(top_srcdir)/src/68_recursion'
src_68_rsprc_incs='-I$(top_builddir)/src/68_rsprc -I$(top_srcdir)/src/68_rsprc'
src_69_wfdesc_incs='-I$(top_builddir)/src/69_wfdesc -I$(top_srcdir)/src/69_wfdesc'
src_70_gw_incs='-I$(top_builddir)/src/70_gw -I$(top_srcdir)/src/70_gw'
src_71_bse_incs='-I$(top_builddir)/src/71_bse -I$(top_srcdir)/src/71_bse'
src_72_response_incs='-I$(top_builddir)/src/72_response -I$(top_srcdir)/src/72_response'
src_77_ddb_incs='-I$(top_builddir)/src/77_ddb -I$(top_srcdir)/src/77_ddb'
src_77_lwf_incs='-I$(top_builddir)/src/77_lwf -I$(top_srcdir)/src/77_lwf'
src_77_suscep_incs='-I$(top_builddir)/src/77_suscep -I$(top_srcdir)/src/77_suscep'
src_79_seqpar_mpi_incs='-I$(top_builddir)/src/79_seqpar_mpi -I$(top_srcdir)/src/79_seqpar_mpi'
src_83_cut3d_incs='-I$(top_builddir)/src/83_cut3d -I$(top_srcdir)/src/83_cut3d'
src_95_drive_incs='-I$(top_builddir)/src/95_drive -I$(top_srcdir)/src/95_drive'
src_incs_incs='-I$(top_builddir)/src/incs -I$(top_srcdir)/src/incs'
src_mods_incs='-I$(top_builddir)/src/mods -I$(top_srcdir)/src/mods'
subdirs=''
sysconfdir='${prefix}/etc'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'
with_algo_flavor='none'
with_algo_incs=''
with_algo_libs=''
with_atompaw_bins=''
with_atompaw_incs=''
with_atompaw_libs=''
with_bigdft_incs=''
with_bigdft_libs=''
with_config_file=''
with_dft_flavor='atompaw+bigdft+libxc+wannier90'
with_etsf_io_incs=''
with_etsf_io_libs=''
with_fc_vendor=''
with_fc_version=''
with_fft_flavor='none'
with_fft_incs=''
with_fft_libs=''
with_fox_incs=''
with_fox_libs=''
with_gnu_ld=''
with_gpu_cflags=''
with_gpu_cppflags=''
with_gpu_flavor='cuda-double'
with_gpu_incs=''
with_gpu_ldflags=''
with_gpu_libs=''
with_gpu_prefix=''
with_libpspio_incs=''
with_libpspio_libs=''
with_libxc_incs=''
with_libxc_libs=''
with_linalg_flavor='netlib'
with_linalg_incs=''
with_linalg_libs=''
with_math_flavor='none'
with_math_incs=''
with_math_libs=''
with_mpi_incs=''
with_mpi_level=''
with_mpi_libs=''
with_mpi_prefix='/usr/lib64/openmpi/'
with_netcdf_incs=''
with_netcdf_libs=''
with_tardir='/home/weitong/.abinit/tarballs'
with_test_timeout='0'
with_timer_flavor='abinit'
with_timer_incs=''
with_timer_libs=''
with_trio_flavor='netcdf+etsf_io'
with_wannier90_bins=''
with_wannier90_incs=''
with_wannier90_libs=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "ABINIT"
#define PACKAGE_TARNAME "abinit"
#define PACKAGE_VERSION "7.2.1"
#define PACKAGE_STRING "ABINIT 7.2.1"
#define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
#define PACKAGE_URL ""
#define PACKAGE "abinit"
#define VERSION "7.2.1"
#define ABINIT_VERSION "7.2.1"
#define ABINIT_VERSION_MAJOR "7"
#define ABINIT_VERSION_MINOR "2"
#define ABINIT_VERSION_MICRO "1"
#define ABINIT_VERSION_BUILD "20130511"
#define ABINIT_VERSION_BASE "7.2"
#define HAVE_OS_LINUX 1

configure: exit 1
