This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Wannier90 configure 1.2.0.1, which was
generated by GNU Autoconf 2.65.  Invocation command line was

  $ ./configure --prefix=/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports --bindir=/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/bin --libdir=/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib --program-suffix=-abinit --disable-shared --enable-static

## --------- ##
## Platform. ##
## --------- ##

hostname = kun
uname -m = x86_64
uname -r = 3.16.0-4-amd64
uname -s = Linux
uname -v = #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09)

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/quantum/bin
PATH: /home/quantum/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/local/games
PATH: /usr/games
PATH: /opt/x86_open64-4.5.2.1/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2370: checking build system type
configure:2384: result: x86_64-unknown-linux-gnu
configure:2404: checking host system type
configure:2417: result: x86_64-unknown-linux-gnu
configure:2437: checking target system type
configure:2450: result: x86_64-unknown-linux-gnu
configure:2492: checking for a BSD-compatible install
configure:2560: result: /usr/bin/install -c
configure:2571: checking whether build environment is sane
configure:2621: result: yes
configure:2762: checking for a thread-safe mkdir -p
configure:2801: result: /bin/mkdir -p
configure:2814: checking for gawk
configure:2830: found /usr/bin/gawk
configure:2841: result: gawk
configure:2852: checking whether make sets $(MAKE)
configure:2874: result: yes
configure:2995: checking for style of include used by make
configure:3023: result: GNU
configure:3093: checking for gcc
configure:3120: result: /usr/bin/mpicc
configure:3349: checking for C compiler version
configure:3358: /usr/bin/mpicc --version >&5
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3369: $? = 0
configure:3358: /usr/bin/mpicc -v >&5
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
configure:3369: $? = 0
configure:3358: /usr/bin/mpicc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3369: $? = 4
configure:3358: /usr/bin/mpicc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3369: $? = 4
configure:3389: checking whether the C compiler works
configure:3411: /usr/bin/mpicc -g -O2  -I/usr/include   conftest.c -L/opt/acml5.3.1/gfortran64_int64/lib -lacml  -L/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib -letsf_io_low_level -letsf_io_utils -letsf_io  >&5
configure:3415: $? = 0
configure:3464: result: yes
configure:3467: checking for C compiler default output file name
configure:3469: result: a.out
configure:3475: checking for suffix of executables
configure:3482: /usr/bin/mpicc -o conftest -g -O2  -I/usr/include   conftest.c -L/opt/acml5.3.1/gfortran64_int64/lib -lacml  -L/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib -letsf_io_low_level -letsf_io_utils -letsf_io  >&5
configure:3486: $? = 0
configure:3508: result: 
configure:3530: checking whether we are cross compiling
configure:3538: /usr/bin/mpicc -o conftest -g -O2  -I/usr/include   conftest.c -L/opt/acml5.3.1/gfortran64_int64/lib -lacml  -L/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib -letsf_io_low_level -letsf_io_utils -letsf_io  >&5
configure:3542: $? = 0
configure:3549: ./conftest
./conftest: error while loading shared libraries: libacml.so: cannot open shared object file: No such file or directory
configure:3553: $? = 127
configure:3560: error: in `/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1':
configure:3564: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CC_set=set
ac_cv_env_CC_value=/usr/bin/mpicc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-g -O2'
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value=' -I/usr/include'
ac_cv_env_CPP_set=set
ac_cv_env_CPP_value='/usr/bin/mpicc -E'
ac_cv_env_FCFLAGS_set=set
ac_cv_env_FCFLAGS_value='-ffree-form -g -ffree-line-length-none   -O2 -mtune=native -march=native -g -O2 -I/usr/include'
ac_cv_env_FC_set=set
ac_cv_env_FC_value=/usr/bin/mpif90
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value=' '
ac_cv_env_LIBS_set=set
ac_cv_env_LIBS_value='-L/opt/acml5.3.1/gfortran64_int64/lib -lacml  -L/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib -letsf_io_low_level -letsf_io_utils -letsf_io '
ac_cv_env_W90_LIBDIR_set=
ac_cv_env_W90_LIBDIR_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=/usr/bin/mpicc
ac_cv_prog_make_make_set=yes
ac_cv_target=x86_64-unknown-linux-gnu

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/missing --run aclocal-1.11'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/missing --run tar'
AR='ar'
AUTOCONF='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/missing --run autoconf'
AUTOHEADER='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/missing --run autoheader'
AUTOMAKE='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/missing --run automake-1.11'
AWK='gawk'
CC='/usr/bin/mpicc'
CCDEPMODE=''
CFLAGS='-g -O2'
CPP='/usr/bin/mpicc -E'
CPPFLAGS=' -I/usr/include'
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DO_BUILD_TEXDOCS_FALSE=''
DO_BUILD_TEXDOCS_TRUE=''
DSYMUTIL=''
DUMPBIN=''
DVIPDF=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FC='/usr/bin/mpif90'
FCFLAGS='-ffree-form -g -ffree-line-length-none   -O2 -mtune=native -march=native -g -O2 -I/usr/include'
FCFLAGS_F90=''
FGREP=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LATEX=''
LD=''
LDFLAGS=' '
LIBOBJS=''
LIBS='-L/opt/acml5.3.1/gfortran64_int64/lib -lacml  -L/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib -letsf_io_low_level -letsf_io_utils -letsf_io '
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LTOBJEXT=''
MAKEINFO='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/missing --run makeinfo'
MKDIR_P='/bin/mkdir -p'
MODEXT=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='wannier90'
PACKAGE_BUGREPORT='a.mostofi@imperial.ac.uk'
PACKAGE_NAME='Wannier90'
PACKAGE_STRING='Wannier90 1.2.0.1'
PACKAGE_TARNAME='wannier90'
PACKAGE_URL=''
PACKAGE_VERSION='1.2.0.1'
PATH_SEPARATOR=':'
PERL=''
RANLIB='ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
VERSION='1.2.0.1'
W90_FCOPTS=''
W90_LDOPTS=''
W90_LIBDIR=''
W90_LIBS=''
ac_ct_CC='/usr/bin/mpicc'
ac_ct_DUMPBIN=''
ac_ct_FC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
bindir='/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/sources/wannier90-1.2.0.1/config/gnu/install-sh'
libdir='/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
lt_ECHO='echo'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/home/quantum/SIMUcode/abinit-7.10.5/build/fallbacks/exports'
program_transform_name='s&$$&-abinit&'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'
w90_fc_path=''
w90_fc_vendor=''
w90_fc_version=''
w90_fc_wrap=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Wannier90"
#define PACKAGE_TARNAME "wannier90"
#define PACKAGE_VERSION "1.2.0.1"
#define PACKAGE_STRING "Wannier90 1.2.0.1"
#define PACKAGE_BUGREPORT "a.mostofi@imperial.ac.uk"
#define PACKAGE_URL ""
#define PACKAGE "wannier90"
#define VERSION "1.2.0.1"

configure: exit 1
