This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by ABINIT configure 6.0.3, which was
generated by GNU Autoconf 2.63.  Invocation command line was

  $ ../configure --prefix=/CHPC/home/nmonama/abinit-6.0.3 --enable-mpi

## --------- ##
## Platform. ##
## --------- ##

hostname = chpcfen
uname -m = ppc64
uname -r = 2.6.16.46-0.12-ppc64
uname -s = Linux
uname -v = #1 SMP Thu May 17 14:00:09 UTC 2007

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = ppc64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /bgsys/drivers/ppcfloor/bin
PATH: /CHPC/home/nmonama/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /usr/X11R6/bin
PATH: /bin
PATH: /usr/games
PATH: /opt/gnome/bin
PATH: /opt/kde3/bin
PATH: /bgsys/drivers/ppcfloor/bin
PATH: /opt/ibmcmp/xlf/bg/11.1/bin
PATH: /opt/ibmcmp/vacpp/bg/9.0/bin
PATH: /opt/ibmll/LoadL/full/bin
PATH: /usr/lpp/mmfs/bin
PATH: /usr/lib/mit/bin
PATH: /usr/lib/mit/sbin
PATH: /bgsys/drivers/ppcfloor/bin
PATH: /opt/ibmcmp/xlf/bg/11.1/bin
PATH: /opt/ibmcmp/vacpp/bg/9.0/bin
PATH: /opt/ibmll/LoadL/full/bin
PATH: /usr/lpp/mmfs/bin
PATH: /CHPC/usr/local/ferret/bin
PATH: /bgsys/drivers/ppcfloor/bin
PATH: /bgsys/drivers/ppcfloor/comm/bin
PATH: /opt/csm/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /usr/X11R6/bin
PATH: /bin
PATH: /usr/games
PATH: /opt/bin
PATH: /opt/gnome/bin
PATH: /opt/kde3/bin
PATH: /usr/local/ofed/bin
PATH: /usr/local/ofed/sbin
PATH: /opt/pathscale/bin
PATH: /CHPC/usr/local/ferret/bin
PATH: /usr/lpp/mmfs/bin
PATH: /opt/ibmll/LoadL/full/bin
PATH: /opt/ibmcmp/xlf/bg/11.1/bin/xlf
PATH: /CHPC/home/nmonama/bin
PATH: /CHPC/home/nmonama/cmake-2.6.4/build/bin
PATH: /bgsys/drivers/ppcfloor/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2766: checking build system type
configure:2784: result: powerpc64-unknown-linux-gnu
configure:2806: checking host system type
configure:2821: result: powerpc64-unknown-linux-gnu
configure:2843: checking target system type
configure:2858: result: powerpc64-unknown-linux-gnu
configure:2902: checking for a BSD-compatible install
configure:2970: result: /usr/bin/install -c
configure:2981: checking whether build environment is sane
configure:3041: result: yes
configure:3182: checking for a thread-safe mkdir -p
configure:3221: result: /bin/mkdir -p
configure:3234: checking for gawk
configure:3250: found /usr/bin/gawk
configure:3261: result: gawk
configure:3272: checking whether make sets $(MAKE)
configure:3294: result: yes
configure:3684: checking whether make sets $(MAKE)
configure:3706: result: yes
configure:3729: checking for a BSD-compatible install
configure:3797: result: /usr/bin/install -c
configure:3808: checking whether ln -s works
configure:3812: result: yes
configure:3819: checking for a sed that does not truncate output
configure:3885: result: /usr/bin/sed
configure:3894: checking for gawk
configure:3921: result: gawk
configure:3932: checking for grep that handles long lines and -e
configure:3992: result: /usr/bin/grep
configure:3999: checking for egrep
configure:4063: result: /usr/bin/grep -E
configure:4071: checking for a thread-safe mkdir -p
configure:4110: result: /bin/mkdir -p
configure:6446: ABINIT version: 6.0.3
configure:6456: M4 010413 - Autoconf 026300 - Automake 011100 - Libtool 020204
configure:6467: reporting user interface changes:
configure:6470:  * new option --enable-cuda is available
configure:6473:  * --enable-debug has a new meaning
configure:6475:    please check that --enable-debug="yes" is OK for you
configure:6478:  * new option --enable-etsf-io-test is available
configure:6481:  * --enable-tricks renamed --enable-hints
configure:6489:  * --enable-etsf-xc renamed --enable-libxc
configure:6497:  * --enable-mpi has a new meaning
configure:6499:    please check that --enable-mpi="yes" is OK for you
configure:6502:  * --enable-mpi-io-buggy renamed --enable-mpi-io-test
configure:6510:  * --enable-optlevel renamed --enable-optim
configure:6518:  * --enable-xmlf90 removed
configure:6526:  * new option --with-cuda-includes is available
configure:6529:  * new option --with-cuda-libs is available
configure:6532:  * new option --with-etsf-io-test-includes is available
configure:6535:  * new option --with-etsf-io-test-libs is available
configure:6538:  * --with-etsf-xc-includes renamed --with-libxc-includes
configure:6546:  * --with-etsf-xc-libs renamed --with-libxc-libs
configure:6554:  * --with-mpi-cc-ldflags removed
configure:6562:  * --with-mpi-cc-libs removed
configure:6570:  * --with-mpi-cflags removed
configure:6578:  * --with-mpi-cppflags removed
configure:6586:  * --with-mpi-cxx-ldflags removed
configure:6594:  * --with-mpi-cxx-libs removed
configure:6602:  * --with-mpi-cxxflags removed
configure:6610:  * --with-mpi-fc-ldflags removed
configure:6618:  * --with-mpi-fc-libs removed
configure:6626:  * --with-mpi-fcflags removed
configure:6634:  * --with-mpi-prefix has a new meaning
configure:6636:    please check that --with-mpi-prefix="" is OK for you
configure:6639:  * --with-xmlf90-includes removed
configure:6647:  * --with-xmlf90-libs removed
configure:6689: checking consistency of external prerequisite options
configure:6723:  |---> all OK
configure:6726: 
configure:6735: checking consistency of plug-in options
configure:6748:  |---> all OK
configure:6751: 
configure:6769: parsing command-line options
configure:7994: Initializing MPI support
configure:8129: checking for mpirun
configure:8145: found /bgsys/drivers/ppcfloor/bin/mpirun
configure:8156: result: mpirun
configure:8168: WARNING: MPI runner mpirun may be incompatible with MPI compilers
configure:8223: compiler checks deferred
configure:8282: checking for sh
configure:8300: found /bin/sh
configure:8313: result: /bin/sh
configure:8323: checking for perl
configure:8341: found /usr/bin/perl
configure:8354: result: /usr/bin/perl
configure:8364: checking for rm
configure:8382: found /bin/rm
configure:8395: result: /bin/rm
configure:8405: checking for mv
configure:8423: found /bin/mv
configure:8436: result: /bin/mv
configure:8446: checking for tar
configure:8464: found /bin/tar
configure:8477: result: /bin/tar
configure:8487: checking for latex
configure:8518: result: /bin/false
configure:8528: checking for dvips
configure:8559: result: /bin/false
configure:8569: checking for dvipdf
configure:8587: found /usr/bin/dvipdf
configure:8600: result: /usr/bin/dvipdf
configure:8610: checking for ps2pdf
configure:8628: found /usr/bin/ps2pdf
configure:8641: result: /usr/bin/ps2pdf
configure:8651: checking for markdown
configure:8684: result: no
configure:8691: checking for wget
configure:8709: found /usr/bin/wget
configure:8722: result: /usr/bin/wget
configure:8733: using internal version of MarkDown
configure:8974: checking for mpicc
configure:8992: found /bgsys/drivers/ppcfloor/comm/bin/mpicc
configure:9004: result: /bgsys/drivers/ppcfloor/comm/bin/mpicc
configure:9067: checking for gcc
configure:9094: result: mpicc
configure:9326: checking for C compiler version
configure:9334: mpicc --version >&5
powerpc-bgp-linux-gcc (GCC) 4.1.2 (BGP)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:9338: $? = 0
configure:9345: mpicc -v >&5
mpicc for 1.0.7
Reading specs from /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/specs
Target: powerpc-bgp-linux
Configured with: /bgsys/drivers/ppcfloor/toolchain/gnu/gcc-4.1.2/configure --prefix=/bgsys/drivers/ppcfloor/gnu-linux --target=powerpc-bgp-linux --enable-multilib --enable-shared --enable-secureplt --disable-libmudflap --disable-libspp --with-headers=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/include --with-libs=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/lib --with-long-double-128 --enable-threads=posix --enable-languages=c,c++,fortran
Thread model: posix
gcc version 4.1.2 (BGP)
configure:9349: $? = 0
configure:9356: mpicc -V >&5
powerpc-bgp-linux-gcc: '-V' must come at the start of the command line
configure:9360: $? = 1
configure:9383: checking for C compiler default output file name
configure:9405: mpicc -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:9409: $? = 0
configure:9447: result: a.out
configure:9466: checking whether the C compiler works
configure:9476: ./a.out
configure:9480: $? = 0
configure:9499: result: yes
configure:9506: checking whether we are cross compiling
configure:9508: result: no
configure:9511: checking for suffix of executables
configure:9518: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:9522: $? = 0
configure:9548: result: 
configure:9554: checking for suffix of object files
configure:9580: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:9584: $? = 0
configure:9609: result: o
configure:9613: checking whether we are using the GNU C compiler
configure:9642: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:9649: $? = 0
configure:9666: result: yes
configure:9675: checking whether mpicc accepts -g
configure:9705: mpicc -c -g  conftest.c >&5
configure:9712: $? = 0
configure:9813: result: yes
configure:9830: checking for mpicc option to accept ISO C89
configure:9904: mpicc  -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:9911: $? = 0
configure:9934: result: none needed
configure:9963: checking for style of include used by make
configure:9991: result: GNU
configure:10016: checking dependency style of mpicc
configure:10126: result: gcc3
configure:10202: checking how to run the C preprocessor
configure:10242: mpicc -E  conftest.c
configure:10249: $? = 0
configure:10280: mpicc -E  conftest.c
conftest.c:16:28: error: ac_nonexistent.h: No such file or directory
configure:10287: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.0.3"
| #define PACKAGE_STRING "ABINIT 6.0.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE "abinit"
| #define VERSION "6.0.3"
| #define ABINIT_VERSION "6.0.3"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "0"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20100504"
| #define ABINIT_VERSION_BASE "6.0"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:10320: result: mpicc -E
configure:10349: mpicc -E  conftest.c
configure:10356: $? = 0
configure:10387: mpicc -E  conftest.c
conftest.c:16:28: error: ac_nonexistent.h: No such file or directory
configure:10394: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.0.3"
| #define PACKAGE_STRING "ABINIT 6.0.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE "abinit"
| #define VERSION "6.0.3"
| #define ABINIT_VERSION "6.0.3"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "0"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20100504"
| #define ABINIT_VERSION_BASE "6.0"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:10444: checking for ANSI C header files
configure:10474: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10481: $? = 0
configure:10580: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10584: $? = 0
configure:10590: ./conftest
configure:10594: $? = 0
configure:10612: result: yes
configure:10636: checking for sys/types.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for sys/stat.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for stdlib.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for string.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for memory.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for strings.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for inttypes.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for stdint.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10636: checking for unistd.h
configure:10657: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10664: $? = 0
configure:10681: result: yes
configure:10700: checking which type of compiler we have
configure:10913: result: gnu 
configure:10938: checking stddef.h usability
configure:10955: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10962: $? = 0
configure:10976: result: yes
configure:10980: checking stddef.h presence
configure:10995: mpicc -E  conftest.c
configure:11002: $? = 0
configure:11016: result: yes
configure:11049: checking for stddef.h
configure:11058: result: yes
configure:10938: checking stdarg.h usability
configure:10955: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:10962: $? = 0
configure:10976: result: yes
configure:10980: checking stdarg.h presence
configure:10995: mpicc -E  conftest.c
configure:11002: $? = 0
configure:11016: result: yes
configure:11049: checking for stdarg.h
configure:11058: result: yes
configure:11092: checking stdio.h usability
configure:11109: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:11116: $? = 0
configure:11130: result: yes
configure:11134: checking stdio.h presence
configure:11149: mpicc -E  conftest.c
configure:11156: $? = 0
configure:11170: result: yes
configure:11203: checking for stdio.h
configure:11212: result: yes
configure:11092: checking malloc.h usability
configure:11109: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:11116: $? = 0
configure:11130: result: yes
configure:11134: checking malloc.h presence
configure:11149: mpicc -E  conftest.c
configure:11156: $? = 0
configure:11170: result: yes
configure:11203: checking for malloc.h
configure:11212: result: yes
configure:11092: checking math.h usability
configure:11109: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:11116: $? = 0
configure:11130: result: yes
configure:11134: checking math.h presence
configure:11149: mpicc -E  conftest.c
configure:11156: $? = 0
configure:11170: result: yes
configure:11203: checking for math.h
configure:11212: result: yes
configure:11092: checking termios.h usability
configure:11109: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:11116: $? = 0
configure:11130: result: yes
configure:11134: checking termios.h presence
configure:11149: mpicc -E  conftest.c
configure:11156: $? = 0
configure:11170: result: yes
configure:11203: checking for termios.h
configure:11212: result: yes
configure:11235: checking for abort
configure:11291: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
conftest.c:56: warning: conflicting types for built-in function 'abort'
configure:11298: $? = 0
configure:11320: result: yes
configure:11340: checking size of int
configure:11645: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:11649: $? = 0
configure:11655: ./conftest
configure:11659: $? = 0
configure:11685: result: 4
configure:11699: checking size of unsigned int
configure:12004: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:12008: $? = 0
configure:12014: ./conftest
configure:12018: $? = 0
configure:12044: result: 4
configure:12058: checking size of float
configure:12363: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:12367: $? = 0
configure:12373: ./conftest
configure:12377: $? = 0
configure:12403: result: 4
configure:12417: checking size of double
configure:12722: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:12726: $? = 0
configure:12732: ./conftest
configure:12736: $? = 0
configure:12762: result: 8
configure:12776: checking size of long
configure:13081: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:13085: $? = 0
configure:13091: ./conftest
configure:13095: $? = 0
configure:13121: result: 4
configure:13135: checking size of unsigned long
configure:13440: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:13444: $? = 0
configure:13450: ./conftest
configure:13454: $? = 0
configure:13480: result: 4
configure:13494: checking size of long long
configure:13799: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:13803: $? = 0
configure:13809: ./conftest
configure:13813: $? = 0
configure:13839: result: 8
configure:13853: checking size of unsigned long long
configure:14158: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:14162: $? = 0
configure:14168: ./conftest
configure:14172: $? = 0
configure:14198: result: 8
configure:14212: checking size of size_t
configure:14517: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:14521: $? = 0
configure:14527: ./conftest
configure:14531: $? = 0
configure:14557: result: 4
configure:14571: checking size of ptrdiff_t
configure:14876: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c  >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:14880: $? = 0
configure:14886: ./conftest
configure:14890: $? = 0
configure:14916: result: 4
configure:14927: checking for an ANSI C-conforming const
configure:15002: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:15009: $? = 0
configure:15024: result: yes
configure:15034: checking for size_t
configure:15062: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:15069: $? = 0
configure:15096: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
conftest.c: In function 'main':
conftest.c:80: error: expected expression before ')' token
configure:15103: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.0.3"
| #define PACKAGE_STRING "ABINIT 6.0.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE "abinit"
| #define VERSION "6.0.3"
| #define ABINIT_VERSION "6.0.3"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "0"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20100504"
| #define ABINIT_VERSION_BASE "6.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CC_GNU 1
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ABORT 1
| #define SIZEOF_INT 4
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG 4
| #define SIZEOF_UNSIGNED_LONG 4
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_SIZE_T 4
| #define SIZEOF_PTRDIFF_T 4
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| int
| main ()
| {
| if (sizeof ((size_t)))
| 	  return 0;
|   ;
|   return 0;
| }
configure:15126: result: yes
configure:15148: checking whether byte ordering is bigendian
configure:15173: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
conftest.c:45: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'a'
configure:15180: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.0.3"
| #define PACKAGE_STRING "ABINIT 6.0.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE "abinit"
| #define VERSION "6.0.3"
| #define ABINIT_VERSION "6.0.3"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "0"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20100504"
| #define ABINIT_VERSION_BASE "6.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CC_GNU 1
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ABORT 1
| #define SIZEOF_INT 4
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG 4
| #define SIZEOF_UNSIGNED_LONG 4
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_SIZE_T 4
| #define SIZEOF_PTRDIFF_T 4
| /* end confdefs.h.  */
| #ifndef __APPLE_CC__
| 	       not a universal capable compiler
| 	     #endif
| 	     typedef int dummy;
| 
configure:15230: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:15237: $? = 0
configure:15269: mpicc -c -O3 -qarch=450d -qtune=450  conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:15276: $? = 0
configure:15528: result: yes
configure:15781: checking for mpicxx
configure:15799: found /bgsys/drivers/ppcfloor/comm/bin/mpicxx
configure:15811: result: /bgsys/drivers/ppcfloor/comm/bin/mpicxx
configure:15938: checking for C++ compiler version
configure:15946: mpicxx --version >&5
powerpc-bgp-linux-g++ (GCC) 4.1.2 (BGP)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:15950: $? = 0
configure:15957: mpicxx -v >&5
mpicxx for 1.0.7
Reading specs from /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/specs
Target: powerpc-bgp-linux
Configured with: /bgsys/drivers/ppcfloor/toolchain/gnu/gcc-4.1.2/configure --prefix=/bgsys/drivers/ppcfloor/gnu-linux --target=powerpc-bgp-linux --enable-multilib --enable-shared --enable-secureplt --disable-libmudflap --disable-libspp --with-headers=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/include --with-libs=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/lib --with-long-double-128 --enable-threads=posix --enable-languages=c,c++,fortran
Thread model: posix
gcc version 4.1.2 (BGP)
configure:15961: $? = 0
configure:15968: mpicxx -V >&5
powerpc-bgp-linux-g++: '-V' must come at the start of the command line
configure:15972: $? = 1
configure:15975: checking whether we are using the GNU C++ compiler
configure:16004: mpicxx -c -O3 -qarch=450d -qtune=450  conftest.cpp >&5
powerpc-bgp-linux-g++: unrecognized option '-qarch=450d'
powerpc-bgp-linux-g++: unrecognized option '-qtune=450'
configure:16011: $? = 0
configure:16028: result: yes
configure:16037: checking whether mpicxx accepts -g
configure:16067: mpicxx -c -g  conftest.cpp >&5
configure:16074: $? = 0
configure:16175: result: yes
configure:16200: checking dependency style of mpicxx
configure:16310: result: gcc3
configure:16339: checking which type of C++ compiler we have
configure:16549: result: gnu 4.1
configure:16787: checking for mpif90
configure:16805: found /bgsys/drivers/ppcfloor/comm/bin/mpif90
configure:16817: result: /bgsys/drivers/ppcfloor/comm/bin/mpif90
configure:16938: checking for Fortran compiler version
configure:16946: mpif90 --version >&5
GNU Fortran 95 (GCC) 4.1.2 (BGP)
Copyright (C) 2006 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

configure:16950: $? = 0
configure:16957: mpif90 -v >&5
mpif90 for 1.0.7
Reading specs from /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/specs
Target: powerpc-bgp-linux
Configured with: /bgsys/drivers/ppcfloor/toolchain/gnu/gcc-4.1.2/configure --prefix=/bgsys/drivers/ppcfloor/gnu-linux --target=powerpc-bgp-linux --enable-multilib --enable-shared --enable-secureplt --disable-libmudflap --disable-libspp --with-headers=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/include --with-libs=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/lib --with-long-double-128 --enable-threads=posix --enable-languages=c,c++,fortran
Thread model: posix
gcc version 4.1.2 (BGP)
configure:16961: $? = 0
configure:16968: mpif90 -V >&5
powerpc-bgp-linux-gfortran: '-V' must come at the start of the command line
configure:16972: $? = 1
configure:16980: checking whether we are using the GNU Fortran compiler
configure:16999: mpif90 -c   conftest.F >&5
configure:17006: $? = 0
configure:17023: result: yes
configure:17029: checking whether mpif90 accepts -g
configure:17046: mpif90 -c -g  conftest.f >&5
configure:17053: $? = 0
configure:17069: result: yes
configure:17153: Fortran source will be preprocessed using C preprocessor
configure:17174: checking which type of Fortran compiler we have
configure:17568: result: gnu 4.1
configure:17576: checking fortran 90 modules extension
configure:17609: mpif90 -c -g -O2  conftest.f >&5
configure:17616: $? = 0
configure:17647: result: mod
configure:17662: checking for Fortran flag to compile .F90 files
configure:17684: mpif90 -c -g -O2  conftest.F90 >&5
configure:17691: $? = 0
configure:17710: result: none
configure:17742: checking whether the Fortran compiler accepts exit()
configure:17763: mpif90 -o conftest -g -O2   conftest.F90  >&5
configure:17770: $? = 0
configure:17804: result: yes
configure:17810: checking whether the Fortran compiler accepts flush()
configure:17831: mpif90 -o conftest -g -O2   conftest.F90  >&5
configure:17838: $? = 0
configure:17872: result: yes
configure:17878: checking whether the Fortran compiler accepts flush_()
configure:17899: mpif90 -o conftest -g -O2   conftest.F90  >&5
/tmp/cc5GKvNK.o: In function `MAIN__':
/CHPC/home/nmonama/abinit-6.0.3/build/conftest.F90:3: undefined reference to `flush_'
collect2: ld returned 1 exit status
configure:17906: $? = 1
configure: failed program was:
|       program main
| 
|             call flush_()
| 
|       end
configure:17940: result: no
configure:17946: checking whether the Fortran compiler accepts gamma()
configure:17968: mpif90 -o conftest -g -O2   conftest.F90  >&5
configure:17975: $? = 0
configure:18009: result: yes
configure:18015: checking whether the Fortran compiler accepts get_environment_variable
configure:18039: mpif90 -o conftest -g -O2   conftest.F90  >&5
configure:18046: $? = 0
configure:18080: result: yes
configure:18086: checking whether the Fortran compiler accepts quadruple integers
configure:18108: mpif90 -o conftest -g -O2   conftest.F90  >&5
 In file conftest.F90:3

              integer*16 my_int
                       1
Error: Old-style type declaration INTEGER*16 not supported at (1)
configure:18115: $? = 1
configure: failed program was:
|       program main
| 
|               integer*16 my_int
| 
|       end
configure:18150: result: no
configure:18156: checking whether the Fortran compiler accepts long lines
configure:18177: mpif90 -o conftest -g -O2   conftest.F90  >&5
 In file conftest.F90:3

         write(*,*)'01234567890123456789012345678901234567890123456789012345678
                  1
Error: Unterminated character constant beginning at (1)
configure:18184: $? = 1
configure: failed program was:
|       program main
| 
|          write(*,*)'0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789' !142
| 
|       end
configure:18218: result: no
configure:18224: checking whether the Fortran compiler accepts the null() intrinsic
configure:18249: mpif90 -o conftest -g -O2   conftest.F90  >&5
configure:18256: $? = 0
configure:18290: result: yes
configure:18314: checking how to get verbose linking output from mpif90
configure:18330: mpif90 -c   conftest.F90 >&5
configure:18337: $? = 0
configure:18359: mpif90 -o conftest -v conftest.F90
mpif90 for 1.0.7
Reading specs from /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/specs
Target: powerpc-bgp-linux
Configured with: /bgsys/drivers/ppcfloor/toolchain/gnu/gcc-4.1.2/configure --prefix=/bgsys/drivers/ppcfloor/gnu-linux --target=powerpc-bgp-linux --enable-multilib --enable-shared --enable-secureplt --disable-libmudflap --disable-libspp --with-headers=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/include --with-libs=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/lib --with-long-double-128 --enable-threads=posix --enable-languages=c,c++,fortran
Thread model: posix
gcc version 4.1.2 (BGP)
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../libexec/gcc/powerpc-bgp-linux/4.1.2/cc1 -E -lang-fortran -traditional-cpp -D_LANGUAGE_FORTRAN -quiet -v -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/sys/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -iprefix /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/ -D__unix__ -D__gnu_linux__ -D__linux__ -Dunix -D__unix -Dlinux -D__linux -Asystem=linux -Asystem=unix -Asystem=posix conftest.F90 -mstrict-align -msecure-plt -fno-underscoring -o /tmp/ccoL63NA.f95
ignoring nonexistent directory "/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/include"
ignoring duplicate directory "/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/include"
ignoring duplicate directory "/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/sys-include"
ignoring nonexistent directory "/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/include"
ignoring duplicate directory "/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include"
#include "..." search starts here:
#include <...> search starts here:
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/sys/include
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/include
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/sys-include
End of search list.
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../libexec/gcc/powerpc-bgp-linux/4.1.2/f951 /tmp/ccoL63NA.f95 -ffree-form -mstrict-align -msecure-plt -quiet -dumpbase conftest.F90 -auxbase conftest -version -fno-underscoring -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/sys/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -fpreprocessed -o /tmp/cciSUIx4.s
GNU F95 version 4.1.2 (BGP) (powerpc-bgp-linux)
	compiled by GNU C version 4.1.2 20070115 (prerelease) (SUSE Linux).
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/bin/as -m450fp2 -V -Qy -o /tmp/cc4QQYfx.o /tmp/cciSUIx4.s
GNU assembler version 2.17 (powerpc-bgp-linux) using BFD version 2.17
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../libexec/gcc/powerpc-bgp-linux/4.1.2/collect2 -V -Qy -static -m elf32ppclinux -o conftest /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib/crt1.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib/crti.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/crtbeginT.o -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib /tmp/cc4QQYfx.o -lgfortranbegin -lgfortran -lm --start-group -lgcc -lgcc_eh -lc --end-group /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/crtsavres.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/crtend.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib/crtn.o
GNU ld version 2.17
  Supported emulations:
   elf32ppclinux
   elf32ppc
   elf32ppcsim
configure:18428: result: -v
configure:18430: checking for Fortran libraries of mpif90
configure:18453: mpif90 -o conftest -v conftest.F90
mpif90 for 1.0.7
Reading specs from /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/specs
Target: powerpc-bgp-linux
Configured with: /bgsys/drivers/ppcfloor/toolchain/gnu/gcc-4.1.2/configure --prefix=/bgsys/drivers/ppcfloor/gnu-linux --target=powerpc-bgp-linux --enable-multilib --enable-shared --enable-secureplt --disable-libmudflap --disable-libspp --with-headers=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/include --with-libs=/bgsys/drivers/ppcfloor/toolchain/gnu/build-powerpc-bgp-linux/tempglibc-4.1.2-install/lib --with-long-double-128 --enable-threads=posix --enable-languages=c,c++,fortran
Thread model: posix
gcc version 4.1.2 (BGP)
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../libexec/gcc/powerpc-bgp-linux/4.1.2/cc1 -E -lang-fortran -traditional-cpp -D_LANGUAGE_FORTRAN -quiet -v -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/sys/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -iprefix /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/ -D__unix__ -D__gnu_linux__ -D__linux__ -Dunix -D__unix -Dlinux -D__linux -Asystem=linux -Asystem=unix -Asystem=posix conftest.F90 -mstrict-align -msecure-plt -fno-underscoring -o /tmp/cckOncT7.f95
ignoring nonexistent directory "/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/include"
ignoring duplicate directory "/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/include"
ignoring duplicate directory "/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/sys-include"
ignoring nonexistent directory "/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/include"
ignoring duplicate directory "/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include"
#include "..." search starts here:
#include <...> search starts here:
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/sys/include
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/include
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/sys-include
End of search list.
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../libexec/gcc/powerpc-bgp-linux/4.1.2/f951 /tmp/cckOncT7.f95 -ffree-form -mstrict-align -msecure-plt -quiet -dumpbase conftest.F90 -auxbase conftest -version -fno-underscoring -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/sys/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -I/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/comm/default/include -fpreprocessed -o /tmp/ccGafnH8.s
GNU F95 version 4.1.2 (BGP) (powerpc-bgp-linux)
	compiled by GNU C version 4.1.2 20070115 (prerelease) (SUSE Linux).
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/bin/as -m450fp2 -V -Qy -o /tmp/ccQs9Ii8.o /tmp/ccGafnH8.s
GNU assembler version 2.17 (powerpc-bgp-linux) using BFD version 2.17
 /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../libexec/gcc/powerpc-bgp-linux/4.1.2/collect2 -V -Qy -static -m elf32ppclinux -o conftest /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib/crt1.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib/crti.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/crtbeginT.o -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib /tmp/ccQs9Ii8.o -lgfortranbegin -lgfortran -lm --start-group -lgcc -lgcc_eh -lc --end-group /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/crtsavres.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/crtend.o /bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib/crtn.o
GNU ld version 2.17
  Supported emulations:
   elf32ppclinux
   elf32ppc
   elf32ppcsim
configure:18630: result:  -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -lgfortranbegin -lgfortran -lm
configure:18646: checking for dummy main to link with Fortran libraries
configure:18690: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c   -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -lgfortranbegin -lgfortran -lm >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:18697: $? = 0
configure:18785: result: none
configure:18824: checking for Fortran name-mangling scheme
configure:18843: mpif90 -c   conftest.F90 >&5
configure:18850: $? = 0
configure:18905: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c cfortran_test.o   -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -lgfortranbegin -lgfortran -lm >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:18912: $? = 0
configure:18994: mpicc -o conftest -O3 -qarch=450d -qtune=450   conftest.c cfortran_test.o   -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -lgfortranbegin -lgfortran -lm >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:19001: $? = 0
configure:19064: result: lower case, no underscore, no extra underscore
configure:19195: checking for python
configure:19211: found /usr/bin/python
configure:19222: result: python
configure:19237: checking for python-config
configure:19267: result: no
configure:19237: checking for python2.6-config
configure:19267: result: no
configure:19237: checking for python2.5-config
configure:19267: result: no
configure:19237: checking for python2.4-config
configure:19267: result: no
configure:19285: checking for Python CPPFLAGS
configure:19290: result: 
configure:19299: checking for bzr
configure:19329: result: no
configure:19346: checking for Python NumPy headers
configure:19365: mpicc -c -O3 -qarch=450d -qtune=450   conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
conftest.c:2:20: error: Python.h: No such file or directory
conftest.c:3:31: error: numpy/arrayobject.h: No such file or directory
configure:19372: $? = 1
configure: failed program was:
| 
| #include <Python.h>
| #include <numpy/arrayobject.h>
| 
| int main(int argc, char** argv)
| {
|     return 0;
| }
configure:19395: result: not found
configure:19411: checking numarray/arrayobject.h usability
configure:19428: mpicc -c -O3 -qarch=450d -qtune=450   conftest.c >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
conftest.c:88:34: error: numarray/arrayobject.h: No such file or directory
configure:19435: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.0.3"
| #define PACKAGE_STRING "ABINIT 6.0.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE "abinit"
| #define VERSION "6.0.3"
| #define ABINIT_VERSION "6.0.3"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "0"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20100504"
| #define ABINIT_VERSION_BASE "6.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CC_GNU 1
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ABORT 1
| #define SIZEOF_INT 4
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG 4
| #define SIZEOF_UNSIGNED_LONG 4
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_SIZE_T 4
| #define SIZEOF_PTRDIFF_T 4
| #define WORDS_BIGENDIAN 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define HAVE_FC_EXIT 1
| #define HAVE_FC_FLUSH 1
| #define HAVE_FC_GAMMA 1
| #define HAVE_FC_GET_ENVIRONMENT_VARIABLE 1
| #define HAVE_FC_NULL 1
| #define FC_FUNC(name,NAME) name
| #define FC_FUNC_(name,NAME) name
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #include <numarray/arrayobject.h>
configure:19449: result: no
configure:19453: checking numarray/arrayobject.h presence
configure:19468: mpicc -E   conftest.c
conftest.c:55:34: error: numarray/arrayobject.h: No such file or directory
configure:19475: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.0.3"
| #define PACKAGE_STRING "ABINIT 6.0.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE "abinit"
| #define VERSION "6.0.3"
| #define ABINIT_VERSION "6.0.3"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "0"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20100504"
| #define ABINIT_VERSION_BASE "6.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CC_GNU 1
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ABORT 1
| #define SIZEOF_INT 4
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG 4
| #define SIZEOF_UNSIGNED_LONG 4
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_SIZE_T 4
| #define SIZEOF_PTRDIFF_T 4
| #define WORDS_BIGENDIAN 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define HAVE_FC_EXIT 1
| #define HAVE_FC_FLUSH 1
| #define HAVE_FC_GAMMA 1
| #define HAVE_FC_GET_ENVIRONMENT_VARIABLE 1
| #define HAVE_FC_NULL 1
| #define FC_FUNC(name,NAME) name
| #define FC_FUNC_(name,NAME) name
| /* end confdefs.h.  */
| #include <numarray/arrayobject.h>
configure:19489: result: no
configure:19522: checking for numarray/arrayobject.h
configure:19529: result: no
configure:19807: checking for ar
configure:19823: found /usr/bin/ar
configure:19834: result: ar
configure:19895: checking for ranlib
configure:19911: found /usr/bin/ranlib
configure:19922: result: ranlib
configure:19992: checking for cpp
configure:20008: found /usr/bin/cpp
configure:20019: result: cpp
configure:20102: checking which cpp hints to apply
configure:20128: result: default/default/default
configure:20137: checking which cc hints to apply
configure:20190: result: gnu/default/default
configure:20201: checking which xpp hints to apply
configure:20205: result: none/none/none
configure:20214: checking which cxx hints to apply
configure:20267: result: gnu/default/default
configure:20278: checking which fpp hints to apply
configure:20282: result: none/none/none
configure:20291: checking which fc hints to apply
configure:20477: result: gnu/4.1/default
configure:20488: checking which ar hints to apply
configure:20507: result: none/none/none
configure:20588: checking debugging status
configure:20596: result: enabled (custom flags are allowed)
configure:20678: setting Fortran debug flags to '-g'
configure:20702: checking whether to activate debug mode in source files
configure:20714: result: no
configure:21049: checking optimization status
configure:21061: result: enabled (profile mode: standard)
configure:22115: optimization profile overriden by user-defined CFLAGS
configure:23091: optimization profile overriden by user-defined CXXFLAGS
configure:23100: checking which fc optimizations to apply
configure:24678: result: gnu/default/ibm_powerpc64
configure:24696: checking whether to apply per-directory optimizations
configure:24702: result: yes
configure:25783: checking for a 64-bit architecture
configure:25785: result: yes
configure:25787: checking whether to use 64-bit flags
configure:25789: result: no
configure:25791: checking for user-defined 64-bit flags
configure:25794: result: none
configure:26008: checking whether the C compiler supports MPI
configure:26252: mpicc -o conftest -O3 -qarch=450d -qtune=450                conftest.c        >&5
powerpc-bgp-linux-gcc: unrecognized option '-qarch=450d'
powerpc-bgp-linux-gcc: unrecognized option '-qtune=450'
configure:26259: $? = 0
configure:26481: result: yes
configure:26487: checking whether the C++ compiler supports MPI
configure:26728: mpicxx -o conftest -O3 -qarch=450d -qtune=450                conftest.cpp        >&5
powerpc-bgp-linux-g++: unrecognized option '-qarch=450d'
powerpc-bgp-linux-g++: unrecognized option '-qtune=450'
configure:26735: $? = 0
configure:26957: result: yes
configure:26963: checking whether the Fortran Compiler supports MPI
configure:27187: mpif90 -o conftest   -g        -static-libgfortran   conftest.F90        >&5
powerpc-bgp-linux-gfortran: unrecognized option '-static-libgfortran'
configure:27194: $? = 0
configure:27416: result: yes
configure:27425: checking whether MPI is usable
configure:27427: result: yes
configure:27469: WARNING: disabling MPI I/O is not recommended
configure:27474: checking whether to build MPI code
configure:27476: result: yes
configure:27487: checking whether to build MPI I/O code
configure:27489: result: no
configure:27499: checking whether to build MPI I/O untested features
configure:27501: result: no
configure:27511: checking whether to build MPI time tracing code
configure:27513: result: no
configure:27526: checking which level of MPI is supported by the Fortran compiler
configure:27752: mpif90 -o conftest   -g        -static-libgfortran   conftest.F90        >&5
powerpc-bgp-linux-gfortran: unrecognized option '-static-libgfortran'
configure:27759: $? = 0
configure:27982: result: 2
configure:28121: checking whether to use the CUDA Library
configure:28123: result: no
configure:28179: checking whether to use the FFTW library
configure:28181: result: no
configure:28208: checking whether to use the GNU Scientific Library
configure:28210: result: no
configure:28269: applying linear algebra tricks (type: abinit)
configure:28304: checking whether to build the LINALG library
configure:28306: result: yes
configure:28333: checking whether to activate ScaLAPACK support
configure:28335: result: no
configure:28367: checking whether to use the PAPI library
configure:28369: result: no
configure:28411: creating /CHPC/home/nmonama/.abinit/tarballs
configure:28416: using tarball repository /CHPC/home/nmonama/.abinit/tarballs
configure:28619: checking whether to enable the FOX plug-in
configure:28621: result: no
configure:28623: checking whether to build the FOX plug-in
configure:28625: result: no
configure:28744: checking for a source tarball of NETCDF
configure:28749: result: no
configure:28754: downloading NETCDF - this may take a while
configure:28758: checking availability of NETCDF from URL 1
configure:28764: result: no
configure:28768: checking availability of NETCDF from URL 2
configure:28774: result: no
configure:28789: WARNING: could not download NETCDF plug-in tarball
configure:28791: WARNING: support for NETCDF plug-in has been disabled
configure:28870: checking whether to enable the NETCDF plug-in
configure:28872: result: no
configure:28874: checking whether to build the NETCDF plug-in
configure:28876: result: no
configure:29003: checking for a source tarball of ETSF_IO
configure:29008: result: no
configure:29013: downloading ETSF_IO - this may take a while
configure:29017: checking availability of ETSF_IO from URL 1
configure:29023: result: no
configure:29038: WARNING: could not download ETSF_IO plug-in tarball
configure:29040: WARNING: support for ETSF_IO plug-in has been disabled
configure:29083: checking whether to enable the ETSF_IO plug-in
configure:29085: result: no
configure:29087: checking whether to build the ETSF_IO plug-in
configure:29089: result: no
configure:29296: checking whether to enable the ETSF_IO_TEST plug-in
configure:29298: result: no
configure:29300: checking whether to build the ETSF_IO_TEST plug-in
configure:29302: result: no
configure:29414: checking for a source tarball of LIBXC
configure:29419: result: no
configure:29424: downloading LIBXC - this may take a while
configure:29428: checking availability of LIBXC from URL 1
configure:29434: result: no
configure:29449: WARNING: could not download LIBXC plug-in tarball
configure:29451: WARNING: support for LIBXC plug-in has been disabled
configure:29479: checking whether to enable the LIBXC plug-in
configure:29481: result: no
configure:29483: checking whether to build the LIBXC plug-in
configure:29485: result: no
configure:29596: checking for a source tarball of BIGDFT
configure:29601: result: no
configure:29606: downloading BIGDFT - this may take a while
configure:29610: checking availability of BIGDFT from URL 1
configure:29616: result: no
configure:29620: checking availability of BIGDFT from URL 2
configure:29626: result: no
configure:29641: WARNING: could not download BIGDFT plug-in tarball
configure:29643: WARNING: support for BIGDFT plug-in has been disabled
configure:29674: checking whether to enable the BIGDFT plug-in
configure:29676: result: no
configure:29678: checking whether to build the BIGDFT plug-in
configure:29680: result: no
configure:29789: checking for a source tarball of WANNIER90
configure:29794: result: no
configure:29799: downloading WANNIER90 - this may take a while
configure:29803: checking availability of WANNIER90 from URL 1
configure:29809: result: no
configure:29813: checking availability of WANNIER90 from URL 2
configure:29819: result: no
configure:29834: WARNING: could not download WANNIER90 plug-in tarball
configure:29836: WARNING: support for WANNIER90 plug-in has been disabled
configure:29886: checking whether to enable the WANNIER90 plug-in
configure:29888: result: no
configure:29890: checking whether to build the WANNIER90 plug-in
configure:29892: result: no
configure:29976: checking whether to build Nightly code
configure:29978: result: no
configure:30527: checking whether to enable bindings
configure:30536: result: no
configure:30548: checking whether to use C clock for timings
configure:30565: result: no
configure:30569: checking whether to enable error handlers
configure:30578: result: no
configure:30597: checking whether to build exports
configure:30599: result: no
configure:30611: checking whether to enable GW double-precision calculations
configure:30620: result: no
configure:30632: checking whether to test abirules
configure:30634: result: 
configure:30646: checking whether to use macroave
configure:30655: result: yes
configure:30675: checking whether to read input from stdin
configure:30684: result: yes
configure:31048: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by ABINIT config.status 6.0.3, which was
generated by GNU Autoconf 2.63.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on chpcfen

config.status:1458: creating config.mk
config.status:1458: creating config.dump
config.status:1458: creating config.pc
config.status:1458: creating config.py
config.status:1458: creating config.sh
config.status:1458: creating config/wrappers/wrap-fc
config.status:1458: creating src/incs/Makefile
config.status:1458: creating src/mods/Makefile
config.status:1458: creating src/16_hideleave/m_build_info.F90
config.status:1458: creating src/98_main/abinis
config.status:1458: creating src/98_main/abinip
config.status:1458: creating tests/tests.env
config.status:1458: creating tests/tests-install.env
config.status:1458: creating Makefile
config.status:1458: creating src/Makefile
config.status:1458: creating src/01_gsl_ext/Makefile
config.status:1458: creating src/01_interfaces_ext/Makefile
config.status:1458: creating src/01_macroavnew_ext/Makefile
config.status:1458: creating src/10_defs/Makefile
config.status:1458: creating src/12_hide_mpi/Makefile
config.status:1458: creating src/14_hidewrite/Makefile
config.status:1458: creating src/16_hideleave/Makefile
config.status:1458: creating src/18_timing/Makefile
config.status:1458: creating src/27_toolbox_oop/Makefile
config.status:1458: creating src/28_numeric_noabirule/Makefile
config.status:1458: creating src/32_contract/Makefile
config.status:1458: creating src/32_util/Makefile
config.status:1458: creating src/42_geometry/Makefile
config.status:1458: creating src/42_nlstrain/Makefile
config.status:1458: creating src/42_parser/Makefile
config.status:1458: creating src/45_psp_parser/Makefile
config.status:1458: creating src/47_xml/Makefile
config.status:1458: creating src/49_gw_toolbox_oop/Makefile
config.status:1458: creating src/50_abitypes_defs/Makefile
config.status:1458: creating src/51_manage_cuda/Makefile
config.status:1458: creating src/51_manage_mpi/Makefile
config.status:1458: creating src/52_fft_mpi_noabirule/Makefile
config.status:1458: creating src/53_abiutil/Makefile
config.status:1458: creating src/53_ffts/Makefile
config.status:1458: creating src/53_spacepar/Makefile
config.status:1458: creating src/56_recipspace/Makefile
config.status:1458: creating src/56_xc/Makefile
config.status:1458: creating src/57_iovars/Makefile
config.status:1458: creating src/59_io_mpi/Makefile
config.status:1458: creating src/61_ionetcdf/Makefile
config.status:1458: creating src/62_cg_noabirule/Makefile
config.status:1458: creating src/62_iowfdenpot/Makefile
config.status:1458: creating src/62_occeig/Makefile
config.status:1458: creating src/62_poisson/Makefile
config.status:1458: creating src/62_wvl_wfs/Makefile
config.status:1458: creating src/63_bader/Makefile
config.status:1458: creating src/64_atompaw/Makefile
config.status:1458: creating src/65_nonlocal/Makefile
config.status:1458: creating src/65_psp/Makefile
config.status:1458: creating src/66_paw/Makefile
config.status:1458: creating src/66_wfs/Makefile
config.status:1458: creating src/67_common/Makefile
config.status:1458: creating src/68_dmft/Makefile
config.status:1458: creating src/68_gw/Makefile
config.status:1458: creating src/68_recursion/Makefile
config.status:1458: creating src/68_rsprc/Makefile
config.status:1458: creating src/69_bse/Makefile
config.status:1458: creating src/72_geomoptim/Makefile
config.status:1458: creating src/72_response/Makefile
config.status:1458: creating src/77_ddb/Makefile
config.status:1458: creating src/77_lwf/Makefile
config.status:1458: creating src/77_suscep/Makefile
config.status:1458: creating src/79_seqpar_mpi/Makefile
config.status:1458: creating src/83_cut3d/Makefile
config.status:1458: creating src/93_rdm/Makefile
config.status:1458: creating src/95_drive/Makefile
config.status:1458: creating src/98_main/Makefile
config.status:1458: creating src/libs/Makefile
config.status:1458: creating tests/Nightly/Makefile
config.status:1458: creating prereqs/Makefile
config.status:1458: creating prereqs/linalg/Makefile
config.status:1458: creating plugins/Makefile
config.status:1458: creating plugins/bigdft/Makefile
config.status:1458: creating plugins/etsf_io/Makefile
config.status:1458: creating plugins/etsf_io_test/Makefile
config.status:1458: creating plugins/fox/Makefile
config.status:1458: creating plugins/libxc/Makefile
config.status:1458: creating plugins/netcdf/Makefile
config.status:1458: creating plugins/wannier90/Makefile
config.status:1458: creating bindings/Makefile
config.status:1458: creating bindings/parser/Makefile
config.status:1458: creating doc/Makefile
config.status:1458: creating tests/Makefile
config.status:1458: creating config.h
config.status:1725: executing depfiles commands
config.status:1725: executing script-perms commands

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=powerpc64-unknown-linux-gnu
ac_cv_c_bigendian=yes
ac_cv_c_compiler_gnu=yes
ac_cv_c_const=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_ARFLAGS_EXTRA_set=
ac_cv_env_ARFLAGS_EXTRA_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_LDFLAGS_set=
ac_cv_env_CC_LDFLAGS_value=
ac_cv_env_CC_LIBS_set=
ac_cv_env_CC_LIBS_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=mpicc
ac_cv_env_CFLAGS_EXTRA_set=
ac_cv_env_CFLAGS_EXTRA_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O3 -qarch=450d -qtune=450'
ac_cv_env_CPPFLAGS_EXTRA_set=
ac_cv_env_CPPFLAGS_EXTRA_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_EXTRA_set=
ac_cv_env_CXXFLAGS_EXTRA_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value='-O3 -qarch=450d -qtune=450'
ac_cv_env_CXX_LDFLAGS_EXTRA_set=
ac_cv_env_CXX_LDFLAGS_EXTRA_value=
ac_cv_env_CXX_LDFLAGS_set=
ac_cv_env_CXX_LDFLAGS_value=
ac_cv_env_CXX_LIBS_set=
ac_cv_env_CXX_LIBS_value=
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=mpicxx
ac_cv_env_FCFLAGS_EXTRA_set=
ac_cv_env_FCFLAGS_EXTRA_value=
ac_cv_env_FCFLAGS_set=
ac_cv_env_FCFLAGS_value=
ac_cv_env_FC_LDFLAGS_EXTRA_set=
ac_cv_env_FC_LDFLAGS_EXTRA_value=
ac_cv_env_FC_LDFLAGS_set=
ac_cv_env_FC_LDFLAGS_value=
ac_cv_env_FC_LIBS_set=
ac_cv_env_FC_LIBS_value=
ac_cv_env_FC_set=set
ac_cv_env_FC_value=mpif90
ac_cv_env_FPPFLAGS_set=
ac_cv_env_FPPFLAGS_value=
ac_cv_env_FPP_set=
ac_cv_env_FPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MPI_RUNNER_set=
ac_cv_env_MPI_RUNNER_value=
ac_cv_env_XPPFLAGS_set=
ac_cv_env_XPPFLAGS_value=
ac_cv_env_XPP_set=
ac_cv_env_XPP_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_fc_compiler_gnu=yes
ac_cv_fc_dummy_main=none
ac_cv_fc_libs=' -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -lgfortranbegin -lgfortran -lm'
ac_cv_fc_mangling='lower case, no underscore, no extra underscore'
ac_cv_fc_srcext_F90=none
ac_cv_fortran_dummy_main=none
ac_cv_func_abort=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_malloc_h=yes
ac_cv_header_math_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_numarray_arrayobject_h=no
ac_cv_header_stdarg_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stddef_h=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdio_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_termios_h=yes
ac_cv_header_unistd_h=yes
ac_cv_host=powerpc64-unknown-linux-gnu
ac_cv_objext=o
ac_cv_path_BOURNE_SHELL=/bin/sh
ac_cv_path_DVI2PDF=/usr/bin/dvipdf
ac_cv_path_DVI2PS=/bin/false
ac_cv_path_EGREP='/usr/bin/grep -E'
ac_cv_path_GREP=/usr/bin/grep
ac_cv_path_LATEX=/bin/false
ac_cv_path_MV=/bin/mv
ac_cv_path_PERL=/usr/bin/perl
ac_cv_path_PS2PDF=/usr/bin/ps2pdf
ac_cv_path_RM=/bin/rm
ac_cv_path_SED=/usr/bin/sed
ac_cv_path_TAR=/bin/tar
ac_cv_path_WGET=/usr/bin/wget
ac_cv_path_abi_cc_path=/bgsys/drivers/ppcfloor/comm/bin/mpicc
ac_cv_path_abi_cxx_path=/bgsys/drivers/ppcfloor/comm/bin/mpicxx
ac_cv_path_abi_fc_path=/bgsys/drivers/ppcfloor/comm/bin/mpif90
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AR=ar
ac_cv_prog_AWK=gawk
ac_cv_prog_CPP='mpicc -E'
ac_cv_prog_MPI_RUNNER=mpirun
ac_cv_prog_PYTHON=python
ac_cv_prog_TRUE_CPP=cpp
ac_cv_prog_ac_ct_CC=mpicc
ac_cv_prog_ac_ct_RANLIB=ranlib
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_prog_fc_g=yes
ac_cv_prog_fc_v=-v
ac_cv_prog_make_make_set=yes
ac_cv_sizeof_double=8
ac_cv_sizeof_float=4
ac_cv_sizeof_int=4
ac_cv_sizeof_long=4
ac_cv_sizeof_long_long=8
ac_cv_sizeof_ptrdiff_t=4
ac_cv_sizeof_size_t=4
ac_cv_sizeof_unsigned_int=4
ac_cv_sizeof_unsigned_long=4
ac_cv_sizeof_unsigned_long_long=8
ac_cv_target=powerpc64-unknown-linux-gnu
ac_cv_type_size_t=yes
am_cv_CC_dependencies_compiler_type=gcc3
am_cv_CXX_dependencies_compiler_type=gcc3
ax_cv_f90_modext=mod

## ----------------- ##
## Output variables. ##
## ----------------- ##

ABINIT_BINARY_PACKAGE='abinit-6.0.3_powerpc64_linux_gnu4.1'
ABINIT_TARGET='powerpc64_linux_gnu4.1'
ABINIT_VERSION='6.0.3'
ABINIT_VERSION_BASE='6.0'
ABINIT_VERSION_BUILD='20100504'
ABINIT_VERSION_MAJOR='6'
ABINIT_VERSION_MICRO='3'
ABINIT_VERSION_MINOR='0'
ACLOCAL='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/missing --run aclocal-1.11'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/missing --run tar'
AR='ar'
ARFLAGS='      rc'
ARFLAGS_64BITS=''
ARFLAGS_CMD='rc'
ARFLAGS_DEBUG=' '
ARFLAGS_EXTRA=''
ARFLAGS_HINTS=''
ARFLAGS_OPT=''
AUTOCONF='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/missing --run autoconf'
AUTOHEADER='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/missing --run autoheader'
AUTOMAKE='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/missing --run automake-1.11'
AWK='gawk'
BAZAAR=''
BOURNE_SHELL='/bin/sh'
CC='mpicc'
CCDEPMODE='depmode=gcc3'
CC_LDFLAGS='     '
CC_LDFLAGS_64BITS=''
CC_LDFLAGS_CUDA=''
CC_LDFLAGS_DEBUG=' '
CC_LDFLAGS_EXTRA=''
CC_LDFLAGS_HINTS=''
CC_LDFLAGS_OPT=''
CC_LIBS='     '
CC_LIBS_64BITS=''
CC_LIBS_CUDA=''
CC_LIBS_DEBUG=' '
CC_LIBS_EXTRA=''
CC_LIBS_HINTS=''
CC_LIBS_OPT=''
CFGFLAGS_BIGDFT=''
CFGFLAGS_ETSF_IO=''
CFGFLAGS_ETSF_IO_TEST=''
CFGFLAGS_FOX=''
CFGFLAGS_LIBXC=''
CFGFLAGS_NETCDF=''
CFGFLAGS_WANNIER90=''
CFLAGS='-O3 -qarch=450d -qtune=450'
CFLAGS_64BITS=''
CFLAGS_BIGDFT='-O3 -qarch=450d -qtune=450'
CFLAGS_CUDA=''
CFLAGS_DEBUG=' '
CFLAGS_ETSF_IO='-O3 -qarch=450d -qtune=450'
CFLAGS_ETSF_IO_TEST='-O3 -qarch=450d -qtune=450'
CFLAGS_EXTRA=''
CFLAGS_FOX='-O3 -qarch=450d -qtune=450'
CFLAGS_HINTS=''
CFLAGS_LIBXC='-O3 -qarch=450d -qtune=450'
CFLAGS_LINALG='-O3 -qarch=450d -qtune=450'
CFLAGS_NETCDF='-O3 -qarch=450d -qtune=450'
CFLAGS_OPT=''
CFLAGS_WANNIER90='-O3 -qarch=450d -qtune=450'
CPP='mpicc -E'
CPPFLAGS='       '
CPPFLAGS_64BITS=''
CPPFLAGS_BIGDFT=''
CPPFLAGS_CUDA=''
CPPFLAGS_DEBUG=' '
CPPFLAGS_ETSF_IO=''
CPPFLAGS_ETSF_IO_TEST=''
CPPFLAGS_EXTRA=''
CPPFLAGS_FOX=''
CPPFLAGS_HINTS='  '
CPPFLAGS_LIBXC=''
CPPFLAGS_LINALG='       '
CPPFLAGS_NETCDF=''
CPPFLAGS_OPT=''
CPPFLAGS_WANNIER90=''
CXX='mpicxx'
CXXDEPMODE='depmode=gcc3'
CXXFLAGS='-O3 -qarch=450d -qtune=450'
CXXFLAGS_64BITS=''
CXXFLAGS_BIGDFT='-O3 -qarch=450d -qtune=450'
CXXFLAGS_CUDA=''
CXXFLAGS_DEBUG=' '
CXXFLAGS_ETSF_IO='-O3 -qarch=450d -qtune=450'
CXXFLAGS_ETSF_IO_TEST='-O3 -qarch=450d -qtune=450'
CXXFLAGS_EXTRA=''
CXXFLAGS_FOX='-O3 -qarch=450d -qtune=450'
CXXFLAGS_HINTS=''
CXXFLAGS_LIBXC='-O3 -qarch=450d -qtune=450'
CXXFLAGS_LINALG='-O3 -qarch=450d -qtune=450'
CXXFLAGS_NETCDF='-O3 -qarch=450d -qtune=450'
CXXFLAGS_OPT=''
CXXFLAGS_WANNIER90='-O3 -qarch=450d -qtune=450'
CXX_LDFLAGS='     '
CXX_LDFLAGS_64BITS=''
CXX_LDFLAGS_CUDA=''
CXX_LDFLAGS_DEBUG=' '
CXX_LDFLAGS_EXTRA=''
CXX_LDFLAGS_HINTS=''
CXX_LDFLAGS_OPT=''
CXX_LIBS='     '
CXX_LIBS_64BITS=''
CXX_LIBS_CUDA=''
CXX_LIBS_DEBUG=' '
CXX_LIBS_EXTRA=''
CXX_LIBS_HINTS=''
CXX_LIBS_OPT=''
CYGPATH_W='echo'
DEFS='-DHAVE_CONFIG_H'
DEPDIR='.deps'
DO_BUILD_01_GSL_EXT_FALSE=''
DO_BUILD_01_GSL_EXT_TRUE='#'
DO_BUILD_01_MACROAVNEW_EXT_FALSE='#'
DO_BUILD_01_MACROAVNEW_EXT_TRUE=''
DO_BUILD_51_MANAGE_CUDA_FALSE=''
DO_BUILD_51_MANAGE_CUDA_TRUE='#'
DO_BUILD_BIGDFT_FALSE=''
DO_BUILD_BIGDFT_TRUE='#'
DO_BUILD_BINDINGS_FALSE=''
DO_BUILD_BINDINGS_TRUE='#'
DO_BUILD_CCLOCK_FALSE=''
DO_BUILD_CCLOCK_TRUE='#'
DO_BUILD_ERROR_HANDLERS_FALSE=''
DO_BUILD_ERROR_HANDLERS_TRUE='#'
DO_BUILD_ETSF_IO_FALSE=''
DO_BUILD_ETSF_IO_TEST_FALSE=''
DO_BUILD_ETSF_IO_TEST_TRUE='#'
DO_BUILD_ETSF_IO_TRUE='#'
DO_BUILD_EXPORTS_FALSE=''
DO_BUILD_EXPORTS_TRUE='#'
DO_BUILD_FOX_FALSE=''
DO_BUILD_FOX_TRUE='#'
DO_BUILD_LIBXC_FALSE=''
DO_BUILD_LIBXC_TRUE='#'
DO_BUILD_LINALG_FALSE='#'
DO_BUILD_LINALG_TRUE=''
DO_BUILD_MACROAVE_FALSE='#'
DO_BUILD_MACROAVE_TRUE=''
DO_BUILD_NETCDF_FALSE=''
DO_BUILD_NETCDF_TRUE='#'
DO_BUILD_NIGHTLY_FALSE=''
DO_BUILD_NIGHTLY_TRUE='#'
DO_BUILD_WANNIER90_FALSE=''
DO_BUILD_WANNIER90_TRUE='#'
DO_ENABLE_BIGDFT_FALSE=''
DO_ENABLE_BIGDFT_TRUE='#'
DO_ENABLE_ETSF_IO_FALSE=''
DO_ENABLE_ETSF_IO_TEST_FALSE=''
DO_ENABLE_ETSF_IO_TEST_TRUE='#'
DO_ENABLE_ETSF_IO_TRUE='#'
DO_ENABLE_FOX_FALSE=''
DO_ENABLE_FOX_TRUE='#'
DO_ENABLE_LIBXC_FALSE=''
DO_ENABLE_LIBXC_TRUE='#'
DO_ENABLE_MPI_FALSE='#'
DO_ENABLE_MPI_TRUE=''
DO_ENABLE_NETCDF_FALSE=''
DO_ENABLE_NETCDF_TRUE='#'
DO_ENABLE_WANNIER90_FALSE=''
DO_ENABLE_WANNIER90_TRUE='#'
DO_TEST_ABIRULES_FALSE=''
DO_TEST_ABIRULES_TRUE='#'
DO_TEST_GWDP_FALSE=''
DO_TEST_GWDP_TRUE='#'
DVI2PDF='/usr/bin/dvipdf'
DVI2PS='/bin/false'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/usr/bin/grep -E'
EXEEXT=''
F77='mpif90'
FC='mpif90'
FCFLAGS='  -g   '
FCFLAGS_64BITS=''
FCFLAGS_BIGDFT='  -g    -O2 -mpowerpc64'
FCFLAGS_DEBUG='-g '
FCFLAGS_ETSF_IO='  -g    -O2 -mpowerpc64'
FCFLAGS_ETSF_IO_TEST='  -g    -O2 -mpowerpc64'
FCFLAGS_EXTRA=''
FCFLAGS_F90=''
FCFLAGS_FIXEDFORM='-ffixed-form'
FCFLAGS_FOX='  -g    -O2 -mpowerpc64'
FCFLAGS_FREEFORM='-ffree-form'
FCFLAGS_HINTS=''
FCFLAGS_LIBXC='  -g    -O2 -mpowerpc64'
FCFLAGS_LINALG='  -g    -O2 -mpowerpc64'
FCFLAGS_MODDIR='-J$(abinit_moddir) -I$(abinit_moddir)'
FCFLAGS_NETCDF='  -g    -O2 -mpowerpc64'
FCFLAGS_OPT='-O2 -mpowerpc64'
FCFLAGS_WANNIER90='  -g    -O2 -mpowerpc64'
FCLIBS=' -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2 -L/bgsys/drivers/V1R2M0_200_2008-080513P/ppc/gnu-linux/bin/../lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -L/bgsys/drivers/ppcfloor/gnu-linux/lib/gcc/powerpc-bgp-linux/4.1.2/../../../../powerpc-bgp-linux/lib -lgfortranbegin -lgfortran -lm'
FCLIBS_ETSF_IO=''
FCLIBS_ETSF_IO_TEST=''
FCLIBS_FOX=''
FCLIBS_NETCDF=''
FCLIBS_WANNIER90=''
FC_LDFLAGS='    -static-libgfortran '
FC_LDFLAGS_64BITS=''
FC_LDFLAGS_DEBUG=' '
FC_LDFLAGS_EXTRA=''
FC_LDFLAGS_HINTS='-static-libgfortran'
FC_LDFLAGS_OPT=''
FC_LIBS='     '
FC_LIBS_64BITS=''
FC_LIBS_DEBUG=' '
FC_LIBS_EXTRA=''
FC_LIBS_HINTS=''
FC_LIBS_OPT=''
FC_NOWRAP='mpif90'
FFLAGS='  -g   '
FPP=''
FPPFLAGS=''
GREP='/usr/bin/grep'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LATEX='/bin/false'
LDFLAGS='    -static-libgfortran '
LIBOBJS=''
LIBS='      '
LN_S='ln -s'
LTLIBOBJS=''
LTXFLAGS=''
MAKEINFO='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/missing --run makeinfo'
MARKDOWN='/usr/bin/perl /CHPC/home/nmonama/abinit-6.0.3/build/../util/developers/markdown.pl'
MDFLAGS=''
MKDIR_P='/bin/mkdir -p'
MODEXT='mod'
MPI_RUNNER='mpirun'
MV='/bin/mv'
NVCC=''
NVCC_CFLAGS=''
NVCC_CPPFLAGS=''
NVCC_LDFLAGS=''
NVCC_LIBS=''
OBJEXT='o'
PACKAGE='abinit'
PACKAGE_BUGREPORT='https://bugs.launchpad.net/abinit/'
PACKAGE_NAME='ABINIT'
PACKAGE_STRING='ABINIT 6.0.3'
PACKAGE_TARNAME='abinit'
PACKAGE_VERSION='6.0.3'
PATH_SEPARATOR=':'
PDFFLAGS=''
PERL='/usr/bin/perl'
PS2PDF='/usr/bin/ps2pdf'
PYTHON='python'
PYTHON_CONFIG=''
PYTHON_CPPFLAGS=''
RANLIB='ranlib'
RM='/bin/rm'
SED='/usr/bin/sed'
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
TAR='/bin/tar'
TRUE_CPP='cpp'
TRUE_CPPFLAGS=' -P -std=c89'
VERSION='6.0.3'
WGET='/usr/bin/wget'
XPP=''
XPPFLAGS=''
abi_ac_version='026300'
abi_am_version='011100'
abi_cc_path='/bgsys/drivers/ppcfloor/comm/bin/mpicc'
abi_cc_vendor='gnu'
abi_cc_version=''
abi_cpp_path=''
abi_cpu_64bits='yes'
abi_cpu_bits='64'
abi_cpu_model='powerpc64'
abi_cpu_spec='ibm_powerpc64'
abi_cpu_vendor='ibm'
abi_cxx_path='/bgsys/drivers/ppcfloor/comm/bin/mpicxx'
abi_cxx_vendor='gnu'
abi_cxx_version='4.1'
abi_fc_path='/bgsys/drivers/ppcfloor/comm/bin/mpif90'
abi_fc_vendor='gnu'
abi_fc_version='4.1'
abi_fc_wrap='no'
abi_fpp_path=''
abi_lt_version='020204'
abi_m4_version='010413'
abi_mpi_runner_works=''
abi_sys_spec='linux-powerpc64'
abinit_bindir='/CHPC/home/nmonama/abinit-6.0.3/abinit/6.0/bin'
abinit_builddir='/CHPC/home/nmonama/abinit-6.0.3/build'
abinit_chkdir='/CHPC/home/nmonama/abinit-6.0.3/abinit/6.0/tests'
abinit_datdir='/CHPC/home/nmonama/abinit-6.0.3/abinit'
abinit_docdir='/CHPC/home/nmonama/abinit-6.0.3/abinit/6.0/doc'
abinit_incdir='/CHPC/home/nmonama/abinit-6.0.3/abinit/6.0/include'
abinit_libdir='/CHPC/home/nmonama/abinit-6.0.3/abinit/6.0/lib'
abinit_mandir='/CHPC/home/nmonama/abinit-6.0.3/abinit/man'
abinit_moddir='/CHPC/home/nmonama/abinit-6.0.3/build/src/mods'
abinit_prefix='/CHPC/home/nmonama/abinit-6.0.3'
abinit_rundir='/CHPC/home/nmonama/abinit-6.0.3/abinit/bin'
abinit_srcdir='/CHPC/home/nmonama/abinit-6.0.3/build/..'
abinit_tardir='/CHPC/home/nmonama/.abinit/tarballs'
abinit_wwwdir='/CHPC/home/nmonama/abinit-6.0.3/abinit/6.0/www'
ac_ct_CC='mpicc'
ac_ct_CXX=''
ac_ct_FC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE='#'
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE='#'
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=' -I$(srcdir)'
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
bigdft_pkg_name='bigdft-1.2.0.2'
bigdft_pkg_string='BigDFT library 1.2.0.2 (upstream release)'
bindir='${exec_prefix}/bin'
build='powerpc64-unknown-linux-gnu'
build_alias=''
build_bigdft='no'
build_cpu='powerpc64'
build_etsf_io='no'
build_etsf_io_test='no'
build_fox='no'
build_libxc='no'
build_linalg='yes'
build_netcdf='no'
build_os='linux-gnu'
build_vendor='unknown'
build_wannier90='no'
bzr_branch=''
bzr_clean=''
bzr_revno=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
enable_64bit_flags='no'
enable_all_plugins=''
enable_bigdft='no'
enable_bindings='no'
enable_cclock='no'
enable_config_file='yes'
enable_cuda='no'
enable_debug='yes'
enable_env_file='no'
enable_error_handlers='no'
enable_etsf_io='no'
enable_etsf_io_test='no'
enable_exports='no'
enable_fc_wrapper='no'
enable_fftw='no'
enable_fftw_threads='no'
enable_fox='no'
enable_gsl='no'
enable_gw_dpc='no'
enable_hints='yes'
enable_libxc='no'
enable_macroave='yes'
enable_mpi='yes'
enable_mpi_io='no'
enable_mpi_io_test='no'
enable_mpi_trace='no'
enable_netcdf='no'
enable_nightly='no'
enable_optim='standard'
enable_papi='no'
enable_scalapack='no'
enable_shared=''
enable_static=''
enable_stdin='yes'
enable_wannier90='no'
etsf_io_pkg_name='etsf_io-1.0.2'
etsf_io_pkg_string='ETSF I/O library 1.0.2 (upstream release)'
etsf_io_test_pkg_name='etsf_io_test-0.1.1'
etsf_io_test_pkg_string='ETSF I/O Test library 0.1.1 (upstream release)'
exec_prefix='${prefix}'
fcflags_opt_01_gsl_ext='-O2 -mpowerpc64'
fcflags_opt_01_interfaces_ext='-O2 -mpowerpc64'
fcflags_opt_01_macroavnew_ext='-O2 -mpowerpc64'
fcflags_opt_10_defs='-O2 -mpowerpc64'
fcflags_opt_12_hide_mpi='-O2 -mpowerpc64'
fcflags_opt_14_hidewrite='-O2 -mpowerpc64'
fcflags_opt_16_hideleave='-O2 -mpowerpc64'
fcflags_opt_18_timing='-O2 -mpowerpc64'
fcflags_opt_27_toolbox_oop='-O2 -mpowerpc64'
fcflags_opt_28_numeric_noabirule='-O2 -mpowerpc64'
fcflags_opt_32_contract='-O2 -mpowerpc64'
fcflags_opt_32_util='-O2 -mpowerpc64'
fcflags_opt_42_geometry='-O2 -mpowerpc64'
fcflags_opt_42_nlstrain='-O2 -mpowerpc64'
fcflags_opt_42_parser='-O2 -mpowerpc64'
fcflags_opt_45_psp_parser='-O2 -mpowerpc64'
fcflags_opt_47_xml='-O2 -mpowerpc64'
fcflags_opt_49_gw_toolbox_oop='-O2 -mpowerpc64'
fcflags_opt_50_abitypes_defs='-O2 -mpowerpc64'
fcflags_opt_51_manage_cuda='-O2 -mpowerpc64'
fcflags_opt_51_manage_mpi='-O2 -mpowerpc64'
fcflags_opt_52_fft_mpi_noabirule='-O2 -mpowerpc64'
fcflags_opt_53_abiutil='-O2 -mpowerpc64'
fcflags_opt_53_ffts='-O2 -mpowerpc64'
fcflags_opt_53_spacepar='-O2 -mpowerpc64'
fcflags_opt_56_recipspace='-O2 -mpowerpc64'
fcflags_opt_56_xc='-O2 -mpowerpc64'
fcflags_opt_57_iovars='-O2 -mpowerpc64'
fcflags_opt_59_io_mpi='-O2 -mpowerpc64'
fcflags_opt_61_ionetcdf='-O2 -mpowerpc64'
fcflags_opt_62_cg_noabirule='-O2 -mpowerpc64'
fcflags_opt_62_iowfdenpot='-O2 -mpowerpc64'
fcflags_opt_62_occeig='-O2 -mpowerpc64'
fcflags_opt_62_poisson='-O2 -mpowerpc64'
fcflags_opt_62_wvl_wfs='-O2 -mpowerpc64'
fcflags_opt_63_bader='-O2 -mpowerpc64'
fcflags_opt_64_atompaw='-O2 -mpowerpc64'
fcflags_opt_65_nonlocal='-O2 -mpowerpc64'
fcflags_opt_65_psp='-O2 -mpowerpc64'
fcflags_opt_66_paw='-O2 -mpowerpc64'
fcflags_opt_66_wfs='-O2 -mpowerpc64'
fcflags_opt_67_common='-O2 -mpowerpc64'
fcflags_opt_68_dmft='-O2 -mpowerpc64'
fcflags_opt_68_gw='-O2 -mpowerpc64'
fcflags_opt_68_recursion='-O2 -mpowerpc64'
fcflags_opt_68_rsprc='-O2 -mpowerpc64'
fcflags_opt_69_bse='-O2 -mpowerpc64'
fcflags_opt_72_geomoptim='-O2 -mpowerpc64'
fcflags_opt_72_response='-O2 -mpowerpc64'
fcflags_opt_77_ddb='-O2 -mpowerpc64'
fcflags_opt_77_lwf='-O2 -mpowerpc64'
fcflags_opt_77_suscep='-O2 -mpowerpc64'
fcflags_opt_79_seqpar_mpi='-O2 -mpowerpc64'
fcflags_opt_83_cut3d='-O2 -mpowerpc64'
fcflags_opt_93_rdm='-O2 -mpowerpc64'
fcflags_opt_95_drive='-O2 -mpowerpc64'
fcflags_opt_98_main='-O2 -mpowerpc64'
fcflags_opt_bigdft='-O2 -mpowerpc64'
fcflags_opt_etsf_io='-O2 -mpowerpc64'
fcflags_opt_etsf_io_test='-O2 -mpowerpc64'
fcflags_opt_fox='-O2 -mpowerpc64'
fcflags_opt_libxc='-O2 -mpowerpc64'
fcflags_opt_linalg='-O2 -mpowerpc64'
fcflags_opt_netcdf='-O2 -mpowerpc64'
fcflags_opt_wannier90='-O2 -mpowerpc64'
fox_pkg_name='FoX-4.0.3'
fox_pkg_string='FoX Fortran XML library 4.0.3 (upstream release)'
host='powerpc64-unknown-linux-gnu'
host_alias=''
host_cpu='powerpc64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /CHPC/home/nmonama/abinit-6.0.3/config/gnu/install-sh'
lib_bigdft_incs=''
lib_bigdft_libs=''
lib_cuda_incs=''
lib_cuda_libs=''
lib_etsf_io_incs=''
lib_etsf_io_libs=''
lib_etsf_io_test_incs=''
lib_etsf_io_test_libs=''
lib_fft_incs=''
lib_fft_libs=''
lib_fox_incs=''
lib_fox_libs=''
lib_gsl_incs=''
lib_gsl_libs=''
lib_libxc_incs=''
lib_libxc_libs=''
lib_linalg_incs=''
lib_linalg_libs='-L$(abinit_builddir)/prereqs/linalg -llapack -lblas'
lib_mpi_incs=''
lib_mpi_libs=''
lib_netcdf_incs=''
lib_netcdf_libs=''
lib_papi_incs=''
lib_papi_libs=''
lib_wannier90_incs=''
lib_wannier90_libs=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
libxc_pkg_name='libxc-svn-r6071-fixed'
libxc_pkg_string='LibXC library SVN revision 6071 (fixed for Abinit by YP)'
linalg_pkg_name='lapack-abinit_6.0'
linalg_pkg_string='The 3.2.1 Lapack library (dlamch.f hacked by XG)'
linalg_supported_types='abinit acml asl atlas cxml essl external mkl mlib sgimath sunperf'
linalg_tricks_bypass='no'
linalg_type='abinit'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
netcdf_pkg_name='netcdf-3.6.3'
netcdf_pkg_string='NetCDF library 3.6.3 (upstream release)'
nightly_timeout=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/CHPC/home/nmonama/abinit-6.0.3'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
src_01_gsl_ext_incs='-I$(top_builddir)/src/01_gsl_ext -I$(top_srcdir)/src/01_gsl_ext'
src_01_interfaces_ext_incs='-I$(top_builddir)/src/01_interfaces_ext -I$(top_srcdir)/src/01_interfaces_ext'
src_01_macroavnew_ext_incs='-I$(top_builddir)/src/01_macroavnew_ext -I$(top_srcdir)/src/01_macroavnew_ext'
src_10_defs_incs='-I$(top_builddir)/src/10_defs -I$(top_srcdir)/src/10_defs'
src_12_hide_mpi_incs='-I$(top_builddir)/src/12_hide_mpi -I$(top_srcdir)/src/12_hide_mpi'
src_14_hidewrite_incs='-I$(top_builddir)/src/14_hidewrite -I$(top_srcdir)/src/14_hidewrite'
src_16_hideleave_incs='-I$(top_builddir)/src/16_hideleave -I$(top_srcdir)/src/16_hideleave'
src_18_timing_incs='-I$(top_builddir)/src/18_timing -I$(top_srcdir)/src/18_timing'
src_27_toolbox_oop_incs='-I$(top_builddir)/src/27_toolbox_oop -I$(top_srcdir)/src/27_toolbox_oop'
src_28_numeric_noabirule_incs='-I$(top_builddir)/src/28_numeric_noabirule -I$(top_srcdir)/src/28_numeric_noabirule'
src_32_contract_incs='-I$(top_builddir)/src/32_contract -I$(top_srcdir)/src/32_contract'
src_32_util_incs='-I$(top_builddir)/src/32_util -I$(top_srcdir)/src/32_util'
src_42_geometry_incs='-I$(top_builddir)/src/42_geometry -I$(top_srcdir)/src/42_geometry'
src_42_nlstrain_incs='-I$(top_builddir)/src/42_nlstrain -I$(top_srcdir)/src/42_nlstrain'
src_42_parser_incs='-I$(top_builddir)/src/42_parser -I$(top_srcdir)/src/42_parser'
src_45_psp_parser_incs='-I$(top_builddir)/src/45_psp_parser -I$(top_srcdir)/src/45_psp_parser'
src_47_xml_incs='-I$(top_builddir)/src/47_xml -I$(top_srcdir)/src/47_xml'
src_49_gw_toolbox_oop_incs='-I$(top_builddir)/src/49_gw_toolbox_oop -I$(top_srcdir)/src/49_gw_toolbox_oop'
src_50_abitypes_defs_incs='-I$(top_builddir)/src/50_abitypes_defs -I$(top_srcdir)/src/50_abitypes_defs'
src_51_manage_cuda_incs='-I$(top_builddir)/src/51_manage_cuda -I$(top_srcdir)/src/51_manage_cuda'
src_51_manage_mpi_incs='-I$(top_builddir)/src/51_manage_mpi -I$(top_srcdir)/src/51_manage_mpi'
src_52_fft_mpi_noabirule_incs='-I$(top_builddir)/src/52_fft_mpi_noabirule -I$(top_srcdir)/src/52_fft_mpi_noabirule'
src_53_abiutil_incs='-I$(top_builddir)/src/53_abiutil -I$(top_srcdir)/src/53_abiutil'
src_53_ffts_incs='-I$(top_builddir)/src/53_ffts -I$(top_srcdir)/src/53_ffts'
src_53_spacepar_incs='-I$(top_builddir)/src/53_spacepar -I$(top_srcdir)/src/53_spacepar'
src_56_recipspace_incs='-I$(top_builddir)/src/56_recipspace -I$(top_srcdir)/src/56_recipspace'
src_56_xc_incs='-I$(top_builddir)/src/56_xc -I$(top_srcdir)/src/56_xc'
src_57_iovars_incs='-I$(top_builddir)/src/57_iovars -I$(top_srcdir)/src/57_iovars'
src_59_io_mpi_incs='-I$(top_builddir)/src/59_io_mpi -I$(top_srcdir)/src/59_io_mpi'
src_61_ionetcdf_incs='-I$(top_builddir)/src/61_ionetcdf -I$(top_srcdir)/src/61_ionetcdf'
src_62_cg_noabirule_incs='-I$(top_builddir)/src/62_cg_noabirule -I$(top_srcdir)/src/62_cg_noabirule'
src_62_iowfdenpot_incs='-I$(top_builddir)/src/62_iowfdenpot -I$(top_srcdir)/src/62_iowfdenpot'
src_62_occeig_incs='-I$(top_builddir)/src/62_occeig -I$(top_srcdir)/src/62_occeig'
src_62_poisson_incs='-I$(top_builddir)/src/62_poisson -I$(top_srcdir)/src/62_poisson'
src_62_wvl_wfs_incs='-I$(top_builddir)/src/62_wvl_wfs -I$(top_srcdir)/src/62_wvl_wfs'
src_63_bader_incs='-I$(top_builddir)/src/63_bader -I$(top_srcdir)/src/63_bader'
src_64_atompaw_incs='-I$(top_builddir)/src/64_atompaw -I$(top_srcdir)/src/64_atompaw'
src_65_nonlocal_incs='-I$(top_builddir)/src/65_nonlocal -I$(top_srcdir)/src/65_nonlocal'
src_65_psp_incs='-I$(top_builddir)/src/65_psp -I$(top_srcdir)/src/65_psp'
src_66_paw_incs='-I$(top_builddir)/src/66_paw -I$(top_srcdir)/src/66_paw'
src_66_wfs_incs='-I$(top_builddir)/src/66_wfs -I$(top_srcdir)/src/66_wfs'
src_67_common_incs='-I$(top_builddir)/src/67_common -I$(top_srcdir)/src/67_common'
src_68_dmft_incs='-I$(top_builddir)/src/68_dmft -I$(top_srcdir)/src/68_dmft'
src_68_gw_incs='-I$(top_builddir)/src/68_gw -I$(top_srcdir)/src/68_gw'
src_68_recursion_incs='-I$(top_builddir)/src/68_recursion -I$(top_srcdir)/src/68_recursion'
src_68_rsprc_incs='-I$(top_builddir)/src/68_rsprc -I$(top_srcdir)/src/68_rsprc'
src_69_bse_incs='-I$(top_builddir)/src/69_bse -I$(top_srcdir)/src/69_bse'
src_72_geomoptim_incs='-I$(top_builddir)/src/72_geomoptim -I$(top_srcdir)/src/72_geomoptim'
src_72_response_incs='-I$(top_builddir)/src/72_response -I$(top_srcdir)/src/72_response'
src_77_ddb_incs='-I$(top_builddir)/src/77_ddb -I$(top_srcdir)/src/77_ddb'
src_77_lwf_incs='-I$(top_builddir)/src/77_lwf -I$(top_srcdir)/src/77_lwf'
src_77_suscep_incs='-I$(top_builddir)/src/77_suscep -I$(top_srcdir)/src/77_suscep'
src_79_seqpar_mpi_incs='-I$(top_builddir)/src/79_seqpar_mpi -I$(top_srcdir)/src/79_seqpar_mpi'
src_83_cut3d_incs='-I$(top_builddir)/src/83_cut3d -I$(top_srcdir)/src/83_cut3d'
src_93_rdm_incs='-I$(top_builddir)/src/93_rdm -I$(top_srcdir)/src/93_rdm'
src_95_drive_incs='-I$(top_builddir)/src/95_drive -I$(top_srcdir)/src/95_drive'
src_incs_incs='-I$(top_builddir)/src/incs -I$(top_srcdir)/src/incs'
src_mods_incs='-I$(top_builddir)/src/mods -I$(top_srcdir)/src/mods'
sysconfdir='${prefix}/etc'
target='powerpc64-unknown-linux-gnu'
target_alias=''
target_cpu='powerpc64'
target_os='linux-gnu'
target_vendor='unknown'
wannier90_pkg_name='wannier90-1.1'
wannier90_pkg_string='Wannier90 program 1.1 (upstream release)'
with_64bit_flags=''
with_ar_dbgflags=''
with_ar_optflags=''
with_bigdft_includes=''
with_bigdft_libs=''
with_cc_dbgflags=''
with_cc_ld_dbgflags=''
with_cc_ld_dbglibs=''
with_cc_ld_optflags=''
with_cc_ld_optlibs=''
with_cc_optflags=''
with_config_file=''
with_cpp_dbgflags=''
with_cpp_optflags=''
with_cuda_includes=''
with_cuda_libs=''
with_cxx_dbgflags=''
with_cxx_ld_dbgflags=''
with_cxx_ld_dbglibs=''
with_cxx_ld_optflags=''
with_cxx_ld_optlibs=''
with_cxx_optflags=''
with_etsf_io_includes=''
with_etsf_io_libs=''
with_etsf_io_test_includes=''
with_etsf_io_test_libs=''
with_fc_dbgflags=''
with_fc_ld_dbgflags=''
with_fc_ld_dbglibs=''
with_fc_ld_optflags=''
with_fc_ld_optlibs=''
with_fc_optflags=''
with_fc_vendor=''
with_fc_version=''
with_fftw_includes=''
with_fftw_libs=''
with_fox_includes=''
with_fox_libs=''
with_gnu_ld=''
with_gsl_includes=''
with_gsl_libs=''
with_libxc_includes=''
with_libxc_libs=''
with_linalg_includes=''
with_linalg_libs=''
with_linalg_type=''
with_mpi_includes=''
with_mpi_level=''
with_mpi_libs=''
with_mpi_prefix=''
with_mpi_runner=''
with_netcdf_includes=''
with_netcdf_libs=''
with_papi_includes=''
with_papi_libs=''
with_plugins_prefix=''
with_plugins_tardir=''
with_scalapack_includes=''
with_scalapack_libs=''
with_timeout='0'
with_wannier90=''
with_wannier90_includes=''
with_wannier90_libs=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

#define PACKAGE_NAME "ABINIT"
#define PACKAGE_TARNAME "abinit"
#define PACKAGE_VERSION "6.0.3"
#define PACKAGE_STRING "ABINIT 6.0.3"
#define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
#define PACKAGE "abinit"
#define VERSION "6.0.3"
#define ABINIT_VERSION "6.0.3"
#define ABINIT_VERSION_MAJOR "6"
#define ABINIT_VERSION_MINOR "0"
#define ABINIT_VERSION_MICRO "3"
#define ABINIT_VERSION_BUILD "20100504"
#define ABINIT_VERSION_BASE "6.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define CC_GNU 1
#define HAVE_STDDEF_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDIO_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MATH_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_ABORT 1
#define SIZEOF_INT 4
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG 4
#define SIZEOF_UNSIGNED_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_SIZE_T 4
#define SIZEOF_PTRDIFF_T 4
#define WORDS_BIGENDIAN 1
#define CXX_GNU 1
#define FC_GNU 1
#define HAVE_FORTRAN2003 1
#define HAVE_FC_EXIT 1
#define HAVE_FC_FLUSH 1
#define HAVE_FC_GAMMA 1
#define HAVE_FC_GET_ENVIRONMENT_VARIABLE 1
#define HAVE_FC_NULL 1
#define FC_FUNC(name,NAME) name
#define FC_FUNC_(name,NAME) name
#define ABINIT_TARGET "powerpc64_linux_gnu4.1"
#define HAVE_MPI 1
#define HAVE_MPI2 1
#define USE_MACROAVE 1

configure: exit 0
