This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libxc configure 1.1.0.1, which was
generated by GNU Autoconf 2.65.  Invocation command line was

  $ ./configure --prefix=/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports --bindir=/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/bin --libdir=/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/lib --program-suffix=-abinit --enable-fortran --enable-static --disable-shared

## --------- ##
## Platform. ##
## --------- ##

hostname = vrh014376
uname -m = x86_64
uname -r = 2.6.18-308.24.1.el5
uname -s = Linux
uname -v = #1 SMP Tue Dec 4 17:43:34 EST 2012

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/lib64/openmpi/1.4-gcc/bin
PATH: /usr/lib64/qt-3.3/bin
PATH: /usr/kerberos/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/X11R6/bin
PATH: /home/bouyer/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2541: checking for a BSD-compatible install
configure:2609: result: /usr/bin/install -c
configure:2620: checking whether build environment is sane
configure:2670: result: yes
configure:2811: checking for a thread-safe mkdir -p
configure:2850: result: /bin/mkdir -p
configure:2863: checking for gawk
configure:2879: found /usr/bin/gawk
configure:2890: result: gawk
configure:2901: checking whether make sets $(MAKE)
configure:2923: result: yes
configure:3071: checking build system type
configure:3085: result: x86_64-unknown-linux-gnu
configure:3105: checking host system type
configure:3118: result: x86_64-unknown-linux-gnu
configure:3150: checking for style of include used by make
configure:3178: result: GNU
configure:3248: checking for gcc
configure:3275: result: gcc
configure:3504: checking for C compiler version
configure:3513: gcc --version >&5
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3524: $? = 0
configure:3513: gcc -v >&5
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
configure:3524: $? = 0
configure:3513: gcc -V >&5
gcc: '-V' option must have argument
configure:3524: $? = 1
configure:3513: gcc -qversion >&5
gcc: unrecognized option '-qversion'
gcc: no input files
configure:3524: $? = 1
configure:3544: checking whether the C compiler works
configure:3566: gcc -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:3570: $? = 0
configure:3619: result: yes
configure:3622: checking for C compiler default output file name
configure:3624: result: a.out
configure:3630: checking for suffix of executables
configure:3637: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:3641: $? = 0
configure:3663: result: 
configure:3685: checking whether we are cross compiling
configure:3693: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:3697: $? = 0
configure:3704: ./conftest
configure:3708: $? = 0
configure:3723: result: no
configure:3728: checking for suffix of object files
configure:3750: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:3754: $? = 0
configure:3775: result: o
configure:3779: checking whether we are using the GNU C compiler
configure:3798: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:3798: $? = 0
configure:3807: result: yes
configure:3816: checking whether gcc accepts -g
configure:3836: gcc -c -g  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:3836: $? = 0
configure:3877: result: yes
configure:3894: checking for gcc option to accept ISO C89
configure:3958: gcc  -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:3958: $? = 0
configure:3971: result: none needed
configure:3993: checking dependency style of gcc
configure:4103: result: gcc3
configure:4118: checking for a sed that does not truncate output
configure:4182: result: /bin/sed
configure:4200: checking for grep that handles long lines and -e
configure:4258: result: /bin/grep
configure:4263: checking for egrep
configure:4325: result: /bin/grep -E
configure:4330: checking for fgrep
configure:4392: result: /bin/grep -F
configure:4427: checking for ld used by gcc
configure:4494: result: /usr/bin/ld
configure:4501: checking if the linker (/usr/bin/ld) is GNU ld
configure:4516: result: yes
configure:4528: checking for BSD- or MS-compatible name lister (nm)
configure:4577: result: /usr/bin/nm -B
configure:4695: checking the name lister (/usr/bin/nm -B) interface
configure:4702: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:4705: /usr/bin/nm -B "conftest.o"
configure:4708: output
0000000000000000 B some_variable
configure:4715: result: BSD nm
configure:4718: checking whether ln -s works
configure:4722: result: yes
configure:4730: checking the maximum length of command line arguments
configure:4850: result: 98304
configure:4867: checking whether the shell understands some XSI constructs
configure:4877: result: yes
configure:4881: checking whether the shell understands "+="
configure:4887: result: yes
configure:4922: checking for /usr/bin/ld option to reload object files
configure:4929: result: -r
configure:4998: checking for objdump
configure:5014: found /usr/bin/objdump
configure:5025: result: objdump
configure:5057: checking how to recognize dependent libraries
configure:5253: result: pass_all
configure:5313: checking for ar
configure:5340: result: ar
configure:5418: checking for strip
configure:5434: found /usr/bin/strip
configure:5445: result: strip
configure:5517: checking for ranlib
configure:5544: result: ranlib
configure:5634: checking command to parse /usr/bin/nm -B output from gcc object
configure:5752: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:5755: $? = 0
configure:5759: /usr/bin/nm -B conftest.o \| sed -n -e 's/^.*[	 ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[	 ][	 ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' \> conftest.nm
configure:5762: $? = 0
configure:5816: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c conftstm.o >&5
configure:5819: $? = 0
configure:5857: result: ok
configure:5953: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:5956: $? = 0
configure:6666: checking how to run the C preprocessor
configure:6736: result: gcc -E
configure:6756: gcc -E  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c
configure:6756: $? = 0
configure:6770: gcc -E  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c
conftest.c:11:28: error: ac_nonexistent.h: No such file or directory
configure:6770: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libxc"
| #define PACKAGE_TARNAME "libxc"
| #define PACKAGE_VERSION "1.1.0.1"
| #define PACKAGE_STRING "libxc 1.1.0.1"
| #define PACKAGE_BUGREPORT "octopus-users@tddft.org"
| #define PACKAGE_URL ""
| #define PACKAGE "libxc"
| #define VERSION "1.1.0.1"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:6799: checking for ANSI C header files
configure:6819: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6819: $? = 0
configure:6892: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:6892: $? = 0
configure:6892: ./conftest
configure:6892: $? = 0
configure:6903: result: yes
configure:6916: checking for sys/types.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for sys/stat.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for stdlib.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for string.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for memory.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for strings.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for inttypes.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for stdint.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6916: checking for unistd.h
configure:6916: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6916: $? = 0
configure:6916: result: yes
configure:6931: checking for dlfcn.h
configure:6931: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:6931: $? = 0
configure:6931: result: yes
configure:7085: checking for objdir
configure:7100: result: .libs
configure:7396: checking if gcc supports -fno-rtti -fno-exceptions
configure:7414: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include -fno-rtti -fno-exceptions conftest.c >&5
cc1: warning: command line option "-fno-rtti" is valid for C++/ObjC++ but not for C
configure:7418: $? = 0
configure:7431: result: no
configure:7451: checking for gcc option to produce PIC
configure:7723: result: -fPIC -DPIC
configure:7735: checking if gcc PIC flag -fPIC -DPIC works
configure:7753: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include -fPIC -DPIC -DPIC conftest.c >&5
configure:7757: $? = 0
configure:7770: result: yes
configure:7794: checking if gcc static flag -static works
configure:7822: result: yes
configure:7837: checking if gcc supports -c -o file.o
configure:7858: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include -o out/conftest2.o conftest.c >&5
configure:7862: $? = 0
configure:7884: result: yes
configure:7892: checking if gcc supports -c -o file.o
configure:7939: result: yes
configure:7972: checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries
configure:8963: result: yes
configure:9202: checking dynamic linker characteristics
configure:9635: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   -Wl,-rpath -Wl,/foo conftest.c  >&5
configure:9635: $? = 0
configure:9865: result: GNU/Linux ld.so
configure:9967: checking how to hardcode library paths into programs
configure:9992: result: immediate
configure:10512: checking whether stripping libraries is possible
configure:10517: result: yes
configure:10552: checking if libtool supports shared libraries
configure:10554: result: yes
configure:10557: checking whether to build shared libraries
configure:10578: result: no
configure:10581: checking whether to build static libraries
configure:10585: result: yes
configure:10670: checking for gcc
configure:10697: result: gcc
configure:10926: checking for C compiler version
configure:10935: gcc --version >&5
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:10946: $? = 0
configure:10935: gcc -v >&5
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
configure:10946: $? = 0
configure:10935: gcc -V >&5
gcc: '-V' option must have argument
configure:10946: $? = 1
configure:10935: gcc -qversion >&5
gcc: unrecognized option '-qversion'
gcc: no input files
configure:10946: $? = 1
configure:10950: checking whether we are using the GNU C compiler
configure:10978: result: yes
configure:10987: checking whether gcc accepts -g
configure:11048: result: yes
configure:11065: checking for gcc option to accept ISO C89
configure:11142: result: none needed
configure:11164: checking dependency style of gcc
configure:11274: result: gcc3
configure:11291: checking whether gcc and cc understand -c and -o together
configure:11322: gcc -c conftest.c -o conftest2.o >&5
configure:11326: $? = 0
configure:11332: gcc -c conftest.c -o conftest2.o >&5
configure:11336: $? = 0
configure:11347: cc -c conftest.c >&5
configure:11351: $? = 0
configure:11359: cc -c conftest.c -o conftest2.o >&5
configure:11363: $? = 0
configure:11369: cc -c conftest.c -o conftest2.o >&5
configure:11373: $? = 0
configure:11391: result: yes
configure:11416: checking for inline
configure:11432: gcc -c -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include conftest.c >&5
configure:11432: $? = 0
configure:11440: result: inline
configure:11460: checking for ANSI C header files
configure:11564: result: yes
configure:11574: checking for working alloca.h
configure:11591: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:11591: $? = 0
configure:11599: result: yes
configure:11607: checking for alloca
configure:11644: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:11644: $? = 0
configure:11652: result: yes
configure:11768: checking size of void*
configure:11773: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c  >&5
configure:11773: $? = 0
configure:11773: ./conftest
configure:11773: $? = 0
configure:11788: result: 8
configure:11800: checking for sqrtf in -lm
configure:11825: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c -lm   >&5
conftest.c:34: warning: conflicting types for built-in function 'sqrtf'
configure:11825: $? = 0
configure:11834: result: yes
configure:11842: checking for cbrt in -lm
configure:11867: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c -lm   >&5
conftest.c:35: warning: conflicting types for built-in function 'cbrt'
configure:11867: $? = 0
configure:11876: result: yes
configure:11884: checking for cbrtf in -lm
configure:11909: gcc -o conftest -g -O2  -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   conftest.c -lm   >&5
conftest.c:36: warning: conflicting types for built-in function 'cbrtf'
configure:11909: $? = 0
configure:11918: result: yes
configure:12056: checking for Fortran compiler version
configure:12065: mpif90 --version >&5
GNU Fortran (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)
Copyright (C) 2007 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

configure:12076: $? = 0
configure:12065: mpif90 -v >&5
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
configure:12076: $? = 0
configure:12065: mpif90 -V >&5
gfortran: '-V' option must have argument
configure:12076: $? = 1
configure:12065: mpif90 -qversion >&5
gfortran: unrecognized option '-qversion'
gfortran: no input files
configure:12076: $? = 1
configure:12085: checking whether we are using the GNU Fortran compiler
configure:12098: mpif90 -c -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include  conftest.F >&5
conftest.F:0: error: bad value (native) for -march= switch
conftest.F:0: error: bad value (native) for -mtune= switch
configure:12098: $? = 1
configure: failed program was:
|       program main
| #ifndef __GNUC__
|        choke me
| #endif
| 
|       end
configure:12107: result: no
configure:12113: checking whether mpif90 accepts -g
configure:12124: mpif90 -c -g  conftest.F90 >&5
configure:12124: $? = 0
configure:12132: result: yes
configure:12263: checking for Fortran compiler version
configure:12272: mpif90 --version >&5
GNU Fortran (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)
Copyright (C) 2007 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

configure:12283: $? = 0
configure:12272: mpif90 -v >&5
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
configure:12283: $? = 0
configure:12272: mpif90 -V >&5
gfortran: '-V' option must have argument
configure:12283: $? = 1
configure:12272: mpif90 -qversion >&5
gfortran: unrecognized option '-qversion'
gfortran: no input files
configure:12283: $? = 1
configure:12292: checking whether we are using the GNU Fortran compiler
configure:12314: result: no
configure:12320: checking whether mpif90 accepts -g
configure:12339: result: yes
configure:12472: checking if libtool supports shared libraries
configure:12474: result: yes
configure:12477: checking whether to build shared libraries
configure:12497: result: no
configure:12500: checking whether to build static libraries
configure:12504: result: yes
configure:12530: mpif90 -c -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include  conftest.F90 >&5
conftest.F90:0: error: bad value (native) for -march= switch
conftest.F90:0: error: bad value (native) for -mtune= switch
configure:12533: $? = 1
configure:12661: checking for mpif90 option to produce PIC
configure:12933: result: 
configure:12998: checking if mpif90 static flag  works
configure:13026: result: no
configure:13038: checking if mpif90 supports -c -o file.o
configure:13059: mpif90 -c -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include -o out/conftest2.o  conftest.F90 >&5
conftest.F90:0: error: bad value (native) for -march= switch
conftest.F90:0: error: bad value (native) for -mtune= switch
configure:13063: $? = 1
configure:13085: result: no
configure:13090: checking if mpif90 supports -c -o file.o
configure:13137: result: no
configure:13167: checking whether the mpif90 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries
configure:14145: result: yes
configure:14282: checking dynamic linker characteristics
configure:14657: mpif90 -o conftest -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include   -rpath /foo  conftest.F90  >&5
gfortran: /foo: No such file or directory
gfortran: unrecognized option '-rpath'
conftest.F90:0: error: bad value (native) for -march= switch
conftest.F90:0: error: bad value (native) for -mtune= switch
configure:14657: $? = 1
configure: failed program was:
|       program main
| 
|       end
configure:14887: result: GNU/Linux ld.so
configure:14938: checking how to hardcode library paths into programs
configure:14963: result: immediate
configure:15008: checking for Fortran flag to compile .f90 files
configure:15024: mpif90 -c -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include  conftest.f90 >&5
conftest.f90:0: error: bad value (native) for -march= switch
conftest.f90:0: error: bad value (native) for -mtune= switch
configure:15024: $? = 1
configure: failed program was:
|       program main
| 
|       end
configure:15024: mpif90 -c -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include -qsuffix=f=f90 conftest.f90 >&5
gfortran: unrecognized option '-qsuffix=f=f90'
conftest.f90:0: error: bad value (native) for -march= switch
conftest.f90:0: error: bad value (native) for -mtune= switch
configure:15024: $? = 1
configure: failed program was:
|       program main
| 
|       end
configure:15024: mpif90 -c -ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include -Tf conftest.f90 >&5
conftest.f90:0: error: bad value (native) for -march= switch
conftest.f90:0: error: bad value (native) for -mtune= switch
configure:15024: $? = 1
configure: failed program was:
|       program main
| 
|       end
configure:15033: result: unknown
configure:15036: error: Fortran could not compile .f90 files

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_build_fortran=yes
ac_cv_c_compiler_gnu=yes
ac_cv_c_inline=inline
ac_cv_env_CC_set=set
ac_cv_env_CC_value=gcc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-g -O2'
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value=' -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include'
ac_cv_env_CPP_set=set
ac_cv_env_CPP_value='gcc -E'
ac_cv_env_FCCPP_set=set
ac_cv_env_FCCPP_value='cpp -P -std=c99'
ac_cv_env_FCFLAGS_set=set
ac_cv_env_FCFLAGS_value='-ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include'
ac_cv_env_FC_set=set
ac_cv_env_FC_value=mpif90
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value=' '
ac_cv_env_LIBS_set=set
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_fc_compiler_gnu=no
ac_cv_fc_srcext_f90=unknown
ac_cv_func_alloca_works=yes
ac_cv_header_dlfcn_h=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_unistd_h=yes
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_lib_m_cbrt=yes
ac_cv_lib_m_cbrtf=yes
ac_cv_lib_m_sqrtf=yes
ac_cv_objext=o
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_FGREP='/bin/grep -F'
ac_cv_path_GREP=/bin/grep
ac_cv_path_SED=/bin/sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_CPP='gcc -E'
ac_cv_prog_ac_ct_AR=ar
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_OBJDUMP=objdump
ac_cv_prog_ac_ct_RANLIB=ranlib
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_cc_gcc_c_o=yes
ac_cv_prog_fc_g=yes
ac_cv_prog_make_make_set=yes
ac_cv_sizeof_voidp=8
ac_cv_working_alloca_h=yes
am_cv_CC_dependencies_compiler_type=gcc3
lt_cv_deplibs_check_method=pass_all
lt_cv_file_magic_cmd='$MAGIC_CMD'
lt_cv_file_magic_test_file=
lt_cv_ld_reload_flag=-r
lt_cv_nm_interface='BSD nm'
lt_cv_objdir=.libs
lt_cv_path_LD=/usr/bin/ld
lt_cv_path_NM='/usr/bin/nm -B'
lt_cv_prog_compiler_c_o=yes
lt_cv_prog_compiler_c_o_FC=no
lt_cv_prog_compiler_pic_works=yes
lt_cv_prog_compiler_rtti_exceptions=no
lt_cv_prog_compiler_static_works=yes
lt_cv_prog_compiler_static_works_FC=no
lt_cv_prog_gnu_ld=yes
lt_cv_sys_global_symbol_pipe='sed -n -e '\''s/^.*[	 ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[	 ][	 ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p'\'''
lt_cv_sys_global_symbol_to_c_name_address='sed -n -e '\''s/^: \([^ ]*\) $/  {\"\1\", (void *) 0},/p'\'' -e '\''s/^[ABCDGIRSTW]* \([^ ]*\) \([^ ]*\)$/  {"\2", (void *) \&\2},/p'\'''
lt_cv_sys_global_symbol_to_c_name_address_lib_prefix='sed -n -e '\''s/^: \([^ ]*\) $/  {\"\1\", (void *) 0},/p'\'' -e '\''s/^[ABCDGIRSTW]* \([^ ]*\) \(lib[^ ]*\)$/  {"\2", (void *) \&\2},/p'\'' -e '\''s/^[ABCDGIRSTW]* \([^ ]*\) \([^ ]*\)$/  {"lib\2", (void *) \&\2},/p'\'''
lt_cv_sys_global_symbol_to_cdecl='sed -n -e '\''s/^T .* \(.*\)$/extern int \1();/p'\'' -e '\''s/^[ABCDGIRSTW]* .* \(.*\)$/extern char \1;/p'\'''
lt_cv_sys_max_cmd_len=98304

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/missing --run aclocal-1.11'
ALLOCA=''
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/missing --run tar'
AR='ar'
AUTOCONF='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/missing --run autoconf'
AUTOHEADER='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/missing --run autoheader'
AUTOMAKE='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/missing --run automake-1.11'
AWK='gawk'
CC='gcc'
CCDEPMODE='depmode=gcc3'
CFLAGS='-g -O2'
COMPILE_FORTRAN_FALSE=''
COMPILE_FORTRAN_TRUE=''
COMPILE_SINGLE_FALSE=''
COMPILE_SINGLE_TRUE=''
CPP='gcc -E'
CPPFLAGS=' -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include'
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
ENABLE_FORTRAN_FALSE='#'
ENABLE_FORTRAN_TRUE=''
EXEEXT=''
F90_ACCEPTS_LINE_NUMBERS=''
F90_MOD_UPPERCASE_FALSE=''
F90_MOD_UPPERCASE_TRUE=''
FC='mpif90'
FCCPP='cpp -P -std=c99'
FCFLAGS='-ffree-form -g    -O2 -mtune=native -march=native -mfpmath=sse -g -O2 -I/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/include'
FCFLAGS_f90=''
FCLIBS=''
FGREP='/bin/grep -F'
GREP='/bin/grep'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD='/usr/bin/ld -m elf_x86_64'
LDFLAGS=' '
LIBOBJS=''
LIBS=''
LIBTOOL='$(SHELL) $(top_builddir)/libtool'
LIPO=''
LN_S='ln -s'
LONG_LINES=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/missing --run makeinfo'
MKDIR_P='/bin/mkdir -p'
NM='/usr/bin/nm -B'
NMEDIT=''
OBJDUMP='objdump'
OBJEXT='o'
OTOOL64=''
OTOOL=''
PACKAGE='libxc'
PACKAGE_BUGREPORT='octopus-users@tddft.org'
PACKAGE_NAME='libxc'
PACKAGE_STRING='libxc 1.1.0.1'
PACKAGE_TARNAME='libxc'
PACKAGE_URL=''
PACKAGE_VERSION='1.1.0.1'
PATH_SEPARATOR=':'
RANLIB='ranlib'
SED='/bin/sed'
SET_MAKE=''
SHELL='/bin/sh'
STRIP='strip'
VERSION='1.1.0.1'
ac_ct_CC='gcc'
ac_ct_DUMPBIN=''
ac_ct_FC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
ax_cv_f90_modext=''
bindir='/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/sources/libxc-1.1.0.1/install-sh'
libdir='/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
lt_ECHO='echo'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/media/DATA/bouyer/abinit/abinit-7.0.5/fallbacks/exports'
program_transform_name='s&$$&-abinit&'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "libxc"
#define PACKAGE_TARNAME "libxc"
#define PACKAGE_VERSION "1.1.0.1"
#define PACKAGE_STRING "libxc 1.1.0.1"
#define PACKAGE_BUGREPORT "octopus-users@tddft.org"
#define PACKAGE_URL ""
#define PACKAGE "libxc"
#define VERSION "1.1.0.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define SIZEOF_VOIDP 8
#define HAVE_SQRTF 1
#define HAVE_CBRT 1
#define HAVE_CBRTF 1
#define HAVE_FORTRAN 1

configure: exit 1
