#ndtset 5
autoparal 1

ecut 55
ecutsm 0.5

kptrlen 35

kptopt 1

ionmov 2
dilatmx 1.3
optcell 2 
strfact 100
tolmxf 1e-5
ntime 50
strprecon 0.1
toldff 1e-6
nstep 100

prtden 0
prtwf 0
prteig 0
prtgsr 0
#****************************************************************************************
#*                    Generated by cif2cell 1.2.10 2016-09-16 11:21                     *
#*    T. Bjorkman, Comp. Phys. Commun. 182, 1183-1186 (2011). Please cite generously.   *
#*                                                                                      *
#*                  Data obtained from ICSD. Reference number : 150371                  *
#*                           B (P O4)   (Boron phosphate(V))                            *
#* Achary, S.N. and Tyagi, A.K., Journal of Solid State Chemistry 177, 3918-3926 (2004) *
#****************************************************************************************
# Structural parameters
acell    8.1813938346E+00  8.1813938346E+00  8.5152583196E+00  

rprim    1.0000000000E+00  0.0000000000E+00  0.0000000000E+00
                       0.0000000000E+00  1.0000000000E+00  0.0000000000E+00
                       4.8039610353E-01  4.8039610353E-01  7.3378414226E-01 
       
natom    6  
ntypat   3  
typat    1 2 2 2 2 3  
znucl    15 8 5  
xred     0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
                       9.2411477311E-03  1.3233175081E-01  2.5393350923E-01
                       7.3682534304E-01  6.1373473996E-01  2.5393350923E-01
                       3.8626526004E-01  9.9075885227E-01  7.4606649077E-01
                       8.6766824919E-01  2.6317465696E-01  7.4606649077E-01
                       7.5000000000E-01  2.5000000000E-01  5.0000000000E-01 
      
