This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by ABINIT configure 6.5.0, which was
generated by GNU Autoconf 2.65.  Invocation command line was

  $ ../configure --with-config-file=/home/jzwanzig/code/build/6.5.0.ac

## --------- ##
## Platform. ##
## --------- ##

hostname = jwzpc17
uname -m = x86_64
uname -r = 2.6.32-24-generic
uname -s = Linux
uname -v = #42-Ubuntu SMP Fri Aug 20 14:21:58 UTC 2010

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/jzwanzig/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /home/jzwanzig/bin
PATH: /home/jzwanzig/ddt/bin
PATH: /usr/local/openmpi/1.4.2/gcc/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:3528: checking build system type
configure:3542: result: x86_64-unknown-linux-gnu
configure:3562: checking host system type
configure:3575: result: x86_64-unknown-linux-gnu
configure:3595: checking target system type
configure:3608: result: x86_64-unknown-linux-gnu
configure:3650: checking for a BSD-compatible install
configure:3718: result: /usr/bin/install -c
configure:3729: checking whether build environment is sane
configure:3779: result: yes
configure:3920: checking for a thread-safe mkdir -p
configure:3959: result: /bin/mkdir -p
configure:3972: checking for gawk
configure:3988: found /usr/bin/gawk
configure:3999: result: gawk
configure:4010: checking whether make sets $(MAKE)
configure:4032: result: yes
configure:4438: checking whether make sets $(MAKE)
configure:4460: result: yes
configure:4470: checking whether ln -s works
configure:4474: result: yes
configure:4481: checking for a sed that does not truncate output
configure:4545: result: /bin/sed
configure:4554: checking for gawk
configure:4581: result: gawk
configure:4592: checking for grep that handles long lines and -e
configure:4650: result: /bin/grep
configure:4657: checking for egrep
configure:4719: result: /bin/grep -E
configure:5756: reading options from /home/jzwanzig/code/build/6.5.0.ac
configure:7097: ABINIT version 6.5.0
configure:7107: M4 010413 - Autoconf 026500 - Automake 011101 - Libtool 020206
configure:7118: reporting user interface changes:
configure:7121:  * new option --enable-bse-unpacked is available
configure:7124:  * new option --enable-dft is available
configure:7127:  * --enable-etsf-io-test removed
configure:7133:  * new option --enable-fast-check is available
configure:7136:  * --enable-fftw renamed --enable-fft
configure:7142:  * --enable-fftw-threads removed
configure:7148:  * --enable-cuda renamed --enable-gpu
configure:7154:  * new option --enable-gw-cutoff is available
configure:7157:  * new option --enable-gw-optimal is available
configure:7160:  * new option --enable-gw-wrapper is available
configure:7163:  * new option --enable-linalg is available
configure:7166:  * new option --enable-maintainer-checks is available
configure:7169:  * --enable-gsl renamed --enable-math
configure:7175:  * new option --enable-smp is available
configure:7178:  * --enable-nightly renamed --enable-test-timeout
configure:7184:  * --enable-papi renamed --enable-timer
configure:7190:  * new option --enable-trio is available
configure:7193:  * new option --enable-vdwxc is available
configure:7196:  * --with-64bit-flags removed
configure:7202:  * --with-ar-dbgflags removed
configure:7208:  * --with-ar-optflags removed
configure:7214:  * --with-cc-dbgflags removed
configure:7220:  * --with-cc-ld-dbgflags removed
configure:7226:  * --with-cc-ld-dbglibs removed
configure:7232:  * --with-cc-ld-optflags removed
configure:7238:  * --with-cc-ld-optlibs removed
configure:7244:  * --with-cc-optflags removed
configure:7250:  * --with-cpp-dbgflags removed
configure:7256:  * --with-cpp-optflags removed
configure:7262:  * --with-cxx-dbgflags removed
configure:7268:  * --with-cxx-ld-dbgflags removed
configure:7274:  * --with-cxx-ld-dbglibs removed
configure:7280:  * --with-cxx-ld-optflags removed
configure:7286:  * --with-cxx-ld-optlibs removed
configure:7292:  * --with-cxx-optflags removed
configure:7298:  * new option --with-dft-flavor is available
configure:7301:  * new option --with-dft-includes is available
configure:7304:  * new option --with-dft-libs is available
configure:7307:  * --with-etsf-io-test-includes removed
configure:7313:  * --with-etsf-io-test-libs removed
configure:7319:  * --with-fc-dbgflags removed
configure:7325:  * --with-fc-ld-dbgflags removed
configure:7331:  * --with-fc-ld-dbglibs removed
configure:7337:  * --with-fc-ld-optflags removed
configure:7343:  * --with-fc-ld-optlibs removed
configure:7349:  * --with-fc-optflags removed
configure:7355:  * new option --with-fft-flavor is available
configure:7358:  * --with-fftw-includes renamed --with-fft-includes
configure:7364:  * --with-fftw-libs renamed --with-fft-libs
configure:7370:  * new option --with-gpu-cflags is available
configure:7373:  * new option --with-gpu-cppflags is available
configure:7376:  * new option --with-gpu-flavor is available
configure:7379:  * --with-cuda-includes renamed --with-gpu-includes
configure:7385:  * new option --with-gpu-ldflags is available
configure:7388:  * --with-cuda-libs renamed --with-gpu-libs
configure:7394:  * new option --with-gpu-prefix is available
configure:7397:  * --with-linalg-type renamed --with-linalg-flavor
configure:7403:  * new option --with-math-flavor is available
configure:7406:  * --with-gsl-includes renamed --with-math-includes
configure:7412:  * --with-gsl-libs renamed --with-math-libs
configure:7418:  * --with-mpi-runner removed
configure:7424:  * --with-scalapack-includes removed
configure:7430:  * --with-scalapack-libs removed
configure:7436:  * --with-timeout renamed --with-test-timeout
configure:7442:  * new option --with-timer-flavor is available
configure:7445:  * --with-papi-includes renamed --with-timer-includes
configure:7451:  * --with-papi-libs renamed --with-timer-libs
configure:7457:  * new option --with-trio-flavor is available
configure:7460:  * new option --with-trio-includes is available
configure:7463:  * new option --with-trio-libs is available
configure:7500: checking consistency of external prerequisite options
configure:7533:  |---> all OK
configure:7536: 
configure:7545: checking consistency of plug-in options
configure:7558:  |---> all OK
configure:7561: 
configure:7570: checking consistency of experimental options
configure:7585:  |---> all OK
configure:7588: 
configure:7606: parsing command-line options
configure:8880: Initializing MPI support
configure:8884: looking for MPI in /usr/local/openmpi/1.4.2/gcc
configure:8917: checking for a MPI C compiler
configure:8927: result: /usr/local/openmpi/1.4.2/gcc/bin/mpicc
configure:8931: checking for a MPI C++ compiler
configure:8944: result: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx
configure:8948: checking for a MPI Fortran compiler
configure:8958: result: /usr/local/openmpi/1.4.2/gcc/bin/mpif90
configure:8962: checking for a MPI runner
configure:8978: result: /usr/local/openmpi/1.4.2/gcc/bin/mpirun
configure:9335: GPU support disabled from command-line
configure:9373: checking for sh
configure:9391: found /bin/sh
configure:9404: result: /bin/sh
configure:9414: checking for mv
configure:9432: found /bin/mv
configure:9445: result: /bin/mv
configure:9455: checking for perl
configure:9473: found /usr/bin/perl
configure:9486: result: /usr/bin/perl
configure:9496: checking for rm
configure:9514: found /bin/rm
configure:9527: result: /bin/rm
configure:9540: checking for dvips
configure:9570: result: no
configure:9582: checking for dvipdf
configure:9598: found /usr/bin/dvipdf
configure:9609: result: dvipdf
configure:9624: checking for latex
configure:9654: result: no
configure:9666: checking for markdown
configure:9696: result: no
configure:9708: checking for md5sum
configure:9724: found /usr/bin/md5sum
configure:9735: result: md5sum
configure:9750: checking for patch
configure:9766: found /usr/bin/patch
configure:9777: result: patch
configure:9792: checking for ps2pdf
configure:9808: found /usr/bin/ps2pdf
configure:9819: result: ps2pdf
configure:9834: checking for tar
configure:9850: found /bin/tar
configure:9861: result: tar
configure:9876: checking for wget
configure:9892: found /usr/bin/wget
configure:9903: result: wget
configure:9917: using internal version of MarkDown
configure:10254: checking for gcc
configure:10281: result: /usr/local/openmpi/1.4.2/gcc/bin/mpicc
configure:10510: checking for C compiler version
configure:10519: /usr/local/openmpi/1.4.2/gcc/bin/mpicc --version >&5
gcc (Ubuntu 4.4.3-4ubuntu5) 4.4.3
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:10530: $? = 0
configure:10519: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -v >&5
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-4ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 
configure:10530: $? = 0
configure:10519: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -V >&5
gcc: '-V' option must have argument
configure:10530: $? = 1
configure:10519: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -qversion >&5
gcc: unrecognized option '-qversion'
gcc: no input files
configure:10530: $? = 1
configure:10550: checking whether the C compiler works
configure:10572: /usr/local/openmpi/1.4.2/gcc/bin/mpicc    conftest.c  >&5
configure:10576: $? = 0
configure:10625: result: yes
configure:10628: checking for C compiler default output file name
configure:10630: result: a.out
configure:10636: checking for suffix of executables
configure:10643: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c  >&5
configure:10647: $? = 0
configure:10669: result: 
configure:10691: checking whether we are cross compiling
configure:10699: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c  >&5
configure:10703: $? = 0
configure:10710: ./conftest
configure:10714: $? = 0
configure:10729: result: no
configure:10734: checking for suffix of object files
configure:10756: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:10760: $? = 0
configure:10781: result: o
configure:10785: checking whether we are using the GNU C compiler
configure:10804: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:10804: $? = 0
configure:10813: result: yes
configure:10822: checking whether /usr/local/openmpi/1.4.2/gcc/bin/mpicc accepts -g
configure:10842: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c -g  conftest.c >&5
configure:10842: $? = 0
configure:10883: result: yes
configure:10900: checking for /usr/local/openmpi/1.4.2/gcc/bin/mpicc option to accept ISO C89
configure:10964: /usr/local/openmpi/1.4.2/gcc/bin/mpicc  -c -g -O2  conftest.c >&5
configure:10964: $? = 0
configure:10977: result: none needed
configure:11008: checking for style of include used by make
configure:11036: result: GNU
configure:11061: checking dependency style of /usr/local/openmpi/1.4.2/gcc/bin/mpicc
configure:11171: result: gcc3
configure:11243: checking how to run the C preprocessor
configure:11274: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E  conftest.c
configure:11274: $? = 0
configure:11288: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E  conftest.c
conftest.c:18:28: error: ac_nonexistent.h: No such file or directory
configure:11288: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:11313: result: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E
configure:11333: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E  conftest.c
configure:11333: $? = 0
configure:11347: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E  conftest.c
conftest.c:18:28: error: ac_nonexistent.h: No such file or directory
configure:11347: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:11387: checking which type of compiler we have
configure:11584: result: gnu 4.4
configure:11781: checking for ANSI C header files
configure:11801: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11801: $? = 0
configure:11874: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c  >&5
configure:11874: $? = 0
configure:11874: ./conftest
configure:11874: $? = 0
configure:11885: result: yes
configure:11898: checking for sys/types.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for sys/stat.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for stdlib.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for string.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for memory.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for strings.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for inttypes.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for stdint.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11898: checking for unistd.h
configure:11898: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11898: $? = 0
configure:11898: result: yes
configure:11911: checking whether byte ordering is bigendian
configure:11926: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
conftest.c:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'a'
configure:11926: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| /* end confdefs.h.  */
| #ifndef __APPLE_CC__
| 	       not a universal capable compiler
| 	     #endif
| 	     typedef int dummy;
| 
configure:11971: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
configure:11971: $? = 0
configure:11989: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c   conftest.c >&5
conftest.c: In function 'main':
conftest.c:36: error: 'not' undeclared (first use in this function)
conftest.c:36: error: (Each undeclared identifier is reported only once
conftest.c:36: error: for each function it appears in.)
conftest.c:36: error: expected ';' before 'big'
configure:11989: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| /* end confdefs.h.  */
| #include <sys/types.h>
| 		#include <sys/param.h>
| 
| int
| main ()
| {
| #if BYTE_ORDER != BIG_ENDIAN
| 		 not big endian
| 		#endif
| 
|   ;
|   return 0;
| }
configure:12117: result: no
configure:12532: checking for C++ compiler version
configure:12541: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx --version >&5
g++ (Ubuntu 4.4.3-4ubuntu5) 4.4.3
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:12552: $? = 0
configure:12541: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx -v >&5
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-4ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 
configure:12552: $? = 0
configure:12541: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx -V >&5
g++: '-V' option must have argument
configure:12552: $? = 1
configure:12541: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx -qversion >&5
g++: unrecognized option '-qversion'
g++: no input files
configure:12552: $? = 1
configure:12556: checking whether we are using the GNU C++ compiler
configure:12575: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx -c   conftest.cpp >&5
configure:12575: $? = 0
configure:12584: result: yes
configure:12593: checking whether /usr/local/openmpi/1.4.2/gcc/bin/mpicxx accepts -g
configure:12613: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx -c -g  conftest.cpp >&5
configure:12613: $? = 0
configure:12654: result: yes
configure:12679: checking dependency style of /usr/local/openmpi/1.4.2/gcc/bin/mpicxx
configure:12789: result: gcc3
configure:12818: checking which type of C++ compiler we have
configure:13012: result: gnu 4.4
configure:13413: checking for Fortran compiler version
configure:13422: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 --version >&5
GNU Fortran (Ubuntu 4.4.3-4ubuntu5) 4.4.3
Copyright (C) 2010 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

configure:13433: $? = 0
configure:13422: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -v >&5
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-4ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 
configure:13433: $? = 0
configure:13422: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -V >&5
gfortran: '-V' option must have argument
configure:13433: $? = 1
configure:13422: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -qversion >&5
gfortran: unrecognized option '-qversion'
gfortran: no input files
configure:13433: $? = 1
configure:13442: checking whether we are using the GNU Fortran compiler
configure:13455: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c   conftest.F >&5
configure:13455: $? = 0
configure:13464: result: yes
configure:13470: checking whether /usr/local/openmpi/1.4.2/gcc/bin/mpif90 accepts -g
configure:13481: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c -g  conftest.f >&5
configure:13481: $? = 0
configure:13489: result: yes
configure:13580: checking which type of Fortran compiler we have
configure:13934: result: gnu 4.4
configure:13946: checking fortran 90 modules extension
configure:13973: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c -g -O2  conftest.f >&5
configure:13973: $? = 0
configure:13996: result: mod
configure:14011: checking for Fortran flag to compile .F90 files
configure:14027: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c -g -O2  conftest.F90 >&5
configure:14027: $? = 0
configure:14036: result: none
configure:14072: determining Fortran module case
configure:14086: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c -g -O2  conftest.F90 >&5
configure:14086: $? = 0
configure:14110: checking whether Fortran modules are upper-case
configure:14112: result: no
configure:14130: checking how to get verbose linking output from /usr/local/openmpi/1.4.2/gcc/bin/mpif90
configure:14140: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c   conftest.F90 >&5
configure:14140: $? = 0
configure:14158: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest -v conftest.F90
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-4ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/f951 conftest.F90 -cpp /tmp/ccPvUX8o.f90 -quiet -v -I/usr/local/openmpi/1.4.2/gcc/include -I/usr/local/openmpi/1.4.2/gcc/lib -D_REENTRANT conftest.F90 -D_FORTIFY_SOURCE=2 -quiet -dumpbase conftest.F90 -mtune=generic -auxbase conftest -version -fintrinsic-modules-path /usr/lib/gcc/x86_64-linux-gnu/4.4.3/finclude -o /tmp/ccoN8jew.s
GNU Fortran (Ubuntu 4.4.3-4ubuntu5) version 4.4.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.4.3, GMP version 4.3.2, MPFR version 2.4.2-p1.
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/usr/include/x86_64-linux-gnu"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/openmpi/1.4.2/gcc/include
 /usr/local/openmpi/1.4.2/gcc/lib
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/finclude
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/include
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/include-fixed
 /usr/include
End of search list.
GNU Fortran (Ubuntu 4.4.3-4ubuntu5) version 4.4.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.4.3, GMP version 4.3.2, MPFR version 2.4.2-p1.
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
 as -V -Qy -o /tmp/ccPAiMkD.o /tmp/ccoN8jew.s
GNU assembler version 2.20.1 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.20.1-system.20100303
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/collect2 --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=both -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o conftest -z relro /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/crtbegin.o -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu /tmp/ccPAiMkD.o -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl --export-dynamic -lnsl -lutil -lgfortranbegin -lgfortran -lm -ldl -lgfortran -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.4.3/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crtn.o
configure:14223: result: -v
configure:14225: checking for Fortran libraries of /usr/local/openmpi/1.4.2/gcc/bin/mpif90
configure:14248: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest -v conftest.F90
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-4ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/f951 conftest.F90 -cpp /tmp/ccholOLi.f90 -quiet -v -I/usr/local/openmpi/1.4.2/gcc/include -I/usr/local/openmpi/1.4.2/gcc/lib -D_REENTRANT conftest.F90 -D_FORTIFY_SOURCE=2 -quiet -dumpbase conftest.F90 -mtune=generic -auxbase conftest -version -fintrinsic-modules-path /usr/lib/gcc/x86_64-linux-gnu/4.4.3/finclude -o /tmp/cctAFcZp.s
GNU Fortran (Ubuntu 4.4.3-4ubuntu5) version 4.4.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.4.3, GMP version 4.3.2, MPFR version 2.4.2-p1.
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/usr/include/x86_64-linux-gnu"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/openmpi/1.4.2/gcc/include
 /usr/local/openmpi/1.4.2/gcc/lib
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/finclude
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/include
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/include-fixed
 /usr/include
End of search list.
GNU Fortran (Ubuntu 4.4.3-4ubuntu5) version 4.4.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.4.3, GMP version 4.3.2, MPFR version 2.4.2-p1.
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
 as -V -Qy -o /tmp/ccpWa7dx.o /tmp/cctAFcZp.s
GNU assembler version 2.20.1 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.20.1-system.20100303
 /usr/lib/gcc/x86_64-linux-gnu/4.4.3/collect2 --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=both -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o conftest -z relro /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/crtbegin.o -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu /tmp/ccpWa7dx.o -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl --export-dynamic -lnsl -lutil -lgfortranbegin -lgfortran -lm -ldl -lgfortran -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.4.3/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crtn.o
configure:14422: result:  -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread
configure:14438: checking for dummy main to link with Fortran libraries
configure:14472: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c   -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread >&5
configure:14472: $? = 0
configure:14517: result: none
configure:14550: checking for Fortran name-mangling scheme
configure:14563: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -c   conftest.F90 >&5
configure:14563: $? = 0
configure:14604: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c cfortran_test.o   -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread >&5
/tmp/ccxTPWyw.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `foobar'
collect2: ld returned 1 exit status
configure:14604: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char foobar ();
| #ifdef FC_DUMMY_MAIN
| #ifndef FC_DUMMY_MAIN_EQ_F77
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int FC_DUMMY_MAIN() { return 1; }
| #endif
| #endif
| int
| main ()
| {
| return foobar ();
|   ;
|   return 0;
| }
configure:14604: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c cfortran_test.o   -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread >&5
configure:14604: $? = 0
configure:14662: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest    conftest.c cfortran_test.o   -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread >&5
configure:14662: $? = 0
configure:14704: result: lower case, underscore, no extra underscore
configure:14801: checking for python
configure:14817: found /usr/bin/python
configure:14828: result: python
configure:14843: checking for python-config
configure:14873: result: no
configure:14843: checking for python2.6-config
configure:14873: result: no
configure:14843: checking for python2.5-config
configure:14873: result: no
configure:14843: checking for python2.4-config
configure:14873: result: no
configure:14891: checking for Python CPPFLAGS
configure:14896: result: 
configure:14905: checking for bzr
configure:14921: found /usr/bin/bzr
configure:14932: result: bzr
configure:14952: checking for Python NumPy headers
configure:14966: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c    conftest.c >&5
conftest.c:35:20: error: Python.h: No such file or directory
conftest.c:36:31: error: numpy/arrayobject.h: No such file or directory
configure:14966: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| /* end confdefs.h.  */
| 
| #include <Python.h>
| #include <numpy/arrayobject.h>
| 
| int main(int argc, char** argv)
| {
|     return 0;
| }
configure:14977: result: not found
configure:14983: checking numarray/arrayobject.h usability
configure:14983: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c    conftest.c >&5
conftest.c:67:34: error: numarray/arrayobject.h: No such file or directory
configure:14983: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #include <numarray/arrayobject.h>
configure:14983: result: no
configure:14983: checking numarray/arrayobject.h presence
configure:14983: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E   conftest.c
conftest.c:34:34: error: numarray/arrayobject.h: No such file or directory
configure:14983: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| /* end confdefs.h.  */
| #include <numarray/arrayobject.h>
configure:14983: result: no
configure:14983: checking for numarray/arrayobject.h
configure:14983: result: no
configure:15005: retrieving Bazaar branch information
configure:15268: checking for ar
configure:15284: found /usr/bin/ar
configure:15295: result: ar
configure:15356: checking for ranlib
configure:15372: found /usr/bin/ranlib
configure:15383: result: ranlib
configure:15454: checking for cpp
configure:15470: found /usr/bin/cpp
configure:15481: result: cpp
configure:15540: checking for a true C preprocessor
configure:15546: result: cpp
configure:16021: checking which Fortran preprocessor to use
configure:16023: result: 
configure:16025: checking which Fortran preprocessor flags to apply
configure:16027: result: 
configure:16051: checking whether to wrap Fortran compiler calls
configure:16053: result: no
configure:16092: checking debugging status
configure:16096: result: disabled
configure:16153: debugging has been turned off
configure:16157: checking whether to activate debug mode in source files
configure:16167: result: no
configure:16468: checking whether to activate design-by-contract debugging
configure:16477: result: no
configure:16524: checking optimization status
configure:16532: result: enabled (using compiler defaults)
configure:20112: checking whether to apply per-directory optimizations
configure:20118: result: yes
configure:21389: checking for a 64-bit architecture
configure:21391: result: yes
configure:21393: checking whether to use 64-bit flags
configure:21395: result: yes
configure:21397: checking for user-defined 64-bit flags
configure:21399: result: 
configure:21404: checking for 64-bit C preprocessor flags
configure:21407: result: none
configure:21420: checking for 64-bit C flags
configure:21423: result: none
configure:21455: checking for 64-bit C++ flags
configure:21458: result: none
configure:21490: checking for 64-bit Fortran flags
configure:21493: result: none
configure:21506: checking for 64-bit archiver flags
configure:21509: result: none
configure:21597: static builds may be performed
configure:21644: checking stddef.h usability
configure:21644: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21644: $? = 0
configure:21644: result: yes
configure:21644: checking stddef.h presence
configure:21644: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21644: $? = 0
configure:21644: result: yes
configure:21644: checking for stddef.h
configure:21644: result: yes
configure:21644: checking stdarg.h usability
configure:21644: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21644: $? = 0
configure:21644: result: yes
configure:21644: checking stdarg.h presence
configure:21644: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21644: $? = 0
configure:21644: result: yes
configure:21644: checking for stdarg.h
configure:21644: result: yes
configure:21658: checking stdio.h usability
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking stdio.h presence
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking for stdio.h
configure:21658: result: yes
configure:21658: checking malloc.h usability
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking malloc.h presence
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking for malloc.h
configure:21658: result: yes
configure:21658: checking math.h usability
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking math.h presence
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking for math.h
configure:21658: result: yes
configure:21658: checking termios.h usability
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking termios.h presence
configure:21658: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21658: $? = 0
configure:21658: result: yes
configure:21658: checking for termios.h
configure:21658: result: yes
configure:21671: checking errno.h usability
configure:21671: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21671: $? = 0
configure:21671: result: yes
configure:21671: checking errno.h presence
configure:21671: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21671: $? = 0
configure:21671: result: yes
configure:21671: checking for errno.h
configure:21671: result: yes
configure:21683: checking mcheck.h usability
configure:21683: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:21683: $? = 0
configure:21683: result: yes
configure:21683: checking mcheck.h presence
configure:21683: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -E      conftest.c
configure:21683: $? = 0
configure:21683: result: yes
configure:21683: checking for mcheck.h
configure:21683: result: yes
configure:21699: checking for abort
configure:21699: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
conftest.c:67: warning: conflicting types for built-in function 'abort'
configure:21699: $? = 0
configure:21699: result: yes
configure:21716: checking size of char
configure:21721: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21721: $? = 0
configure:21721: ./conftest
configure:21721: $? = 0
configure:21736: result: 1
configure:21750: checking size of short
configure:21755: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21755: $? = 0
configure:21755: ./conftest
configure:21755: $? = 0
configure:21770: result: 2
configure:21784: checking size of int
configure:21789: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21789: $? = 0
configure:21789: ./conftest
configure:21789: $? = 0
configure:21804: result: 4
configure:21818: checking size of long
configure:21823: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21823: $? = 0
configure:21823: ./conftest
configure:21823: $? = 0
configure:21838: result: 8
configure:21852: checking size of long long
configure:21857: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21857: $? = 0
configure:21857: ./conftest
configure:21857: $? = 0
configure:21872: result: 8
configure:21886: checking size of unsigned int
configure:21891: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21891: $? = 0
configure:21891: ./conftest
configure:21891: $? = 0
configure:21906: result: 4
configure:21920: checking size of unsigned long
configure:21925: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21925: $? = 0
configure:21925: ./conftest
configure:21925: $? = 0
configure:21940: result: 8
configure:21954: checking size of unsigned long long
configure:21959: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21959: $? = 0
configure:21959: ./conftest
configure:21959: $? = 0
configure:21974: result: 8
configure:21988: checking size of float
configure:21993: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:21993: $? = 0
configure:21993: ./conftest
configure:21993: $? = 0
configure:22008: result: 4
configure:22022: checking size of double
configure:22027: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:22027: $? = 0
configure:22027: ./conftest
configure:22027: $? = 0
configure:22042: result: 8
configure:22056: checking size of long double
configure:22061: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:22061: $? = 0
configure:22061: ./conftest
configure:22061: $? = 0
configure:22076: result: 16
configure:22090: checking size of size_t
configure:22095: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:22095: $? = 0
configure:22095: ./conftest
configure:22095: $? = 0
configure:22110: result: 8
configure:22124: checking size of ptrdiff_t
configure:22129: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest            conftest.c  >&5
configure:22129: $? = 0
configure:22129: ./conftest
configure:22129: $? = 0
configure:22144: result: 8
configure:22155: checking for an ANSI C-conforming const
configure:22228: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:22228: $? = 0
configure:22235: result: yes
configure:22243: checking for size_t
configure:22243: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
configure:22243: $? = 0
configure:22243: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -c           conftest.c >&5
conftest.c: In function 'main':
conftest.c:102: error: expected expression before ')' token
configure:22243: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "6.5.0"
| #define PACKAGE_STRING "ABINIT 6.5.0"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "6.5.0"
| #define ABINIT_VERSION "6.5.0"
| #define ABINIT_VERSION_MAJOR "6"
| #define ABINIT_VERSION_MINOR "5"
| #define ABINIT_VERSION_MICRO "0"
| #define ABINIT_VERSION_BUILD "20100907"
| #define ABINIT_VERSION_BASE "6.5"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| #define HAVE_BZR_BRANCH 1
| #define ABINIT_TARGET "x86_64_linux_gnu4.4"
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MCHECK_H 1
| #define HAVE_ABORT 1
| #define SIZEOF_CHAR 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_UNSIGNED_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG_DOUBLE 16
| #define SIZEOF_SIZE_T 8
| #define SIZEOF_PTRDIFF_T 8
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #ifdef FC_DUMMY_MAIN
| #ifndef FC_DUMMY_MAIN_EQ_F77
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int FC_DUMMY_MAIN() { return 1; }
| #endif
| #endif
| int
| main ()
| {
| if (sizeof ((size_t)))
| 	    return 0;
|   ;
|   return 0;
| }
configure:22243: result: yes
configure:22261: checking whether the Fortran compiler provides the iso_c_binding module
configure:22283: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22283: $? = 0
configure:22301: result: yes
configure:22307: checking whether the Fortran compiler accepts exit()
configure:22322: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22322: $? = 0
configure:22340: result: yes
configure:22346: checking whether the Fortran compiler accepts flush()
configure:22361: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22361: $? = 0
configure:22379: result: yes
configure:22385: checking whether the Fortran compiler accepts flush_()
configure:22400: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
/tmp/ccNFZS3Y.o: In function `MAIN__':
conftest.F90:(.text+0x1a): undefined reference to `flush__'
collect2: ld returned 1 exit status
configure:22400: $? = 1
configure: failed program was:
|       program main
| 
|             call flush_()
| 
|       end
configure:22418: result: no
configure:22424: checking whether the Fortran compiler accepts gamma()
configure:22440: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22440: $? = 0
configure:22458: result: yes
configure:22464: checking whether the Fortran compiler accepts getenv()
configure:22481: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22481: $? = 0
configure:22499: result: yes
configure:22517: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
/tmp/cckO4Pwb.o: In function `MAIN__':
conftest.F90:(.text+0x1a): undefined reference to `getpid_'
collect2: ld returned 1 exit status
configure:22517: $? = 1
configure: failed program was:
|       program main
| 
|           call getpid()
| 
|       end
configure:22529: checking whether the Fortran compiler accepts getpid()
configure:22531: result: no
configure:22542: checking whether the Fortran compiler accepts the null() intrinsic
configure:22561: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22561: $? = 0
configure:22579: result: yes
configure:22585: checking whether the Fortran compiler accepts quadruple integers
configure:22601: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
configure:22601: $? = 0
configure:22620: result: yes
configure:22626: checking whether the Fortran compiler accepts long lines
configure:22641: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
conftest.F90:3.19:

         write(*,*)'01234567890123456789012345678901234567890123456789012345678
                   1
Error: Unterminated character constant beginning at (1)
conftest.F90:3.132:

789012345678901234567890123456789012345678901234567890123456789012345678901
                                                                           1                                                         
Warning: Line truncated at (1)
configure:22641: $? = 1
configure: failed program was:
|       program main
| 
|          write(*,*)'0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789' !142
| 
|       end
configure:22659: result: no
configure:22667: checking whether the Fortran compiler accepts etime()
configure:22682: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native   conftest.F90  >&5
conftest.F90:3.25:

            call etime(1)
                         1
Error: Missing actual argument 'time' in call to 'etime' at (1)
configure:22682: $? = 1
configure: failed program was:
|       program main
| 
|             call etime(1)
| 
|       end
configure:22700: result: no
configure:22705: checking whether to use C clock for timings
configure:22707: result: no
configure:22775: checking whether the C compiler supports MPI
configure:23023: /usr/local/openmpi/1.4.2/gcc/bin/mpicc -o conftest                 conftest.c       >&5
configure:23023: $? = 0
configure:23247: result: yes
configure:23253: checking whether the C++ compiler supports MPI
configure:23498: /usr/local/openmpi/1.4.2/gcc/bin/mpicxx -o conftest                 conftest.cpp       >&5
configure:23498: $? = 0
configure:23722: result: yes
configure:23728: checking whether the Fortran Compiler supports MPI
configure:23960: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native       conftest.F90       -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread  >&5
configure:23960: $? = 0
configure:24184: result: yes
configure:24193: checking whether MPI is usable
configure:24195: result: yes
configure:24237: WARNING: disabling MPI I/O is not recommended
configure:24242: checking whether to build MPI code
configure:24244: result: yes
configure:24253: checking whether to build MPI I/O code
configure:24255: result: no
configure:24263: checking whether to build MPI I/O untested features
configure:24265: result: no
configure:24273: checking whether to build MPI time tracing code
configure:24275: result: no
configure:24286: checking which level of MPI is supported by the Fortran compiler
configure:24520: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native       conftest.F90       -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread  >&5
configure:24520: $? = 0
configure:24745: result: 2
configure:24805: checking whether to activate GPU support
configure:24807: result: no
configure:25411: checking whether to use transferable I/O libraries
configure:25413: result: no
configure:26547: checking whether to use optimized timer libraries
configure:26549: result: no
configure:27169: checking whether to use optimized linear algebra libraries
configure:27171: result: yes
configure:27173: checking whether to activate ScaLAPACK support
configure:27175: result: no
configure:27422: checking for the requested linear algebra support
configure:27424: result: netlib
configure:28547: checking for a serial optimized linear algebra support
configure:28557: /usr/local/openmpi/1.4.2/gcc/bin/mpif90 -o conftest    -O3 -ffast-math -funroll-loops -march=native       conftest.F90 -lblas -llapack       -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread  >&5
configure:28557: $? = 0
configure:28564: result: yes
configure:28567: checking for a MPI optimized linear algebra support
configure:28586: result: no
configure:28852: checking for the actual linear algebra support
configure:28854: result: netlib
configure:28884: checking whether to use optimized math libraries
configure:28886: result: no
configure:29676: checking whether to use optimized FFT libraries
configure:29678: result: no
configure:30912: checking whether to use DFT libraries
configure:30914: result: no
configure:31779: using tarball repository /home/jzwanzig/.abinit/tarballs
configure:32165: checking whether to enable the FOX plug-in
configure:32167: result: no
configure:32169: checking whether to build the FOX plug-in
configure:32171: result: no
configure:32582: checking whether to enable the NETCDF plug-in
configure:32584: result: no
configure:32586: checking whether to build the NETCDF plug-in
configure:32588: result: no
configure:32961: checking whether to enable the ETSF_IO plug-in
configure:32963: result: no
configure:32965: checking whether to build the ETSF_IO plug-in
configure:32967: result: no
configure:33323: checking whether to enable the LIBXC plug-in
configure:33325: result: no
configure:33327: checking whether to build the LIBXC plug-in
configure:33329: result: no
configure:33688: checking whether to enable the BIGDFT plug-in
configure:33690: result: no
configure:33692: checking whether to build the BIGDFT plug-in
configure:33694: result: no
configure:33802: checking for a source tarball of WANNIER90
configure:33805: result: yes
configure:33874: tarball MD5 check succeeded
configure:34042: applying Wannier90 tricks (vendor: gnu, version: 4.4)
configure:34069: checking whether to enable the WANNIER90 plug-in
configure:34071: result: yes
configure:34073: checking whether to build the WANNIER90 plug-in
configure:34075: result: yes
configure:34157: checking whether to build test timeout code
configure:34159: result: no
configure:34328: checking timeout for automatic tests
configure:34331: result: none
configure:34374: checking whether to enable bindings
configure:34376: result: no
configure:35012: checking whether to enable BSE unpacking
configure:35019: result: no
configure:35023: checking whether to enable CLib
configure:35030: result: no
configure:35042: checking whether to build exports
configure:35044: result: no
configure:35056: checking whether to accelerate 'make check'
configure:35058: result: no
configure:35070: checking whether to enable GW cut-off
configure:35077: result: no
configure:35081: checking whether to enable GW double-precision calculations
configure:35088: result: no
configure:35100: checking whether to enable optimal GW
configure:35107: result: no
configure:35111: checking whether to enable GW wrapper
configure:35118: result: no
configure:35122: checking whether to activate maintainer checks
configure:35124: result: no
configure:35144: checking whether to use macroave
configure:35151: result: yes
configure:35171: checking whether to read input from stdin
configure:35178: result: yes
configure:35182: checking whether to activate Symmetric Multi-Processing
configure:35189: result: no
configure:35490: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by ABINIT config.status 6.5.0, which was
generated by GNU Autoconf 2.65.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on jwzpc17

config.status:1582: creating config.dump
config.status:1582: creating config.mk
config.status:1582: creating config.pc
config.status:1582: creating config.sh
config.status:1582: creating config/wrappers/wrap-fc
config.status:1582: creating src/incs/Makefile
config.status:1582: creating src/mods/Makefile
config.status:1582: creating src/16_hideleave/m_build_info.F90
config.status:1582: creating tests/tests.env
config.status:1582: creating tests/tests-install.env
config.status:1582: creating Makefile
config.status:1582: creating src/Makefile
config.status:1582: creating src/01_gsl_ext/Makefile
config.status:1582: creating src/01_interfaces_ext/Makefile
config.status:1582: creating src/01_macroavnew_ext/Makefile
config.status:1582: creating src/01_qespresso_ext/Makefile
config.status:1582: creating src/02_clib/Makefile
config.status:1582: creating src/10_defs/Makefile
config.status:1582: creating src/12_hide_mpi/Makefile
config.status:1582: creating src/14_hidewrite/Makefile
config.status:1582: creating src/15_gpu_toolbox/Makefile
config.status:1582: creating src/16_hideleave/Makefile
config.status:1582: creating src/18_timing/Makefile
config.status:1582: creating src/27_toolbox_oop/Makefile
config.status:1582: creating src/28_numeric_noabirule/Makefile
config.status:1582: creating src/32_contract/Makefile
config.status:1582: creating src/32_util/Makefile
config.status:1582: creating src/42_geometry/Makefile
config.status:1582: creating src/42_geomoptim/Makefile
config.status:1582: creating src/42_nlstrain/Makefile
config.status:1582: creating src/42_parser/Makefile
config.status:1582: creating src/43_ptgroups/Makefile
config.status:1582: creating src/45_psp_parser/Makefile
config.status:1582: creating src/47_xml/Makefile
config.status:1582: creating src/49_gw_toolbox_oop/Makefile
config.status:1582: creating src/50_abitypes_defs/Makefile
config.status:1582: creating src/51_manage_cuda/Makefile
config.status:1582: creating src/51_manage_mpi/Makefile
config.status:1582: creating src/52_fft_mpi_noabirule/Makefile
config.status:1582: creating src/53_abiutil/Makefile
config.status:1582: creating src/53_ffts/Makefile
config.status:1582: creating src/53_spacepar/Makefile
config.status:1582: creating src/56_recipspace/Makefile
config.status:1582: creating src/56_xc/Makefile
config.status:1582: creating src/57_iovars/Makefile
config.status:1582: creating src/59_io_mpi/Makefile
config.status:1582: creating src/61_ionetcdf/Makefile
config.status:1582: creating src/62_cg_noabirule/Makefile
config.status:1582: creating src/62_iowfdenpot/Makefile
config.status:1582: creating src/62_occeig/Makefile
config.status:1582: creating src/62_poisson/Makefile
config.status:1582: creating src/62_wvl_wfs/Makefile
config.status:1582: creating src/63_bader/Makefile
config.status:1582: creating src/64_atompaw/Makefile
config.status:1582: creating src/65_nonlocal/Makefile
config.status:1582: creating src/65_psp/Makefile
config.status:1582: creating src/66_paw/Makefile
config.status:1582: creating src/66_wfs/Makefile
config.status:1582: creating src/67_common/Makefile
config.status:1582: creating src/68_dmft/Makefile
config.status:1582: creating src/68_gw/Makefile
config.status:1582: creating src/68_recursion/Makefile
config.status:1582: creating src/68_rsprc/Makefile
config.status:1582: creating src/69_bse/Makefile
config.status:1582: creating src/72_response/Makefile
config.status:1582: creating src/77_ddb/Makefile
config.status:1582: creating src/77_lwf/Makefile
config.status:1582: creating src/77_suscep/Makefile
config.status:1582: creating src/79_seqpar_mpi/Makefile
config.status:1582: creating src/83_cut3d/Makefile
config.status:1582: creating src/93_rdm/Makefile
config.status:1582: creating src/95_drive/Makefile
config.status:1582: creating src/98_main/Makefile
config.status:1582: creating src/libs/Makefile
config.status:1582: creating tests/Nightly/Makefile
config.status:1582: creating prereqs/Makefile
config.status:1582: creating prereqs/linalg/Makefile
config.status:1582: creating plugins/Makefile
config.status:1582: creating plugins/bigdft/Makefile
config.status:1582: creating plugins/etsf_io/Makefile
config.status:1582: creating plugins/fox/Makefile
config.status:1582: creating plugins/libxc/Makefile
config.status:1582: creating plugins/netcdf/Makefile
config.status:1582: creating plugins/wannier90/Makefile
config.status:1582: creating bindings/Makefile
config.status:1582: creating bindings/parser/Makefile
config.status:1582: creating doc/Makefile
config.status:1582: creating tests/Makefile
config.status:1582: creating config.h
config.status:1795: executing depfiles commands
config.status:1795: executing dump-optim commands
config.status:1795: executing script-perms commands
config.status:1795: executing long-lines commands

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_c_bigendian=no
ac_cv_c_compiler_gnu=yes
ac_cv_c_const=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_ARFLAGS_EXTRA_set=
ac_cv_env_ARFLAGS_EXTRA_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_LDFLAGS_set=
ac_cv_env_CC_LDFLAGS_value=
ac_cv_env_CC_LIBS_set=
ac_cv_env_CC_LIBS_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_EXTRA_set=
ac_cv_env_CFLAGS_EXTRA_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_EXTRA_set=
ac_cv_env_CPPFLAGS_EXTRA_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_EXTRA_set=
ac_cv_env_CXXFLAGS_EXTRA_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_LDFLAGS_EXTRA_set=
ac_cv_env_CXX_LDFLAGS_EXTRA_value=
ac_cv_env_CXX_LDFLAGS_set=
ac_cv_env_CXX_LDFLAGS_value=
ac_cv_env_CXX_LIBS_set=
ac_cv_env_CXX_LIBS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_FCFLAGS_EXTRA_set=
ac_cv_env_FCFLAGS_EXTRA_value=
ac_cv_env_FCFLAGS_set=
ac_cv_env_FCFLAGS_value=
ac_cv_env_FC_LDFLAGS_EXTRA_set=
ac_cv_env_FC_LDFLAGS_EXTRA_value=
ac_cv_env_FC_LDFLAGS_set=
ac_cv_env_FC_LDFLAGS_value=
ac_cv_env_FC_LIBS_set=
ac_cv_env_FC_LIBS_value=
ac_cv_env_FC_set=
ac_cv_env_FC_value=
ac_cv_env_FPPFLAGS_EXTRA_set=
ac_cv_env_FPPFLAGS_EXTRA_value=
ac_cv_env_FPPFLAGS_set=
ac_cv_env_FPPFLAGS_value=
ac_cv_env_FPP_set=
ac_cv_env_FPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MPI_RUNNER_set=
ac_cv_env_MPI_RUNNER_value=
ac_cv_env_SERIAL_RUNNER_set=
ac_cv_env_SERIAL_RUNNER_value=
ac_cv_env_XPPFLAGS_EXTRA_set=
ac_cv_env_XPPFLAGS_EXTRA_value=
ac_cv_env_XPPFLAGS_set=
ac_cv_env_XPPFLAGS_value=
ac_cv_env_XPP_set=
ac_cv_env_XPP_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_fc_compiler_gnu=yes
ac_cv_fc_dummy_main=none
ac_cv_fc_libs=' -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread'
ac_cv_fc_mangling='lower case, underscore, no extra underscore'
ac_cv_fc_srcext_F90=none
ac_cv_fortran_dummy_main=none
ac_cv_func_abort=yes
ac_cv_header_errno_h=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_malloc_h=yes
ac_cv_header_math_h=yes
ac_cv_header_mcheck_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_numarray_arrayobject_h=no
ac_cv_header_stdarg_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stddef_h=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdio_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_termios_h=yes
ac_cv_header_unistd_h=yes
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_objext=o
ac_cv_path_BOURNE_SHELL=/bin/sh
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_GREP=/bin/grep
ac_cv_path_MV=/bin/mv
ac_cv_path_PERL=/usr/bin/perl
ac_cv_path_RM=/bin/rm
ac_cv_path_SED=/bin/sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AR=ar
ac_cv_prog_AWK=gawk
ac_cv_prog_BAZAAR=bzr
ac_cv_prog_CPP='/usr/local/openmpi/1.4.2/gcc/bin/mpicc -E'
ac_cv_prog_DVI2PDF=dvipdf
ac_cv_prog_MD5SUM=md5sum
ac_cv_prog_PATCH=patch
ac_cv_prog_PS2PDF=ps2pdf
ac_cv_prog_PYTHON=python
ac_cv_prog_TAR=tar
ac_cv_prog_TRUE_CPP=cpp
ac_cv_prog_WGET=wget
ac_cv_prog_ac_ct_CC=/usr/local/openmpi/1.4.2/gcc/bin/mpicc
ac_cv_prog_ac_ct_RANLIB=ranlib
ac_cv_prog_cc_c89=
ac_cv_prog_cc_c99=no
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_prog_fc_g=yes
ac_cv_prog_fc_v=-v
ac_cv_prog_make_make_set=yes
ac_cv_sizeof_char=1
ac_cv_sizeof_double=8
ac_cv_sizeof_float=4
ac_cv_sizeof_int=4
ac_cv_sizeof_long=8
ac_cv_sizeof_long_double=16
ac_cv_sizeof_long_long=8
ac_cv_sizeof_ptrdiff_t=8
ac_cv_sizeof_short=2
ac_cv_sizeof_size_t=8
ac_cv_sizeof_unsigned_int=4
ac_cv_sizeof_unsigned_long=8
ac_cv_sizeof_unsigned_long_long=8
ac_cv_target=x86_64-unknown-linux-gnu
ac_cv_type_size_t=yes
am_cv_CC_dependencies_compiler_type=gcc3
am_cv_CXX_dependencies_compiler_type=gcc3
ax_cv_f90_modext=mod

## ----------------- ##
## Output variables. ##
## ----------------- ##

ABINIT_BINARY_PACKAGE='abinit-6.5.0_x86_64_linux_gnu4.4'
ABINIT_TARGET='x86_64_linux_gnu4.4'
ABINIT_VERSION='6.5.0'
ABINIT_VERSION_BASE='6.5'
ABINIT_VERSION_BUILD='20100907'
ABINIT_VERSION_MAJOR='6'
ABINIT_VERSION_MICRO='0'
ABINIT_VERSION_MINOR='5'
ABI_CPPFLAGS='    '
ACLOCAL='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/missing --run aclocal-1.11'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/missing --run tar'
AR='ar'
ARFLAGS='     rc'
ARFLAGS_64BITS=''
ARFLAGS_CMD='rc'
ARFLAGS_DEBUG=''
ARFLAGS_EXTRA=''
ARFLAGS_HINTS=''
ARFLAGS_OPT=''
AUTOCONF='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/missing --run autoconf'
AUTOHEADER='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/missing --run autoheader'
AUTOMAKE='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/missing --run automake-1.11'
AWK='gawk'
BAZAAR='bzr'
BOURNE_SHELL='/bin/sh'
CC='/usr/local/openmpi/1.4.2/gcc/bin/mpicc'
CCDEPMODE='depmode=gcc3'
CC_LDFLAGS='    '
CC_LDFLAGS_64BITS=''
CC_LDFLAGS_DEBUG=''
CC_LDFLAGS_EXTRA=''
CC_LDFLAGS_GPU=''
CC_LDFLAGS_HINTS=''
CC_LDFLAGS_OPT=''
CC_LIBS='    '
CC_LIBS_64BITS=''
CC_LIBS_DEBUG=''
CC_LIBS_EXTRA=''
CC_LIBS_GPU=''
CC_LIBS_HINTS=''
CC_LIBS_OPT=''
CFGFLAGS_BIGDFT=''
CFGFLAGS_ETSF_IO=''
CFGFLAGS_FOX=''
CFGFLAGS_LIBXC=''
CFGFLAGS_NETCDF=''
CFGFLAGS_WANNIER90=''
CFLAGS='    '
CFLAGS_64BITS=''
CFLAGS_BIGDFT='    '
CFLAGS_DEBUG=''
CFLAGS_ETSF_IO='    '
CFLAGS_EXTRA=''
CFLAGS_FOX='    '
CFLAGS_GPU=''
CFLAGS_HINTS=''
CFLAGS_LIBXC='    '
CFLAGS_LINALG='    '
CFLAGS_NETCDF='    '
CFLAGS_OPT=''
CFLAGS_WANNIER90='    '
CPP='/usr/local/openmpi/1.4.2/gcc/bin/mpicc -E'
CPPFLAGS=''
CPPFLAGS_64BITS=''
CPPFLAGS_BIGDFT=''
CPPFLAGS_DEBUG=''
CPPFLAGS_ETSF_IO=''
CPPFLAGS_EXTRA=''
CPPFLAGS_FOX=''
CPPFLAGS_GPU=''
CPPFLAGS_HINTS=''
CPPFLAGS_LIBXC=''
CPPFLAGS_LINALG='    '
CPPFLAGS_NETCDF=''
CPPFLAGS_OPT=''
CPPFLAGS_WANNIER90=' '
CXX='/usr/local/openmpi/1.4.2/gcc/bin/mpicxx'
CXXDEPMODE='depmode=gcc3'
CXXFLAGS='    '
CXXFLAGS_64BITS=''
CXXFLAGS_BIGDFT='    '
CXXFLAGS_DEBUG=''
CXXFLAGS_ETSF_IO='    '
CXXFLAGS_EXTRA=''
CXXFLAGS_FOX='    '
CXXFLAGS_GPU=''
CXXFLAGS_HINTS=''
CXXFLAGS_LIBXC='    '
CXXFLAGS_LINALG='    '
CXXFLAGS_NETCDF='    '
CXXFLAGS_OPT=''
CXXFLAGS_WANNIER90='    '
CXX_LDFLAGS='    '
CXX_LDFLAGS_64BITS=''
CXX_LDFLAGS_DEBUG=''
CXX_LDFLAGS_EXTRA=''
CXX_LDFLAGS_GPU=''
CXX_LDFLAGS_HINTS=''
CXX_LDFLAGS_OPT=''
CXX_LIBS='    '
CXX_LIBS_64BITS=''
CXX_LIBS_DEBUG=''
CXX_LIBS_EXTRA=''
CXX_LIBS_GPU=''
CXX_LIBS_HINTS=''
CXX_LIBS_OPT=''
CYGPATH_W='echo'
DEFS='-DHAVE_CONFIG_H'
DEPDIR='.deps'
DO_BUILD_01_GSL_EXT_FALSE=''
DO_BUILD_01_GSL_EXT_TRUE='#'
DO_BUILD_01_MACROAVNEW_EXT_FALSE='#'
DO_BUILD_01_MACROAVNEW_EXT_TRUE=''
DO_BUILD_02_CLIB_FALSE=''
DO_BUILD_02_CLIB_TRUE='#'
DO_BUILD_15_GPU_TOOLBOX_FALSE=''
DO_BUILD_15_GPU_TOOLBOX_TRUE='#'
DO_BUILD_32_CONTRACT_FALSE=''
DO_BUILD_32_CONTRACT_TRUE='#'
DO_BUILD_51_MANAGE_CUDA_FALSE=''
DO_BUILD_51_MANAGE_CUDA_TRUE='#'
DO_BUILD_BIGDFT_FALSE=''
DO_BUILD_BIGDFT_TRUE='#'
DO_BUILD_BINDINGS_FALSE=''
DO_BUILD_BINDINGS_TRUE='#'
DO_BUILD_CCLOCK_FALSE=''
DO_BUILD_CCLOCK_TRUE='#'
DO_BUILD_ETSF_IO_FALSE=''
DO_BUILD_ETSF_IO_TRUE='#'
DO_BUILD_EXPORTS_FALSE=''
DO_BUILD_EXPORTS_TRUE='#'
DO_BUILD_FOX_FALSE=''
DO_BUILD_FOX_TRUE='#'
DO_BUILD_LIBXC_FALSE=''
DO_BUILD_LIBXC_TRUE='#'
DO_BUILD_LINALG_FALSE=''
DO_BUILD_LINALG_TRUE='#'
DO_BUILD_MACROAVE_FALSE='#'
DO_BUILD_MACROAVE_TRUE=''
DO_BUILD_NETCDF_FALSE=''
DO_BUILD_NETCDF_TRUE='#'
DO_BUILD_NIGHTLY_FALSE=''
DO_BUILD_NIGHTLY_TRUE='#'
DO_BUILD_WANNIER90_FALSE='#'
DO_BUILD_WANNIER90_TRUE=''
DO_CHECK_FAST_FALSE=''
DO_CHECK_FAST_TRUE='#'
DO_TEST_ABIRULES_FALSE=''
DO_TEST_ABIRULES_TRUE='#'
DO_TEST_BIGDFT_FALSE=''
DO_TEST_BIGDFT_TRUE='#'
DO_TEST_BUILDSYS_FALSE=''
DO_TEST_BUILDSYS_TRUE='#'
DO_TEST_ETSF_IO_FALSE=''
DO_TEST_ETSF_IO_TRUE='#'
DO_TEST_FOX_FALSE=''
DO_TEST_FOX_TRUE='#'
DO_TEST_GWDP_FALSE=''
DO_TEST_GWDP_TRUE='#'
DO_TEST_LIBXC_FALSE=''
DO_TEST_LIBXC_TRUE='#'
DO_TEST_MPI_FALSE='#'
DO_TEST_MPI_TRUE=''
DO_TEST_NETCDF_FALSE=''
DO_TEST_NETCDF_TRUE='#'
DO_TEST_VDWXC_FALSE=''
DO_TEST_VDWXC_TRUE='#'
DO_TEST_WANNIER90_FALSE='#'
DO_TEST_WANNIER90_TRUE=''
DVI2PDF='dvipdf'
DVI2PS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
EXEEXT=''
F77='/usr/local/openmpi/1.4.2/gcc/bin/mpif90'
FC='/usr/local/openmpi/1.4.2/gcc/bin/mpif90'
FCFLAGS='   -O3 -ffast-math -funroll-loops -march=native'
FCFLAGS_64BITS=''
FCFLAGS_BIGDFT='   -O3 -ffast-math -funroll-loops -march=native '
FCFLAGS_DEBUG=''
FCFLAGS_ETSF_IO='   -O3 -ffast-math -funroll-loops -march=native '
FCFLAGS_EXTRA='-O3 -ffast-math -funroll-loops -march=native'
FCFLAGS_F90=''
FCFLAGS_FIXEDFORM=''
FCFLAGS_FOX='   -O3 -ffast-math -funroll-loops -march=native '
FCFLAGS_FREEFORM=''
FCFLAGS_HINTS=''
FCFLAGS_LIBXC='   -O3 -ffast-math -funroll-loops -march=native '
FCFLAGS_LINALG='   -O3 -ffast-math -funroll-loops -march=native '
FCFLAGS_MODDIR=''
FCFLAGS_NETCDF='   -O3 -ffast-math -funroll-loops -march=native '
FCFLAGS_OPT=''
FCFLAGS_WANNIER90='   -O3 -ffast-math -funroll-loops -march=native '
FCLIBS=' -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread'
FCLIBS_ETSF_IO=''
FCLIBS_FOX=''
FCLIBS_NETCDF=''
FCLIBS_WANNIER90='-lblas -llapack '
FC_LDFLAGS='    '
FC_LDFLAGS_64BITS=''
FC_LDFLAGS_DEBUG=''
FC_LDFLAGS_EXTRA=''
FC_LDFLAGS_HINTS=''
FC_LDFLAGS_OPT=''
FC_LIBS='      -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread'
FC_LIBS_64BITS=''
FC_LIBS_DEBUG=''
FC_LIBS_EXTRA=''
FC_LIBS_HINTS=''
FC_LIBS_OPT=''
FC_NOWRAP='/usr/local/openmpi/1.4.2/gcc/bin/mpif90'
FFLAGS='   -O3 -ffast-math -funroll-loops -march=native'
FPP=''
FPPFLAGS='    '
FPPFLAGS_DEBUG=''
FPPFLAGS_EXTRA=''
FPPFLAGS_HINTS=''
FPPFLAGS_OPT=''
GREP='/bin/grep'
GSL_CONFIG=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LATEX=''
LDFLAGS='    '
LIBOBJS=''
LIBS='      -L/usr/local/openmpi/1.4.2/gcc/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortranbegin -lgfortran -lm -lpthread '
LN_S='ln -s'
LTLIBOBJS=''
LTXFLAGS=''
MAKEINFO='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/missing --run makeinfo'
MARKDOWN='/usr/bin/perl /home/jzwanzig/code/abinit/6.5.0-private/tmp-gcc/../util/developers/markdown.pl'
MD5SUM='md5sum'
MDFLAGS=''
MKDIR_P='/bin/mkdir -p'
MODEXT='mod'
MPI_RUNNER='/usr/local/openmpi/1.4.2/gcc/bin/mpirun'
MV='/bin/mv'
NVCC=''
NVCC_CFLAGS=''
NVCC_CPPFLAGS=''
NVCC_LDFLAGS=''
NVCC_LIBS=''
OBJEXT='o'
PACKAGE='abinit'
PACKAGE_BUGREPORT='https://bugs.launchpad.net/abinit/'
PACKAGE_NAME='ABINIT'
PACKAGE_STRING='ABINIT 6.5.0'
PACKAGE_TARNAME='abinit'
PACKAGE_URL=''
PACKAGE_VERSION='6.5.0'
PATCH='patch'
PATH_SEPARATOR=':'
PDFFLAGS=''
PERL='/usr/bin/perl'
PS2PDF='ps2pdf'
PYTHON='python'
PYTHON_CONFIG=''
PYTHON_CPPFLAGS=''
RANLIB='ranlib'
RM='/bin/rm'
SED='/bin/sed'
SERIAL_RUNNER=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
TAR='tar'
TRUE_CPP='cpp'
VERSION='6.5.0'
WGET='wget'
XPP=''
XPPFLAGS='    '
XPPFLAGS_EXTRA=''
abi_ac_version='026500'
abi_am_version='011101'
abi_cc_path=''
abi_cc_vendor='gnu'
abi_cc_version='4.4'
abi_cpp_path=''
abi_cpu_64bits='yes'
abi_cpu_bits='64'
abi_cpu_model='unknown'
abi_cpu_platform='unknown'
abi_cpu_spec='unknown_unknown'
abi_cpu_vendor='unknown'
abi_cxx_path=''
abi_cxx_vendor='gnu'
abi_cxx_version='4.4'
abi_fc_path=''
abi_fc_vendor='gnu'
abi_fc_version='4.4'
abi_fc_wrap='no'
abi_fpp_path=''
abi_lt_version='020206'
abi_m4_version='010413'
abi_mpi_runner_works=''
abi_sys_spec='linux-x86_64'
abinit_bindir='/opt/abinit-6.3.1/bin'
abinit_builddir='/home/jzwanzig/code/abinit/6.5.0-private/tmp-gcc'
abinit_chkdir='/opt/abinit-6.3.1/share/abinit/tests'
abinit_datdir='/opt/abinit-6.3.1/share/abinit'
abinit_docdir='/opt/abinit-6.3.1/doc/abinit'
abinit_incdir='/opt/abinit-6.3.1/include'
abinit_libdir='/opt/abinit-6.3.1/lib'
abinit_mandir='/opt/abinit-6.3.1/share/man'
abinit_moddir='/home/jzwanzig/code/abinit/6.5.0-private/tmp-gcc/src/mods'
abinit_prefix='/opt/abinit-6.3.1'
abinit_srcdir='/home/jzwanzig/code/abinit/6.5.0-private/tmp-gcc/..'
abinit_tardir='/home/jzwanzig/.abinit/tarballs'
ac_ct_CC='/usr/local/openmpi/1.4.2/gcc/bin/mpicc'
ac_ct_CXX=''
ac_ct_FC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE='#'
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE='#'
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=' -I$(srcdir)'
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
bigdft_pkg_name='bigdft-1.2.0.2'
bigdft_pkg_string='BigDFT library 1.2.0.2 (upstream release)'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_bigdft='no'
build_cpu='x86_64'
build_etsf_io='no'
build_fox='no'
build_libxc='no'
build_netcdf='no'
build_os='linux-gnu'
build_vendor='unknown'
build_wannier90='yes'
bzr_branch='root@abinit3.pcpm.ucl.ac.be-20100906201025-um6idbq27xe4707z'
bzr_clean='0'
bzr_revno='365'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
enable_64bit_flags='yes'
enable_all_plugins=''
enable_bigdft='no'
enable_bindings='no'
enable_bse_unpacked='no'
enable_cclock='no'
enable_clib='no'
enable_config_file='yes'
enable_debug='no'
enable_dft='no'
enable_etsf_io='no'
enable_exports='no'
enable_fast_check='no'
enable_fc_wrapper='no'
enable_fft='no'
enable_fox='no'
enable_gpu='no'
enable_gw_cutoff='no'
enable_gw_dpc='no'
enable_gw_optimal='no'
enable_gw_wrapper='no'
enable_hints='no'
enable_libxc='no'
enable_linalg='yes'
enable_macroave='yes'
enable_maintainer_checks='no'
enable_math='no'
enable_mpi='yes'
enable_mpi_io='no'
enable_mpi_io_test='no'
enable_mpi_trace='no'
enable_netcdf='no'
enable_optim='yes'
enable_scalapack='no'
enable_shared=''
enable_smp='no'
enable_static=''
enable_stdin='yes'
enable_test_timeout='no'
enable_timer='no'
enable_trio='no'
enable_vdwxc='no'
enable_wannier90='yes'
etsf_io_pkg_name='etsf_io-1.0.3'
etsf_io_pkg_string='ETSF I/O library 1.0.3 (upstream release)'
exec_prefix='${prefix}'
fc_timing='standard'
fcflags_opt_01_gsl_ext=''
fcflags_opt_01_interfaces_ext=''
fcflags_opt_01_macroavnew_ext=''
fcflags_opt_01_qespresso_ext=''
fcflags_opt_02_clib=''
fcflags_opt_10_defs=''
fcflags_opt_12_hide_mpi=''
fcflags_opt_14_hidewrite=''
fcflags_opt_15_gpu_toolbox=''
fcflags_opt_16_hideleave=''
fcflags_opt_18_timing=''
fcflags_opt_27_toolbox_oop=''
fcflags_opt_28_numeric_noabirule=''
fcflags_opt_32_contract=''
fcflags_opt_32_util=''
fcflags_opt_42_geometry=''
fcflags_opt_42_geomoptim=''
fcflags_opt_42_nlstrain=''
fcflags_opt_42_parser=''
fcflags_opt_43_ptgroups='-O0'
fcflags_opt_45_psp_parser=''
fcflags_opt_47_xml=''
fcflags_opt_49_gw_toolbox_oop=''
fcflags_opt_50_abitypes_defs=''
fcflags_opt_51_manage_cuda=''
fcflags_opt_51_manage_mpi=''
fcflags_opt_52_fft_mpi_noabirule=''
fcflags_opt_53_abiutil=''
fcflags_opt_53_ffts=''
fcflags_opt_53_spacepar=''
fcflags_opt_56_recipspace=''
fcflags_opt_56_xc=''
fcflags_opt_57_iovars=''
fcflags_opt_59_io_mpi=''
fcflags_opt_61_ionetcdf=''
fcflags_opt_62_cg_noabirule=''
fcflags_opt_62_iowfdenpot=''
fcflags_opt_62_occeig=''
fcflags_opt_62_poisson=''
fcflags_opt_62_wvl_wfs=''
fcflags_opt_63_bader=''
fcflags_opt_64_atompaw=''
fcflags_opt_65_nonlocal=''
fcflags_opt_65_psp=''
fcflags_opt_66_paw=''
fcflags_opt_66_wfs=''
fcflags_opt_67_common=''
fcflags_opt_68_dmft=''
fcflags_opt_68_gw=''
fcflags_opt_68_recursion=''
fcflags_opt_68_rsprc=''
fcflags_opt_69_bse=''
fcflags_opt_72_response=''
fcflags_opt_77_ddb=''
fcflags_opt_77_lwf=''
fcflags_opt_77_suscep=''
fcflags_opt_79_seqpar_mpi=''
fcflags_opt_83_cut3d=''
fcflags_opt_93_rdm=''
fcflags_opt_95_drive=''
fcflags_opt_98_main=''
fcflags_opt_bigdft=''
fcflags_opt_etsf_io=''
fcflags_opt_fox=''
fcflags_opt_libxc=''
fcflags_opt_linalg=''
fcflags_opt_netcdf=''
fcflags_opt_wannier90=''
fox_pkg_name='FoX-4.0.4'
fox_pkg_string='FoX Fortran XML library 4.0.4 (upstream release)'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/jzwanzig/code/abinit/6.5.0-private/config/gnu/install-sh'
lib_bigdft_incs=''
lib_bigdft_libs=''
lib_dft_fcflags='  '
lib_dft_flavor='bigdft+libxc+wannier90'
lib_dft_incs='  '
lib_dft_ldflags='  '
lib_dft_libs='  '
lib_etsf_io_incs=''
lib_etsf_io_libs=''
lib_fft_fcflags=''
lib_fft_flavor='none'
lib_fft_incs=''
lib_fft_ldflags=''
lib_fft_libs=''
lib_fox_incs=''
lib_fox_libs=''
lib_gpu_fcflags=''
lib_gpu_flavor='none'
lib_gpu_incs=''
lib_gpu_ldflags=''
lib_gpu_libs=''
lib_libxc_incs=''
lib_libxc_libs=''
lib_linalg_fcflags=''
lib_linalg_flavor='netlib'
lib_linalg_incs=''
lib_linalg_ldflags=''
lib_linalg_libs='-lblas -llapack'
lib_math_fcflags=''
lib_math_flavor='none'
lib_math_incs=''
lib_math_ldflags=''
lib_math_libs=''
lib_mpi_fcflags=''
lib_mpi_incs=''
lib_mpi_ldflags=''
lib_mpi_libs=''
lib_netcdf_incs=''
lib_netcdf_libs=''
lib_timer_fcflags=''
lib_timer_flavor='none'
lib_timer_incs=''
lib_timer_ldflags=''
lib_timer_libs=''
lib_trio_fcflags='   '
lib_trio_flavor='fox+etsf'
lib_trio_incs='   '
lib_trio_ldflags='   '
lib_trio_libs='   '
lib_wannier90_incs=''
lib_wannier90_libs='-L$(abinit_builddir)/plugins/wannier90 -lwannier'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
libxc_pkg_name='libxc-svn-r6071-fixed'
libxc_pkg_string='LibXC library SVN revision 6071 (fixed for Abinit by YP)'
linalg_pkg_name='lapack-abinit_6.0'
linalg_pkg_string='The 3.2.1 Lapack library (dlamch.f hacked by XG)'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
netcdf_pkg_name='netcdf-3.6.3'
netcdf_pkg_string='NetCDF library 3.6.3 (upstream release)'
nightly_timeout='0'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/opt/abinit-6.3.1'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
src_01_gsl_ext_incs='-I$(top_builddir)/src/01_gsl_ext -I$(top_srcdir)/src/01_gsl_ext'
src_01_interfaces_ext_incs='-I$(top_builddir)/src/01_interfaces_ext -I$(top_srcdir)/src/01_interfaces_ext'
src_01_macroavnew_ext_incs='-I$(top_builddir)/src/01_macroavnew_ext -I$(top_srcdir)/src/01_macroavnew_ext'
src_01_qespresso_ext_incs='-I$(top_builddir)/src/01_qespresso_ext -I$(top_srcdir)/src/01_qespresso_ext'
src_02_clib_incs='-I$(top_builddir)/src/02_clib -I$(top_srcdir)/src/02_clib'
src_10_defs_incs='-I$(top_builddir)/src/10_defs -I$(top_srcdir)/src/10_defs'
src_12_hide_mpi_incs='-I$(top_builddir)/src/12_hide_mpi -I$(top_srcdir)/src/12_hide_mpi'
src_14_hidewrite_incs='-I$(top_builddir)/src/14_hidewrite -I$(top_srcdir)/src/14_hidewrite'
src_15_gpu_toolbox_incs='-I$(top_builddir)/src/15_gpu_toolbox -I$(top_srcdir)/src/15_gpu_toolbox'
src_16_hideleave_incs='-I$(top_builddir)/src/16_hideleave -I$(top_srcdir)/src/16_hideleave'
src_18_timing_incs='-I$(top_builddir)/src/18_timing -I$(top_srcdir)/src/18_timing'
src_27_toolbox_oop_incs='-I$(top_builddir)/src/27_toolbox_oop -I$(top_srcdir)/src/27_toolbox_oop'
src_28_numeric_noabirule_incs='-I$(top_builddir)/src/28_numeric_noabirule -I$(top_srcdir)/src/28_numeric_noabirule'
src_32_contract_incs='-I$(top_builddir)/src/32_contract -I$(top_srcdir)/src/32_contract'
src_32_util_incs='-I$(top_builddir)/src/32_util -I$(top_srcdir)/src/32_util'
src_42_geometry_incs='-I$(top_builddir)/src/42_geometry -I$(top_srcdir)/src/42_geometry'
src_42_geomoptim_incs='-I$(top_builddir)/src/42_geomoptim -I$(top_srcdir)/src/42_geomoptim'
src_42_nlstrain_incs='-I$(top_builddir)/src/42_nlstrain -I$(top_srcdir)/src/42_nlstrain'
src_42_parser_incs='-I$(top_builddir)/src/42_parser -I$(top_srcdir)/src/42_parser'
src_43_ptgroups_incs='-I$(top_builddir)/src/43_ptgroups -I$(top_srcdir)/src/43_ptgroups'
src_45_psp_parser_incs='-I$(top_builddir)/src/45_psp_parser -I$(top_srcdir)/src/45_psp_parser'
src_47_xml_incs='-I$(top_builddir)/src/47_xml -I$(top_srcdir)/src/47_xml'
src_49_gw_toolbox_oop_incs='-I$(top_builddir)/src/49_gw_toolbox_oop -I$(top_srcdir)/src/49_gw_toolbox_oop'
src_50_abitypes_defs_incs='-I$(top_builddir)/src/50_abitypes_defs -I$(top_srcdir)/src/50_abitypes_defs'
src_51_manage_cuda_incs='-I$(top_builddir)/src/51_manage_cuda -I$(top_srcdir)/src/51_manage_cuda'
src_51_manage_mpi_incs='-I$(top_builddir)/src/51_manage_mpi -I$(top_srcdir)/src/51_manage_mpi'
src_52_fft_mpi_noabirule_incs='-I$(top_builddir)/src/52_fft_mpi_noabirule -I$(top_srcdir)/src/52_fft_mpi_noabirule'
src_53_abiutil_incs='-I$(top_builddir)/src/53_abiutil -I$(top_srcdir)/src/53_abiutil'
src_53_ffts_incs='-I$(top_builddir)/src/53_ffts -I$(top_srcdir)/src/53_ffts'
src_53_spacepar_incs='-I$(top_builddir)/src/53_spacepar -I$(top_srcdir)/src/53_spacepar'
src_56_recipspace_incs='-I$(top_builddir)/src/56_recipspace -I$(top_srcdir)/src/56_recipspace'
src_56_xc_incs='-I$(top_builddir)/src/56_xc -I$(top_srcdir)/src/56_xc'
src_57_iovars_incs='-I$(top_builddir)/src/57_iovars -I$(top_srcdir)/src/57_iovars'
src_59_io_mpi_incs='-I$(top_builddir)/src/59_io_mpi -I$(top_srcdir)/src/59_io_mpi'
src_61_ionetcdf_incs='-I$(top_builddir)/src/61_ionetcdf -I$(top_srcdir)/src/61_ionetcdf'
src_62_cg_noabirule_incs='-I$(top_builddir)/src/62_cg_noabirule -I$(top_srcdir)/src/62_cg_noabirule'
src_62_iowfdenpot_incs='-I$(top_builddir)/src/62_iowfdenpot -I$(top_srcdir)/src/62_iowfdenpot'
src_62_occeig_incs='-I$(top_builddir)/src/62_occeig -I$(top_srcdir)/src/62_occeig'
src_62_poisson_incs='-I$(top_builddir)/src/62_poisson -I$(top_srcdir)/src/62_poisson'
src_62_wvl_wfs_incs='-I$(top_builddir)/src/62_wvl_wfs -I$(top_srcdir)/src/62_wvl_wfs'
src_63_bader_incs='-I$(top_builddir)/src/63_bader -I$(top_srcdir)/src/63_bader'
src_64_atompaw_incs='-I$(top_builddir)/src/64_atompaw -I$(top_srcdir)/src/64_atompaw'
src_65_nonlocal_incs='-I$(top_builddir)/src/65_nonlocal -I$(top_srcdir)/src/65_nonlocal'
src_65_psp_incs='-I$(top_builddir)/src/65_psp -I$(top_srcdir)/src/65_psp'
src_66_paw_incs='-I$(top_builddir)/src/66_paw -I$(top_srcdir)/src/66_paw'
src_66_wfs_incs='-I$(top_builddir)/src/66_wfs -I$(top_srcdir)/src/66_wfs'
src_67_common_incs='-I$(top_builddir)/src/67_common -I$(top_srcdir)/src/67_common'
src_68_dmft_incs='-I$(top_builddir)/src/68_dmft -I$(top_srcdir)/src/68_dmft'
src_68_gw_incs='-I$(top_builddir)/src/68_gw -I$(top_srcdir)/src/68_gw'
src_68_recursion_incs='-I$(top_builddir)/src/68_recursion -I$(top_srcdir)/src/68_recursion'
src_68_rsprc_incs='-I$(top_builddir)/src/68_rsprc -I$(top_srcdir)/src/68_rsprc'
src_69_bse_incs='-I$(top_builddir)/src/69_bse -I$(top_srcdir)/src/69_bse'
src_72_response_incs='-I$(top_builddir)/src/72_response -I$(top_srcdir)/src/72_response'
src_77_ddb_incs='-I$(top_builddir)/src/77_ddb -I$(top_srcdir)/src/77_ddb'
src_77_lwf_incs='-I$(top_builddir)/src/77_lwf -I$(top_srcdir)/src/77_lwf'
src_77_suscep_incs='-I$(top_builddir)/src/77_suscep -I$(top_srcdir)/src/77_suscep'
src_79_seqpar_mpi_incs='-I$(top_builddir)/src/79_seqpar_mpi -I$(top_srcdir)/src/79_seqpar_mpi'
src_83_cut3d_incs='-I$(top_builddir)/src/83_cut3d -I$(top_srcdir)/src/83_cut3d'
src_93_rdm_incs='-I$(top_builddir)/src/93_rdm -I$(top_srcdir)/src/93_rdm'
src_95_drive_incs='-I$(top_builddir)/src/95_drive -I$(top_srcdir)/src/95_drive'
src_incs_incs='-I$(top_builddir)/src/incs -I$(top_srcdir)/src/incs'
src_mods_incs='-I$(top_builddir)/src/mods -I$(top_srcdir)/src/mods'
sysconfdir='${prefix}/etc'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'
wannier90_pkg_name='wannier90-1.2'
wannier90_pkg_string='Wannier90 program 1.2 (upstream release)'
with_bigdft_includes=''
with_bigdft_libs=''
with_config_file='/home/jzwanzig/code/build/6.5.0.ac'
with_dft_flavor='bigdft+libxc+wannier90'
with_dft_includes=''
with_dft_libs=''
with_etsf_io_includes=''
with_etsf_io_libs=''
with_fc_vendor=''
with_fc_version=''
with_fft_flavor='fftw3'
with_fft_includes=''
with_fft_libs=''
with_fox_includes=''
with_fox_libs=''
with_gnu_ld=''
with_gpu_cflags=''
with_gpu_cppflags=''
with_gpu_flavor='cuda-single'
with_gpu_includes=''
with_gpu_ldflags=''
with_gpu_libs=''
with_gpu_prefix=''
with_libxc_includes=''
with_libxc_libs=''
with_linalg_flavor='netlib'
with_linalg_includes=''
with_linalg_libs='-lblas -llapack'
with_math_flavor='gsl'
with_math_includes=''
with_math_libs=''
with_mpi_includes=''
with_mpi_level=''
with_mpi_libs=''
with_mpi_prefix='/usr/local/openmpi/1.4.2/gcc'
with_netcdf_includes=''
with_netcdf_libs=''
with_plugins_prefix=''
with_plugins_tardir=''
with_test_timeout='0'
with_timer_flavor='abinit'
with_timer_includes=''
with_timer_libs=''
with_trio_flavor='fox+etsf'
with_trio_includes=''
with_trio_libs=''
with_wannier90=''
with_wannier90_includes=''
with_wannier90_libs=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "ABINIT"
#define PACKAGE_TARNAME "abinit"
#define PACKAGE_VERSION "6.5.0"
#define PACKAGE_STRING "ABINIT 6.5.0"
#define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
#define PACKAGE_URL ""
#define PACKAGE "abinit"
#define VERSION "6.5.0"
#define ABINIT_VERSION "6.5.0"
#define ABINIT_VERSION_MAJOR "6"
#define ABINIT_VERSION_MINOR "5"
#define ABINIT_VERSION_MICRO "0"
#define ABINIT_VERSION_BUILD "20100907"
#define ABINIT_VERSION_BASE "6.5"
#define HAVE_OS_LINUX 1
#define CC_GNU 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define CXX_GNU 1
#define FC_GNU 1
#define HAVE_FORTRAN2003 1
#define FC_FUNC(name,NAME) name ## _
#define FC_FUNC_(name,NAME) name ## _
#define HAVE_BZR_BRANCH 1
#define ABINIT_TARGET "x86_64_linux_gnu4.4"
#define HAVE_STDDEF_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDIO_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MATH_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_ERRNO_H 1
#define HAVE_MCHECK_H 1
#define HAVE_ABORT 1
#define SIZEOF_CHAR 1
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define SIZEOF_SIZE_T 8
#define SIZEOF_PTRDIFF_T 8
#define HAVE_FC_ISO_C_BINDING 1
#define HAVE_FC_EXIT 1
#define HAVE_FC_FLUSH 1
#define HAVE_FC_GAMMA 1
#define HAVE_FC_GETENV 1
#define HAVE_FC_NULL 1
#define HAVE_FC_INT_QUAD 1
#define HAVE_MPI 1
#define HAVE_MPI2 1
#define HAVE_LINALG_NETLIB 1
#define HAVE_LINALG 1
#define HAVE_LINALG_SERIAL 1
#define HAVE_WANNIER90 1
#define USE_MACROAVE 1

configure: exit 0
