This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by AtomPAW configure 3.0.1.9, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = ubuntu
uname -m = i686
uname -r = 3.2.0-29-generic-pae
uname -s = Linux
uname -v = #46-Ubuntu SMP Fri Jul 27 17:25:43 UTC 2012

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/ahmed/Downloads/XCrySDen-1.5.24-src-all
PATH: /usr/lib/lightdm/lightdm
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /home/ahmed/Downloads/XCrySDen-1.5.24-src-all/scripts
PATH: /home/ahmed/Downloads/XCrySDen-1.5.24-src-all/util


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2279: regenerating the VERSION file
configure:2327: checking build system type
configure:2341: result: i686-pc-linux-gnu
configure:2361: checking host system type
configure:2374: result: i686-pc-linux-gnu
configure:2394: checking target system type
configure:2407: result: i686-pc-linux-gnu
configure:2449: checking for a BSD-compatible install
configure:2517: result: /usr/bin/install -c
configure:2528: checking whether build environment is sane
configure:2583: result: yes
configure:2734: checking for a thread-safe mkdir -p
configure:2773: result: /bin/mkdir -p
configure:2780: checking for gawk
configure:2810: result: no
configure:2780: checking for mawk
configure:2796: found /usr/bin/mawk
configure:2807: result: mawk
configure:2818: checking whether make sets $(MAKE)
configure:2840: result: yes
configure:2990: setting linear algebra flavor to 'netlib'
configure:2997: checking whether make sets $(MAKE)
configure:3019: result: yes
configure:3029: checking whether ln -s works
configure:3033: result: yes
configure:3040: checking for a sed that does not truncate output
configure:3104: result: /bin/sed
configure:3113: checking for gawk
configure:3140: result: mawk
configure:3151: checking for grep that handles long lines and -e
configure:3209: result: /bin/grep
configure:3216: checking for egrep
configure:3278: result: /bin/grep -E
configure:3335: checking for dvipdf
configure:3351: found /usr/bin/dvipdf
configure:3362: result: dvipdf
configure:3377: checking for latex
configure:3407: result: no
configure:3419: checking for pdflatex
configure:3449: result: no
configure:3461: checking for perl
configure:3477: found /usr/bin/perl
configure:3488: result: perl
configure:3608: checking for gfortran
configure:3624: found /usr/bin/gfortran
configure:3635: result: gfortran
configure:3661: checking for Fortran compiler version
configure:3670: gfortran --version >&5
GNU Fortran (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

configure:3681: $? = 0
configure:3670: gfortran -v >&5
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
configure:3681: $? = 0
configure:3670: gfortran -V >&5
gfortran: error: unrecognized option '-V'
gfortran: fatal error: no input files
compilation terminated.
configure:3681: $? = 4
configure:3670: gfortran -qversion >&5
gfortran: error: unrecognized option '-qversion'
gfortran: fatal error: no input files
compilation terminated.
configure:3681: $? = 4
configure:3696: checking whether the Fortran compiler works
configure:3718: gfortran    conftest.f  >&5
configure:3722: $? = 0
configure:3770: result: yes
configure:3773: checking for Fortran compiler default output file name
configure:3775: result: a.out
configure:3781: checking for suffix of executables
configure:3788: gfortran -o conftest    conftest.f  >&5
configure:3792: $? = 0
configure:3814: result: 
configure:3830: checking whether we are cross compiling
configure:3838: gfortran -o conftest    conftest.f  >&5
configure:3842: $? = 0
configure:3849: ./conftest
configure:3853: $? = 0
configure:3868: result: no
configure:3873: checking for suffix of object files
configure:3889: gfortran -c   conftest.f >&5
configure:3893: $? = 0
configure:3914: result: o
configure:3922: checking whether we are using the GNU Fortran compiler
configure:3935: gfortran -c   conftest.F >&5
configure:3935: $? = 0
configure:3944: result: yes
configure:3950: checking whether gfortran accepts -g
configure:3961: gfortran -c -g  conftest.f >&5
configure:3961: $? = 0
configure:3969: result: yes
configure:4019: checking which type of Fortran compiler we have
configure:4379: result: gnu 4.6
configure:4391: checking fortran 90 modules extension
configure:4418: gfortran -c -g -O2  conftest.f >&5
configure:4418: $? = 0
configure:4441: result: mod
configure:4456: checking for Fortran flag to compile .F90 files
configure:4476: gfortran -c -g -O2  conftest.F90 >&5
configure:4476: $? = 0
configure:4485: result: none
configure:4521: determining Fortran module case
configure:4535: gfortran -c -g -O2  conftest.F90 >&5
configure:4535: $? = 0
configure:4559: checking whether Fortran modules are upper-case
configure:4561: result: no
configure:4721: checking how to print strings
configure:4748: result: printf
configure:4781: checking for style of include used by make
configure:4809: result: GNU
configure:4880: checking for gcc
configure:4896: found /usr/bin/gcc
configure:4907: result: gcc
configure:5136: checking for C compiler version
configure:5145: gcc --version >&5
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:5156: $? = 0
configure:5145: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
configure:5156: $? = 0
configure:5145: gcc -V >&5
gcc: error: unrecognized option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:5156: $? = 4
configure:5145: gcc -qversion >&5
gcc: error: unrecognized option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:5156: $? = 4
configure:5160: checking whether we are using the GNU C compiler
configure:5179: gcc -c   conftest.c >&5
configure:5179: $? = 0
configure:5188: result: yes
configure:5197: checking whether gcc accepts -g
configure:5217: gcc -c -g  conftest.c >&5
configure:5217: $? = 0
configure:5258: result: yes
configure:5275: checking for gcc option to accept ISO C89
configure:5338: gcc  -c -g -O2  conftest.c >&5
configure:5338: $? = 0
configure:5351: result: none needed
configure:5373: checking dependency style of gcc
configure:5484: result: none
configure:5499: checking for a sed that does not truncate output
configure:5563: result: /bin/sed
configure:5581: checking for fgrep
configure:5643: result: /bin/grep -F
configure:5678: checking for ld used by gcc
configure:5745: result: /usr/bin/ld
configure:5752: checking if the linker (/usr/bin/ld) is GNU ld
configure:5767: result: yes
configure:5779: checking for BSD- or MS-compatible name lister (nm)
configure:5828: result: /usr/bin/nm -B
configure:5958: checking the name lister (/usr/bin/nm -B) interface
configure:5965: gcc -c -g -O2  conftest.c >&5
configure:5968: /usr/bin/nm -B "conftest.o"
configure:5971: output
00000000 B some_variable
configure:5978: result: BSD nm
configure:5982: checking the maximum length of command line arguments
configure:6112: result: 1572864
configure:6129: checking whether the shell understands some XSI constructs
configure:6139: result: yes
configure:6143: checking whether the shell understands "+="
configure:6149: result: yes
configure:6184: checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format
configure:6224: result: func_convert_file_noop
configure:6231: checking how to convert i686-pc-linux-gnu file names to toolchain format
configure:6251: result: func_convert_file_noop
configure:6258: checking for /usr/bin/ld option to reload object files
configure:6265: result: -r
configure:6339: checking for objdump
configure:6355: found /usr/bin/objdump
configure:6366: result: objdump
configure:6398: checking how to recognize dependent libraries
configure:6600: result: pass_all
configure:6685: checking for dlltool
configure:6715: result: no
configure:6745: checking how to associate runtime and link libraries
configure:6772: result: printf %s\n
configure:6833: checking for ar
configure:6849: found /usr/bin/ar
configure:6860: result: ar
configure:6897: checking for archiver @FILE support
configure:6914: gcc -c -g -O2  conftest.c >&5
configure:6914: $? = 0
configure:6917: ar cru libconftest.a @conftest.lst >&5
configure:6920: $? = 0
configure:6925: ar cru libconftest.a @conftest.lst >&5
ar: conftest.o: No such file or directory
configure:6928: $? = 1
configure:6940: result: @
configure:6998: checking for strip
configure:7014: found /usr/bin/strip
configure:7025: result: strip
configure:7097: checking for ranlib
configure:7113: found /usr/bin/ranlib
configure:7124: result: ranlib
configure:7226: checking command to parse /usr/bin/nm -B output from gcc object
configure:7346: gcc -c -g -O2  conftest.c >&5
configure:7349: $? = 0
configure:7353: /usr/bin/nm -B conftest.o \| sed -n -e 's/^.*[ ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[ ][ ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' | sed '/ __gnu_lto/d' \> conftest.nm
configure:7356: $? = 0
configure:7422: gcc -o conftest -g -O2   conftest.c conftstm.o >&5
configure:7425: $? = 0
configure:7463: result: ok
configure:7500: checking for sysroot
configure:7530: result: no
configure:7786: checking for mt
configure:7802: found /bin/mt
configure:7813: result: mt
configure:7836: checking if mt is a manifest tool
configure:7842: mt '-?'
configure:7850: result: no
configure:8492: checking how to run the C preprocessor
configure:8523: gcc -E  conftest.c
configure:8523: $? = 0
configure:8537: gcc -E  conftest.c
conftest.c:13:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:8537: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "AtomPAW"
| #define PACKAGE_TARNAME "atompaw"
| #define PACKAGE_VERSION "3.0.1.9"
| #define PACKAGE_STRING "AtomPAW 3.0.1.9"
| #define PACKAGE_BUGREPORT "natalie@wfu.edu, marc.torrent@cea.fr"
| #define PACKAGE_URL ""
| #define PACKAGE "atompaw"
| #define VERSION "3.0.1.9"
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:8562: result: gcc -E
configure:8582: gcc -E  conftest.c
configure:8582: $? = 0
configure:8596: gcc -E  conftest.c
conftest.c:13:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:8596: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "AtomPAW"
| #define PACKAGE_TARNAME "atompaw"
| #define PACKAGE_VERSION "3.0.1.9"
| #define PACKAGE_STRING "AtomPAW 3.0.1.9"
| #define PACKAGE_BUGREPORT "natalie@wfu.edu, marc.torrent@cea.fr"
| #define PACKAGE_URL ""
| #define PACKAGE "atompaw"
| #define VERSION "3.0.1.9"
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:8625: checking for ANSI C header files
configure:8645: gcc -c -g -O2  conftest.c >&5
configure:8645: $? = 0
configure:8718: gcc -o conftest -g -O2   conftest.c  >&5
configure:8718: $? = 0
configure:8718: ./conftest
configure:8718: $? = 0
configure:8729: result: yes
configure:8742: checking for sys/types.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for sys/stat.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for stdlib.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for string.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for memory.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for strings.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for inttypes.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for stdint.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8742: checking for unistd.h
configure:8742: gcc -c -g -O2  conftest.c >&5
configure:8742: $? = 0
configure:8742: result: yes
configure:8756: checking for dlfcn.h
configure:8756: gcc -c -g -O2  conftest.c >&5
configure:8756: $? = 0
configure:8756: result: yes
configure:8972: checking for objdir
configure:8987: result: .libs
configure:9258: checking if gcc supports -fno-rtti -fno-exceptions
configure:9276: gcc -c -g -O2  -fno-rtti -fno-exceptions conftest.c >&5
cc1: warning: command line option '-fno-rtti' is valid for C++/ObjC++ but not for C [enabled by default]
configure:9280: $? = 0
configure:9293: result: no
configure:9620: checking for gcc option to produce PIC
configure:9627: result: -fPIC -DPIC
configure:9635: checking if gcc PIC flag -fPIC -DPIC works
configure:9653: gcc -c -g -O2  -fPIC -DPIC -DPIC conftest.c >&5
configure:9657: $? = 0
configure:9670: result: yes
configure:9699: checking if gcc static flag -static works
configure:9727: result: yes
configure:9742: checking if gcc supports -c -o file.o
configure:9763: gcc -c -g -O2  -o out/conftest2.o conftest.c >&5
configure:9767: $? = 0
configure:9789: result: yes
configure:9797: checking if gcc supports -c -o file.o
configure:9844: result: yes
configure:9877: checking whether the gcc linker (/usr/bin/ld) supports shared libraries
configure:11030: result: yes
configure:11067: checking whether -lc should be explicitly linked in
configure:11075: gcc -c -g -O2  conftest.c >&5
configure:11078: $? = 0
configure:11093: gcc -shared  -fPIC -DPIC conftest.o  -v -Wl,-soname -Wl,conftest -o conftest 2\>\&1 \| /bin/grep  -lc  \>/dev/null 2\>\&1
configure:11096: $? = 0
configure:11110: result: no
configure:11270: checking dynamic linker characteristics
configure:11781: gcc -o conftest -g -O2   -Wl,-rpath -Wl,/foo conftest.c  >&5
configure:11781: $? = 0
configure:12003: result: GNU/Linux ld.so
configure:12110: checking how to hardcode library paths into programs
configure:12135: result: immediate
configure:12675: checking whether stripping libraries is possible
configure:12680: result: yes
configure:12715: checking if libtool supports shared libraries
configure:12717: result: yes
configure:12720: checking whether to build shared libraries
configure:12741: result: yes
configure:12744: checking whether to build static libraries
configure:12748: result: yes
configure:12877: checking if libtool supports shared libraries
configure:12879: result: yes
configure:12882: checking whether to build shared libraries
configure:12902: result: yes
configure:12905: checking whether to build static libraries
configure:12909: result: yes
configure:12943: gfortran -c -g -O2  conftest.F90 >&5
configure:12946: $? = 0
configure:13393: checking for gfortran option to produce PIC
configure:13400: result: -fPIC
configure:13408: checking if gfortran PIC flag -fPIC works
configure:13426: gfortran -c -g -O2 -fPIC  conftest.F90 >&5
configure:13430: $? = 0
configure:13443: result: yes
configure:13466: checking if gfortran static flag -static works
configure:13494: result: yes
configure:13506: checking if gfortran supports -c -o file.o
configure:13527: gfortran -c -g -O2 -o out/conftest2.o  conftest.F90 >&5
configure:13531: $? = 0
configure:13553: result: yes
configure:13558: checking if gfortran supports -c -o file.o
configure:13605: result: yes
configure:13635: checking whether the gfortran linker (/usr/bin/ld) supports shared libraries
configure:14738: result: yes
configure:14879: checking dynamic linker characteristics
configure:15540: result: GNU/Linux ld.so
configure:15593: checking how to hardcode library paths into programs
configure:15618: result: immediate
configure:15745: checking whether linear algebra libraries work
configure:15755: gfortran -o conftest -g -O2 -O2  conftest.F90 -llapack -lblas  >&5
configure:15755: $? = 0
configure:15762: result: yes
configure:15934: FC       = gfortran
configure:15936: CPPFLAGS = 
configure:15938: FCFLAGS  = -g -O2
configure:15940: LDFLAGS  = -O2
configure:15942: LIBS     = -llapack -lblas 
configure:16056: checking that generated files are newer than configure
configure:16062: result: done
configure:16085: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by AtomPAW config.status 3.0.1.9, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on ubuntu

config.status:1161: creating Makefile
config.status:1161: creating src/Makefile
config.status:1161: creating src/pkginfo.f90
config.status:1161: creating config.h
config.status:1342: config.h is unchanged
config.status:1390: executing depfiles commands
config.status:1390: executing libtool commands

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=i686-pc-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_env_ATOMPAW_LIBDIR_set=
ac_cv_env_ATOMPAW_LIBDIR_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_FCFLAGS_set=
ac_cv_env_FCFLAGS_value=
ac_cv_env_FC_set=
ac_cv_env_FC_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_fc_compiler_gnu=yes
ac_cv_fc_srcext_F90=none
ac_cv_header_dlfcn_h=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_unistd_h=yes
ac_cv_host=i686-pc-linux-gnu
ac_cv_objext=o
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_FGREP='/bin/grep -F'
ac_cv_path_GREP=/bin/grep
ac_cv_path_SED=/bin/sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=mawk
ac_cv_prog_CPP='gcc -E'
ac_cv_prog_DVIPDF=dvipdf
ac_cv_prog_PERL=perl
ac_cv_prog_ac_ct_AR=ar
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_FC=gfortran
ac_cv_prog_ac_ct_MANIFEST_TOOL=mt
ac_cv_prog_ac_ct_OBJDUMP=objdump
ac_cv_prog_ac_ct_RANLIB=ranlib
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_fc_g=yes
ac_cv_prog_make_make_set=yes
ac_cv_target=i686-pc-linux-gnu
am_cv_CC_dependencies_compiler_type=none
ax_cv_f90_modext=mod
lt_cv_ar_at_file=@
lt_cv_archive_cmds_need_lc=no
lt_cv_deplibs_check_method=pass_all
lt_cv_file_magic_cmd='$MAGIC_CMD'
lt_cv_file_magic_test_file=
lt_cv_ld_reload_flag=-r
lt_cv_nm_interface='BSD nm'
lt_cv_objdir=.libs
lt_cv_path_LD=/usr/bin/ld
lt_cv_path_NM='/usr/bin/nm -B'
lt_cv_path_mainfest_tool=no
lt_cv_prog_compiler_c_o=yes
lt_cv_prog_compiler_c_o_FC=yes
lt_cv_prog_compiler_pic='-fPIC -DPIC'
lt_cv_prog_compiler_pic_FC=-fPIC
lt_cv_prog_compiler_pic_works=yes
lt_cv_prog_compiler_pic_works_FC=yes
lt_cv_prog_compiler_rtti_exceptions=no
lt_cv_prog_compiler_static_works=yes
lt_cv_prog_compiler_static_works_FC=yes
lt_cv_prog_gnu_ld=yes
lt_cv_sharedlib_from_linklib_cmd='printf %s\n'
lt_cv_shlibpath_overrides_runpath=no
lt_cv_sys_global_symbol_pipe='sed -n -e '\''s/^.*[	 ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[	 ][	 ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p'\'' | sed '\''/ __gnu_lto/d'\'''
lt_cv_sys_global_symbol_to_c_name_address='sed -n -e '\''s/^: \([^ ]*\)[ ]*$/  {\"\1\", (void *) 0},/p'\'' -e '\''s/^[ABCDGIRSTW]* \([^ ]*\) \([^ ]*\)$/  {"\2", (void *) \&\2},/p'\'''
lt_cv_sys_global_symbol_to_c_name_address_lib_prefix='sed -n -e '\''s/^: \([^ ]*\)[ ]*$/  {\"\1\", (void *) 0},/p'\'' -e '\''s/^[ABCDGIRSTW]* \([^ ]*\) \(lib[^ ]*\)$/  {"\2", (void *) \&\2},/p'\'' -e '\''s/^[ABCDGIRSTW]* \([^ ]*\) \([^ ]*\)$/  {"lib\2", (void *) \&\2},/p'\'''
lt_cv_sys_global_symbol_to_cdecl='sed -n -e '\''s/^T .* \(.*\)$/extern int \1();/p'\'' -e '\''s/^[ABCDGIRSTW]* .* \(.*\)$/extern char \1;/p'\'''
lt_cv_sys_max_cmd_len=1572864
lt_cv_to_host_file_cmd=func_convert_file_noop
lt_cv_to_tool_file_cmd=func_convert_file_noop

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/ahmed/Downloads/atompaw-3.0.1.9/config/gnu/missing --run aclocal-1.12'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AR='ar'
ATOMPAW_LIBDIR=''
ATP_FCOPTS='-O2'
ATP_LDOPTS='-O2'
ATP_LIBS='-llapack -lblas'
AUTOCONF='${SHELL} /home/ahmed/Downloads/atompaw-3.0.1.9/config/gnu/missing --run autoconf'
AUTOHEADER='${SHELL} /home/ahmed/Downloads/atompaw-3.0.1.9/config/gnu/missing --run autoheader'
AUTOMAKE='${SHELL} /home/ahmed/Downloads/atompaw-3.0.1.9/config/gnu/missing --run automake-1.12'
AWK='mawk'
CC='gcc'
CCDEPMODE='depmode=none'
CFLAGS='-g -O2'
CPP='gcc -E'
CPPFLAGS=''
CYGPATH_W='echo'
DEFS='-DHAVE_CONFIG_H'
DEPDIR='.deps'
DLLTOOL='false'
DSYMUTIL=''
DUMPBIN=''
DVIPDF='dvipdf'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
EXEEXT=''
FC='gfortran'
FCFLAGS='-g -O2'
FCFLAGS_F90=''
FGREP='/bin/grep -F'
GREP='/bin/grep'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LATEX=''
LD='/usr/bin/ld'
LDFLAGS='-O2'
LIBOBJS=''
LIBS='-llapack -lblas '
LIBTOOL='$(SHELL) $(top_builddir)/libtool'
LIPO=''
LN_S='ln -s'
LTLIBOBJS=''
LTOBJEXT='lo'
MAKEINFO='${SHELL} /home/ahmed/Downloads/atompaw-3.0.1.9/config/gnu/missing --run makeinfo'
MANIFEST_TOOL=':'
MKDIR_P='/bin/mkdir -p'
MODEXT='mod'
NM='/usr/bin/nm -B'
NMEDIT=''
OBJDUMP='objdump'
OBJEXT='o'
OTOOL64=''
OTOOL=''
PACKAGE='atompaw'
PACKAGE_BUGREPORT='natalie@wfu.edu, marc.torrent@cea.fr'
PACKAGE_NAME='AtomPAW'
PACKAGE_STRING='AtomPAW 3.0.1.9'
PACKAGE_TARNAME='atompaw'
PACKAGE_URL=''
PACKAGE_VERSION='3.0.1.9'
PATH_SEPARATOR=':'
PDFLATEX=''
PERL='perl'
RANLIB='ranlib'
SED='/bin/sed'
SET_MAKE=''
SHELL='/bin/bash'
STRIP='strip'
VERSION='3.0.1.9'
ac_ct_AR='ar'
ac_ct_CC='gcc'
ac_ct_DUMPBIN=''
ac_ct_FC='gfortran'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE='#'
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE='#'
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
atp_fc_path=''
atp_fc_vendor='gnu'
atp_fc_version='4.6'
atp_fc_wrap='no'
bindir='${exec_prefix}/bin'
build='i686-pc-linux-gnu'
build_alias=''
build_cpu='i686'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='${prefix}'
host='i686-pc-linux-gnu'
host_alias=''
host_cpu='i686'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/ahmed/Downloads/atompaw-3.0.1.9/config/gnu/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='i686-pc-linux-gnu'
target_alias=''
target_cpu='i686'
target_os='linux-gnu'
target_vendor='pc'

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "AtomPAW"
#define PACKAGE_TARNAME "atompaw"
#define PACKAGE_VERSION "3.0.1.9"
#define PACKAGE_STRING "AtomPAW 3.0.1.9"
#define PACKAGE_BUGREPORT "natalie@wfu.edu, marc.torrent@cea.fr"
#define PACKAGE_URL ""
#define PACKAGE "atompaw"
#define VERSION "3.0.1.9"
#define FC_GNU 1
#define HAVE_FORTRAN2003 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"

configure: exit 0
