  autoparal=1
  #paral_kgb = 1 
# 2-Options for output:
# ---------------------
  ndtset 2
  enunit 2  #print eigenvalues in both hartree and eV.
  prtvol 0  #Control the volume of printed output. 
#  prtdos 2
  prtden 0  # provide output of electron density
  prtwf 1   #provide output of wavefunction and eigenvalue file
  prtnabla 1 #If set to 1, calculate the matrix elements <Psi_n|-inabla|Psi_m> and write it in file _OPT to be read by the code conducti

# 3-Parameters governing the convergence:
# ---------------------------------------
  ecut 20. #specified in Ha (the default)
  pawecutdg 60. #Define the energy cut-off for the fine FFT grid, ecut is on the order of 15 Ha,pawecutdg should be on the order of 40 Ha. Choosing a larger value should not increase the accuracy, but does not slow down the computation either, only the memory.
  pawmixdg 1 #If pawmixdg=1 the density/potential is mixed in REAL space using the fine FFT grid
  pawovlp =-1 #spheres OVerLap allowed (in percentage)  pawovlp<0. : overlap is always allowed
  nband 480 #${band[$j]} #Number of BANDs
  nstep 500 #Number of (non-)self-consistent field STEPS 
  nline 4 #Gives maximum number of line minimizations allowed in preconditioned conjugate gradient minimization for each band. The Default, 4, is fine
  toldfe 1.d-5 #TOLerance on the DiFference of total Energy in Ha

# 4-Options for the choice of calculation:
# ----------------------------------------
  ixc1 -101130
  getwfk2   1
  ixc2 -428 # 7 LDA PW92 #11 GGA-PBE -428 HSE06
  nnsclohf 3 #Number of Non-Self Consistent LOops for (Hartree)-Fock exact exchange
  nsppol 1 #If nsppol=1, one has an unpolarized calculation
  iscf 17 # Integer for Self-Consistent-Field cycles 17 (PAW) 
  occopt 3 #Fermi-Dirac smearing (finite-temperature metal) Smeared delta function : 0.25d0/(cosh(xx/2.0d0)**2)
  tsmear 20000 K #If occopt=3, tsmear is the physical temperature, as the broadening is based on Fermi-Dirac statistics
  ionmov 0 #0=> do not move ions;
  optcell 0 #OPTimize the CELL shape and dimensions Characteristic,modify nuclear positions, since ionmov=2, but no cell shape and dimension optimisation

# 5-Definition of special K-points:
# ---------------------------------
#  kptopt 0 #KPoinTs OPTion,0=> read directly nkpt, kpt, kptnrm and wtk.
#   nkpt 1 #Number of K - Points 
#   kpt 0. 0. 0.  # K - PoinTs 
#   wtk  1.0 #WeighTs for K points 
    ngkpt 2 2 2 #Number of Grid points for K PoinTs generation
    kptopt 1 #rely on ngkpt or kptrlatt, as well as on nshiftk and shiftk to set up the k points
    kptnrm 1 # K - PoinTs NoRMalization 
    nshiftk 4 #Number of SHIFTs for K point grids 
    shiftk 0.5 0.5 0.5 #the (very efficient) usual Monkhorst-Pack sampling will be generated by using nshiftk= 4 and shiftk
         0.5 0.0 0.0
          0.0 0.5 0.0
          0.0 0.0 0.5
    istwfk *0 #Integer for choice of STorage of WaveFunction at each k point 

# 6-Symmetries of the lattice:
# ----------------------------
  nsym 1 #If there is no symmetry in the problem then set nsym to 1
  chkprim 0 #CHecK whether the cell is PRIMitive,If chkprim=0, a warning is issued, but the run does not stop.

# 7-Definition of the unit cell:
# ------------------------------
  amu 14.007 #Atomic Mass Units 
  znucl 7 #In the pseudopotential files, znucl is called "zatom".
  acell    9.4253806    9.4253806    9.4253806 angstrom #CELL lattice vector scaling Default is 3*1 (in Bohr). 1.50g/cm^3, 20000 K 8000 step
  rprim 1.0 0.0 0.0 #Real space PRIMitive translations 
        0.0 1.0 0.0
        0.0 0.0 1.0
  natom 54 #Number of ATOMs 
  ntypat 1  #Number of TYPEs of atoms 
  typat 54*1 #TYPE of atoms, BaTiO3  typat 1 2 3 3 3
   xred
   0.34203228  0.78982466  0.55018572
   0.63994065  0.06863553  0.43398494
   0.35482231  0.36589761  0.43925149
   0.33067018  0.43650116  0.32439100
   0.58098977  0.47474998  0.10483850
   0.59737164  0.61154540  0.32795093
   0.18461984  0.12040782  0.39386177
   0.06954679  0.48702575  0.08736018
   0.48339263  0.78923426  0.29522373
   0.64872887  0.69136267  0.15141900
   0.30185564  0.68665622  0.08710038
   0.57495847  0.20141144  0.38725256
   0.64443751  0.96099853  0.40572931
   0.84649857  0.53949161  0.65203603
   0.98790461  0.53035150  0.76198884
   0.54722778  0.89068466  0.97999160
   0.92776003  0.60679799  0.07989627
   0.60336150  0.14691114  0.26387144
   0.14983028  0.74479397  0.74989495
   0.89434941  0.95585116  0.02581488
   0.78617306  0.62743672  0.81786930
   0.11541802  0.34973737  0.77103342
   0.45760859  0.51062463  0.86541137
   0.02914222  0.43601923  0.87479146
   0.91119459  0.18331937  0.94193521
   0.96678457  0.26567883  0.48935266
   0.38470726  0.70047096  0.25158477
   0.55317745  0.87003407  0.59326268
   0.42805379  0.42192229  0.12928194
   0.62407824  0.34608600  0.53498392
   0.86268524  0.16967567  0.35556455
   0.18171251  0.10640356  0.10059253
   0.33178835  0.95692436  0.98925428
   0.88364037  0.83316014  0.81370868
   0.07305174  0.35529027  0.64035043
   0.49706558  0.81202027  0.84138956
   0.03930051  0.84723248  0.82947472
   0.23445251  0.23504873  0.73379604
   0.19191608  0.11944700  0.23301347
   0.24933157  0.87645517  0.79036307
   0.32093854  0.64427213  0.60870298
   0.22420505  0.79389340  0.16381207
   0.36332575  0.08563893  0.92715886
   0.11808259  0.22077514  0.93672466
   0.40266697  0.30231809  0.77424802
   0.46654798  0.86564841  0.45044503
   0.66542047  0.27014590  0.72541402
   0.09580681  0.57506602  0.22559794
   0.49046309  0.50480536  0.33620580
   0.70156022  0.72610218  0.91454483
   0.68295061  0.27063016  0.99538416
   0.59871304  0.20717189  0.55633780
   0.11429820  0.65409974  0.32485659
   0.24343966  0.75731250  0.96150966
