############################################################################################
# The Calcualtion for the bulk NiO properties, such as lattice constant and B
# created by abinp.py; abinp.py gs NiO_cf8_POSCAR.vasp --usepaw -p ../JTH-PBE-atomicdata-1.1
# /ATOMICDATA/Ni.GGA_PBE-JTH.xml ../JTH-PBE-atomicdata-1.1/ATOMICDATA/O.GGA_PBE-JTH.xml > Ni
# Obulk.in
############################################################################################
 optcell 1
 ionmov 2
 ntime 20
 dilatmx 1.05
 ecutsm 0.5
 diemix 0.5
 diemixmag 0.3
 nline 10

############################################################################################
#                                       SECTION: output DOS KPoint                                      
############################################################################################
 prtdos 1
 prtden 0
 prtwf  0
 prtvol 0

############################################################################################
#                                       SECTION: spin                                      
############################################################################################
spinat 
  0.0  0.0  3.7
  0.0  0.0 -3.7
  0.0  0.0  3.7
  0.0  0.0 -3.7
  0.0  0.0  3.7
  0.0  0.0 -3.7
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
nsppol 1
nspden 4
pawspnorb 1

############################################################################################
# for DFT+U
############################################################################################
usepawu 1
lpawu 2 -1
upawu 4.0 0.0 eV
jpawu 0.0 0.0 eV


############################################################################################
#                                       SECTION: basic                                      
############################################################################################
 ecut 18.0
 ngkpt 4 4 4
 shiftk    0.5    0.5    0.5
 nshiftk 1
 kptopt 4
 nband 142
 occopt 3
 tolvrs 1e-08
 nstep 100
 nsym 1

############################################################################################
#                                      SECTION: gstate                                      
############################################################################################
 chksymbreak 0
 chkprim 0
 charge 0.0
 tsmear 0.003674932248 Ha
############################################################################################
#                                        SECTION: paw                                       
############################################################################################
 pawecutdg 36.0
############################################################################################
#                                         STRUCTURE                                         
############################################################################################
 natom 12
 ntypat 2
 typat
 1 1 1 1 1 1
 2 2 2 2 2 2
 znucl 26 8
 xred
    0.0000000000    0.0000000000    0.0000000000
    0.3333333333    0.3333333333    0.1666666667
    0.6666666667    0.6666666667    0.3333333333
    0.0000000000    0.0000000000    0.5000000000
    0.3333333333    0.3333333333    0.6666666667
    0.6666666667    0.6666666667    0.8333333333    
    0.0000000000    0.0000000000    0.2500000000
    0.6666666667    0.6666666667    0.0833333333
    0.3333333333    0.3333333333    0.4166666667
    0.0000000000    0.0000000000    0.7500000000
    0.6666666667    0.6666666667    0.5833333333
    0.3333333333    0.3333333333    0.9166666667

 acell    3*8.1857849493

 rprim
    0.5000000000    0.0000000000   -0.5000000000
    0.0000000000    0.5000000000   -0.5000000000
    2.0000000000    2.0000000000    2.0000000000


#<JSON>
#{
#    "pseudos": [
#        {
#            "basename": "O.GGA_PBE-JTH.xml",
#            "type": "PawXmlSetup",
#            "symbol": "O",
#            "Z": 8,
#            "Z_val": 6.0,
#            "l_max": null,
#            "md5": "49c9b2c1172cd84f39db3d053a34c103",
#            "filepath": "/home/tongke/Research/JTH-PBE-atomicdata-1.1/ATOMICDATA/O.GGA_PBE-JTH.xml",
#            "@module": "pymatgen.io.abinit.pseudos",
#            "@class": "PawXmlSetup"
#        },
#        {
#            "basename": "Ni.GGA_PBE-JTH.xml",
#            "type": "PawXmlSetup",
#            "symbol": "Ni",
#            "Z": 28,
#            "Z_val": 18.0,
#            "l_max": null,
#            "md5": "aa0f24e8bb8c4bbd6493bf531333560e",
#            "filepath": "/home/tongke/Research/JTH-PBE-atomicdata-1.1/ATOMICDATA/Ni.GGA_PBE-JTH.xml",
#            "@module": "pymatgen.io.abinit.pseudos",
#            "@class": "PawXmlSetup"
#        }
#    ]
#}
#</JSON>


# This input file template has been automatically generated by the abinp.py script.
# Several input parameters have default values that might not be suitable for you particular calculation.
# Please check the input file, make sure you understand what's happening and modify the template according to your needs
