prefix="/usr/local"
enable_mpi="no"
enable_mpi_io="no"
with_trio_flavor="netcdf"
with_netcdf_incs="-I/usr/local/include"
with_netcdf_libs="-L/usr/local/lib -lnetcdf -lnetcdff"
with_fft_flavor="fftw3"
with_fft_incs="-I/usr/local/include/"
with_fft_libs="-L/usr/lib/x86-64-linux-gnu/ -lfftw3 -lfftw3f"
with_linalg_flavor="atlas"
with_linalg_incs="-I/usr/include"
with_linalg_libs="-L/usr/lib64 -llapack -lf77blas -lcblas -latlas"
with_dft_flavor="libxc"

