This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by ABINIT configure 7.3.3, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = mater20
uname -m = x86_64
uname -r = 3.8.0-23-generic
uname -s = Linux
uname -v = #34-Ubuntu SMP Wed May 29 20:22:58 UTC 2013

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/lib/lightdm/lightdm
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games


## ----------- ##
## Core tests. ##
## ----------- ##

configure:3639: checking build system type
configure:3653: result: x86_64-unknown-linux-gnu
configure:3673: checking host system type
configure:3686: result: x86_64-unknown-linux-gnu
configure:3706: checking target system type
configure:3719: result: x86_64-unknown-linux-gnu
configure:3761: checking for a BSD-compatible install
configure:3829: result: /usr/bin/install -c
configure:3840: checking whether build environment is sane
configure:3890: result: yes
configure:4031: checking for a thread-safe mkdir -p
configure:4070: result: /bin/mkdir -p
configure:4083: checking for gawk
configure:4099: found /usr/bin/gawk
configure:4110: result: gawk
configure:4121: checking whether make sets $(MAKE)
configure:4143: result: yes
configure:4612: checking whether make sets $(MAKE)
configure:4634: result: yes
configure:4644: checking whether ln -s works
configure:4648: result: yes
configure:4655: checking for a sed that does not truncate output
configure:4719: result: /bin/sed
configure:4728: checking for gawk
configure:4755: result: gawk
configure:4766: checking for grep that handles long lines and -e
configure:4824: result: /bin/grep
configure:4831: checking for egrep
configure:4893: result: /bin/grep -E
configure:5890: reading options from /home/ebousq/.abinit/build/mater20.ac
configure:7832: ABINIT version 7.3.3
configure:7842: M4 010416 - Autoconf 026900 - Automake 011106 - Libtool 020402
configure:7853: reporting user interface changes:
configure:7856:  * new option --enable-lotf is available
configure:7893: checking consistency of library-related options
configure:7924:  |---> all OK
configure:7927: 
configure:7936: checking consistency of experimental options
configure:7951:  |---> all OK
configure:7954: 
configure:7963: checking consistency of maintainer options
configure:7979:  |---> all OK
configure:7982: 
configure:7991: parsing command-line options
configure:9157: Initializing MPI support
configure:9389: checking for mpirun
configure:9405: found /usr/bin/mpirun
configure:9416: result: mpirun
configure:9428: WARNING: MPI runner mpirun may be incompatible with MPI compilers
configure:9484: compiler checks deferred
configure:9782: GPU support disabled from command-line
configure:9825: checking for sh
configure:9843: found /bin/sh
configure:9856: result: /bin/sh
configure:9866: checking for mv
configure:9884: found /bin/mv
configure:9897: result: /bin/mv
configure:9907: checking for perl
configure:9925: found /usr/bin/perl
configure:9938: result: /usr/bin/perl
configure:9948: checking for rm
configure:9966: found /bin/rm
configure:9979: result: /bin/rm
configure:9992: checking for patch
configure:10008: found /usr/bin/patch
configure:10019: result: patch
configure:10034: checking for tar
configure:10050: found /bin/tar
configure:10061: result: tar
configure:10419: checking for gcc
configure:10435: found /usr/bin/gcc
configure:10446: result: gcc
configure:10675: checking for C compiler version
configure:10684: gcc --version >&5
gcc (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:10695: $? = 0
configure:10684: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.3-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-objc-gc --with-cloog --enable-cloog-backend=ppl --disable-cloog-version-check --disable-ppl-version-check --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1) 
configure:10695: $? = 0
configure:10684: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:10695: $? = 4
configure:10684: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:10695: $? = 4
configure:10715: checking whether the C compiler works
configure:10737: gcc    conftest.c  >&5
configure:10741: $? = 0
configure:10789: result: yes
configure:10792: checking for C compiler default output file name
configure:10794: result: a.out
configure:10800: checking for suffix of executables
configure:10807: gcc -o conftest    conftest.c  >&5
configure:10811: $? = 0
configure:10833: result: 
configure:10855: checking whether we are cross compiling
configure:10863: gcc -o conftest    conftest.c  >&5
configure:10867: $? = 0
configure:10874: ./conftest
configure:10878: $? = 0
configure:10893: result: no
configure:10898: checking for suffix of object files
configure:10920: gcc -c   conftest.c >&5
configure:10924: $? = 0
configure:10945: result: o
configure:10949: checking whether we are using the GNU C compiler
configure:10968: gcc -c   conftest.c >&5
configure:10968: $? = 0
configure:10977: result: yes
configure:10986: checking whether gcc accepts -g
configure:11006: gcc -c -g  conftest.c >&5
configure:11006: $? = 0
configure:11047: result: yes
configure:11064: checking for gcc option to accept ISO C89
configure:11127: gcc  -c -g -O2  conftest.c >&5
configure:11127: $? = 0
configure:11140: result: none needed
configure:11171: checking for style of include used by make
configure:11199: result: GNU
configure:11225: checking dependency style of gcc
configure:11336: result: gcc3
configure:11408: checking how to run the C preprocessor
configure:11439: gcc -E  conftest.c
configure:11439: $? = 0
configure:11453: gcc -E  conftest.c
conftest.c:18:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:11453: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:11478: result: gcc -E
configure:11498: gcc -E  conftest.c
configure:11498: $? = 0
configure:11512: gcc -E  conftest.c
conftest.c:18:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:11512: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:11552: checking which type of compiler we have
configure:11769: result: gnu 4.7
configure:11784: checking for ANSI C header files
configure:11804: gcc -c   conftest.c >&5
configure:11804: $? = 0
configure:11877: gcc -o conftest    conftest.c  >&5
configure:11877: $? = 0
configure:11877: ./conftest
configure:11877: $? = 0
configure:11888: result: yes
configure:11901: checking for sys/types.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for sys/stat.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for stdlib.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for string.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for memory.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for strings.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for inttypes.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for stdint.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11901: checking for unistd.h
configure:11901: gcc -c   conftest.c >&5
configure:11901: $? = 0
configure:11901: result: yes
configure:11913: checking whether byte ordering is bigendian
configure:11928: gcc -c   conftest.c >&5
conftest.c:30:9: error: unknown type name 'not'
conftest.c:30:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'universal'
conftest.c:30:15: error: unknown type name 'universal'
configure:11928: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| /* end confdefs.h.  */
| #ifndef __APPLE_CC__
| 	       not a universal capable compiler
| 	     #endif
| 	     typedef int dummy;
| 
configure:11973: gcc -c   conftest.c >&5
configure:11973: $? = 0
configure:11991: gcc -c   conftest.c >&5
conftest.c: In function 'main':
conftest.c:36:4: error: unknown type name 'not'
conftest.c:36:12: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'endian'
configure:11991: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| /* end confdefs.h.  */
| #include <sys/types.h>
| 		#include <sys/param.h>
| 
| int
| main ()
| {
| #if BYTE_ORDER != BIG_ENDIAN
| 		 not big endian
| 		#endif
| 
|   ;
|   return 0;
| }
configure:12119: result: no
configure:12680: checking for g++
configure:12696: found /usr/bin/g++
configure:12707: result: g++
configure:12734: checking for C++ compiler version
configure:12743: g++ --version >&5
g++ (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:12754: $? = 0
configure:12743: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.3-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-objc-gc --with-cloog --enable-cloog-backend=ppl --disable-cloog-version-check --disable-ppl-version-check --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1) 
configure:12754: $? = 0
configure:12743: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:12754: $? = 4
configure:12743: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'
g++: fatal error: no input files
compilation terminated.
configure:12754: $? = 4
configure:12758: checking whether we are using the GNU C++ compiler
configure:12777: g++ -c   conftest.cpp >&5
configure:12777: $? = 0
configure:12786: result: yes
configure:12795: checking whether g++ accepts -g
configure:12815: g++ -c -g  conftest.cpp >&5
configure:12815: $? = 0
configure:12856: result: yes
configure:12881: checking dependency style of g++
configure:12992: result: gcc3
configure:13021: checking which type of C++ compiler we have
configure:13238: result: gnu 4.7
configure:13505: checking for mpif90
configure:13523: found /usr/bin/mpif90
configure:13535: result: /usr/bin/mpif90
configure:13654: checking for Fortran compiler version
configure:13663: mpif90 --version >&5
GNU Fortran (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

configure:13674: $? = 0
configure:13663: mpif90 -v >&5
Using built-in specs.
COLLECT_GCC=/usr/bin/gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.3-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-objc-gc --with-cloog --enable-cloog-backend=ppl --disable-cloog-version-check --disable-ppl-version-check --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1) 
configure:13674: $? = 0
configure:13663: mpif90 -V >&5
gfortran: error: unrecognized command line option '-V'
gfortran: fatal error: no input files
compilation terminated.
configure:13674: $? = 4
configure:13663: mpif90 -qversion >&5
gfortran: error: unrecognized command line option '-qversion'
gfortran: fatal error: no input files
compilation terminated.
configure:13674: $? = 4
configure:13683: checking whether we are using the GNU Fortran compiler
configure:13696: mpif90 -c   conftest.F >&5
configure:13696: $? = 0
configure:13705: result: yes
configure:13711: checking whether mpif90 accepts -g
configure:13722: mpif90 -c -g  conftest.f >&5
configure:13722: $? = 0
configure:13730: result: yes
configure:13827: checking which type of Fortran compiler we have
configure:14186: result: gnu 4.7
configure:14199: checking fortran 90 modules extension
configure:14226: mpif90 -c -g -O2  conftest.f >&5
configure:14226: $? = 0
configure:14249: result: mod
configure:14264: checking for Fortran flag to compile .F90 files
configure:14284: mpif90 -c -g -O2  conftest.F90 >&5
configure:14284: $? = 0
configure:14293: result: none
configure:14329: determining Fortran module case
configure:14343: mpif90 -c -g -O2  conftest.F90 >&5
configure:14343: $? = 0
configure:14367: checking whether Fortran modules are upper-case
configure:14369: result: no
configure:14387: checking how to get verbose linking output from mpif90
configure:14397: mpif90 -c   conftest.F90 >&5
configure:14397: $? = 0
configure:14415: mpif90 -o conftest -v conftest.F90
Using built-in specs.
Target: x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1) 
 /usr/lib/gcc/x86_64-linux-gnu/4.7/f951 conftest.F90 -cpp=/tmp/ccdndEif.f90 -quiet -v -I /usr/lib/openmpi/include -I /usr/lib/openmpi/lib -imultilib . -imultiarch x86_64-linux-gnu -D_REENTRANT conftest.F90 -quiet -dumpbase conftest.F90 -mtune=generic -march=x86-64 -auxbase conftest -version -fintrinsic-modules-path /usr/lib/gcc/x86_64-linux-gnu/4.7/finclude -o /tmp/ccrMAHGi.s
GNU Fortran (Ubuntu/Linaro 4.7.3-1ubuntu1) version 4.7.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.7.3, GMP version 5.0.5, MPFR version 3.1.1-p2, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/openmpi/include
 /usr/lib/openmpi/lib
 /usr/lib/gcc/x86_64-linux-gnu/4.7/finclude
 /usr/lib/gcc/x86_64-linux-gnu/4.7/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.7/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU Fortran (Ubuntu/Linaro 4.7.3-1ubuntu1) version 4.7.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.7.3, GMP version 5.0.5, MPFR version 3.1.1-p2, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
 as -v -I /usr/lib/openmpi/include -I /usr/lib/openmpi/lib --64 -o /tmp/ccaKiy8l.o /tmp/ccrMAHGi.s
GNU assembler version 2.23.2 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.23.2
Reading specs from /usr/lib/gcc/x86_64-linux-gnu/4.7/libgfortran.spec
rename spec lib to liborig
 /usr/lib/gcc/x86_64-linux-gnu/4.7/collect2 --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o conftest /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.7/crtbegin.o -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. /tmp/ccaKiy8l.o -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl --export-dynamic -lnsl -lutil -lgfortran -lm -ldl -lgfortran -lm -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.7/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/crtn.o
configure:14498: result: -v
configure:14500: checking for Fortran libraries of mpif90
configure:14523: mpif90 -o conftest -v conftest.F90
Using built-in specs.
Target: x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1) 
 /usr/lib/gcc/x86_64-linux-gnu/4.7/f951 conftest.F90 -cpp=/tmp/ccOjnQKk.f90 -quiet -v -I /usr/lib/openmpi/include -I /usr/lib/openmpi/lib -imultilib . -imultiarch x86_64-linux-gnu -D_REENTRANT conftest.F90 -quiet -dumpbase conftest.F90 -mtune=generic -march=x86-64 -auxbase conftest -version -fintrinsic-modules-path /usr/lib/gcc/x86_64-linux-gnu/4.7/finclude -o /tmp/cckcXEoo.s
GNU Fortran (Ubuntu/Linaro 4.7.3-1ubuntu1) version 4.7.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.7.3, GMP version 5.0.5, MPFR version 3.1.1-p2, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/openmpi/include
 /usr/lib/openmpi/lib
 /usr/lib/gcc/x86_64-linux-gnu/4.7/finclude
 /usr/lib/gcc/x86_64-linux-gnu/4.7/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.7/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU Fortran (Ubuntu/Linaro 4.7.3-1ubuntu1) version 4.7.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.7.3, GMP version 5.0.5, MPFR version 3.1.1-p2, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
 as -v -I /usr/lib/openmpi/include -I /usr/lib/openmpi/lib --64 -o /tmp/cc8uZ95r.o /tmp/cckcXEoo.s
GNU assembler version 2.23.2 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.23.2
Reading specs from /usr/lib/gcc/x86_64-linux-gnu/4.7/libgfortran.spec
rename spec lib to liborig
 /usr/lib/gcc/x86_64-linux-gnu/4.7/collect2 --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o conftest /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.7/crtbegin.o -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. /tmp/cc8uZ95r.o -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl --export-dynamic -lnsl -lutil -lgfortran -lm -ldl -lgfortran -lm -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.7/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/crtn.o
configure:14719: result:  -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread
configure:14735: checking for dummy main to link with Fortran libraries
configure:14769: gcc -o conftest    conftest.c   -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread >&5
configure:14769: $? = 0
configure:14814: result: none
configure:14847: checking for Fortran name-mangling scheme
configure:14860: mpif90 -c   conftest.F90 >&5
configure:14860: $? = 0
configure:14901: gcc -o conftest    conftest.c cfortran_test.o   -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread >&5
/tmp/ccUgxe3C.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `foobar'
collect2: error: ld returned 1 exit status
configure:14901: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char foobar ();
| #ifdef FC_DUMMY_MAIN
| #ifndef FC_DUMMY_MAIN_EQ_F77
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int FC_DUMMY_MAIN() { return 1; }
| #endif
| #endif
| int
| main ()
| {
| return foobar ();
|   ;
|   return 0;
| }
configure:14901: gcc -o conftest    conftest.c cfortran_test.o   -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread >&5
configure:14901: $? = 0
configure:14959: gcc -o conftest    conftest.c cfortran_test.o   -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread >&5
configure:14959: $? = 0
configure:15001: result: lower case, underscore, no extra underscore
configure:15108: checking for python
configure:15124: found /usr/bin/python
configure:15135: result: python
configure:15148: checking for Python CPPFLAGS
configure:15163: result: -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include
configure:15172: checking for bzr
configure:15188: found /usr/bin/bzr
configure:15199: result: bzr
configure:15217: checking Python.h usability
configure:15217: gcc -c  -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include  conftest.c >&5
configure:15217: $? = 0
configure:15217: result: yes
configure:15217: checking Python.h presence
configure:15217: gcc -E -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include  conftest.c
configure:15217: $? = 0
configure:15217: result: yes
configure:15217: checking for Python.h
configure:15217: result: yes
configure:15229: checking for numpy/arrayobject.h
configure:15261: gcc -c  -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include  conftest.c >&5
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1728:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:15,
                 from conftest.c:36:
/usr/include/python2.7/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
configure:15261: $? = 0
configure:15278: result: yes
configure:15295: retrieving Bazaar branch information
configure:15572: checking for ar
configure:15588: found /usr/bin/ar
configure:15599: result: ar
configure:15660: checking for ranlib
configure:15676: found /usr/bin/ranlib
configure:15687: result: ranlib
configure:15758: checking for cpp
configure:15774: found /usr/bin/cpp
configure:15785: result: cpp
configure:15844: checking for a true C preprocessor
configure:15850: result: cpp
configure:15897: checking which cpp hints to apply
configure:15926: result: default/default/default
configure:15935: checking which cc hints to apply
configure:15996: result: gnu/default/default
configure:16007: checking which xpp hints to apply
configure:16011: result: none/none/none
configure:16020: checking which cxx hints to apply
configure:16073: result: gnu/default/default
configure:16084: checking which fpp hints to apply
configure:16102: result: default/default/default
configure:16111: checking which fc hints to apply
configure:16324: result: gnu/default/default
configure:16335: checking which ar hints to apply
configure:16353: result: none/none/none
configure:16371: checking which Fortran preprocessor to use
configure:16373: result: 
configure:16375: checking which Fortran preprocessor flags to apply
configure:16377: result: 
configure:16401: checking whether to wrap Fortran compiler calls
configure:16403: result: no
configure:16445: checking debugging status
configure:16468: result: enabled (profile mode: basic)
configure:16489: setting C debug flags to '-g'
configure:16497: setting C++ debug flags to '-g'
configure:16505: setting Fortran debug flags to '-g'
configure:16511: checking whether to activate debug mode in source files
configure:16522: result: no
configure:16534: checking which cc debug flags to apply
configure:16561: result: gnu/default/default
configure:16575: checking which cxx debug flags to apply
configure:16579: result: none/none/none
configure:16593: checking which fc debug flags to apply
configure:16929: result: gnu/4.7/default
configure:16949: checking whether to activate design-by-contract debugging
configure:16958: result: no
configure:17003: checking optimization status
configure:17026: result: enabled (profile mode: aggressive)
configure:17051: checking which cc optimizations to apply
configure:17469: result: gnu/default/default
configure:17483: checking which cxx optimizations to apply
configure:17844: result: gnu/default/default
configure:17858: checking which fc optimizations to apply
configure:18728: result: gnu/4.7/default
configure:18742: checking whether to apply per-directory optimizations
configure:18748: result: yes
configure:20159: checking for a 64-bit architecture
configure:20161: result: yes
configure:20163: checking whether to use 64-bit flags
configure:20165: result: yes
configure:20167: checking for user-defined 64-bit flags
configure:20169: result: 
configure:20174: checking for 64-bit C preprocessor flags
configure:20177: result: none
configure:20190: checking for 64-bit C flags
configure:20196: result: -m64
configure:20225: checking for 64-bit C++ flags
configure:20231: result: -m64
configure:20260: checking for 64-bit Fortran flags
configure:20266: result: -m64
configure:20276: checking for 64-bit archiver flags
configure:20279: result: none
configure:20367: static builds may be performed
configure:20414: checking stddef.h usability
configure:20414: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20414: $? = 0
configure:20414: result: yes
configure:20414: checking stddef.h presence
configure:20414: gcc -E      conftest.c
configure:20414: $? = 0
configure:20414: result: yes
configure:20414: checking for stddef.h
configure:20414: result: yes
configure:20414: checking stdarg.h usability
configure:20414: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20414: $? = 0
configure:20414: result: yes
configure:20414: checking stdarg.h presence
configure:20414: gcc -E      conftest.c
configure:20414: $? = 0
configure:20414: result: yes
configure:20414: checking for stdarg.h
configure:20414: result: yes
configure:20427: checking stdio.h usability
configure:20427: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20427: $? = 0
configure:20427: result: yes
configure:20427: checking stdio.h presence
configure:20427: gcc -E      conftest.c
configure:20427: $? = 0
configure:20427: result: yes
configure:20427: checking for stdio.h
configure:20427: result: yes
configure:20427: checking math.h usability
configure:20427: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20427: $? = 0
configure:20427: result: yes
configure:20427: checking math.h presence
configure:20427: gcc -E      conftest.c
configure:20427: $? = 0
configure:20427: result: yes
configure:20427: checking for math.h
configure:20427: result: yes
configure:20427: checking termios.h usability
configure:20427: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20427: $? = 0
configure:20427: result: yes
configure:20427: checking termios.h presence
configure:20427: gcc -E      conftest.c
configure:20427: $? = 0
configure:20427: result: yes
configure:20427: checking for termios.h
configure:20427: result: yes
configure:20439: checking errno.h usability
configure:20439: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20439: $? = 0
configure:20439: result: yes
configure:20439: checking errno.h presence
configure:20439: gcc -E      conftest.c
configure:20439: $? = 0
configure:20439: result: yes
configure:20439: checking for errno.h
configure:20439: result: yes
configure:20452: checking malloc.h usability
configure:20452: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20452: $? = 0
configure:20452: result: yes
configure:20452: checking malloc.h presence
configure:20452: gcc -E      conftest.c
configure:20452: $? = 0
configure:20452: result: yes
configure:20452: checking for malloc.h
configure:20452: result: yes
configure:20452: checking sys/malloc.h usability
configure:20452: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
conftest.c:77:24: fatal error: sys/malloc.h: No such file or directory
compilation terminated.
configure:20452: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| #define HAVE_NUMPY 1
| #define HAVE_BZR_BRANCH 1
| #define ABINIT_TARGET "x86_64_linux_gnu4.7"
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MALLOC_H 1
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #include <sys/malloc.h>
configure:20452: result: no
configure:20452: checking sys/malloc.h presence
configure:20452: gcc -E      conftest.c
conftest.c:44:24: fatal error: sys/malloc.h: No such file or directory
compilation terminated.
configure:20452: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| #define HAVE_NUMPY 1
| #define HAVE_BZR_BRANCH 1
| #define ABINIT_TARGET "x86_64_linux_gnu4.7"
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MALLOC_H 1
| /* end confdefs.h.  */
| #include <sys/malloc.h>
configure:20452: result: no
configure:20452: checking for sys/malloc.h
configure:20452: result: no
configure:20464: checking mcheck.h usability
configure:20464: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20464: $? = 0
configure:20464: result: yes
configure:20464: checking mcheck.h presence
configure:20464: gcc -E      conftest.c
configure:20464: $? = 0
configure:20464: result: yes
configure:20464: checking for mcheck.h
configure:20464: result: yes
configure:20476: checking sys/time.h usability
configure:20476: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20476: $? = 0
configure:20476: result: yes
configure:20476: checking sys/time.h presence
configure:20476: gcc -E      conftest.c
configure:20476: $? = 0
configure:20476: result: yes
configure:20476: checking for sys/time.h
configure:20476: result: yes
configure:20488: checking sys/resource.h usability
configure:20488: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:20488: $? = 0
configure:20488: result: yes
configure:20488: checking sys/resource.h presence
configure:20488: gcc -E      conftest.c
configure:20488: $? = 0
configure:20488: result: yes
configure:20488: checking for sys/resource.h
configure:20488: result: yes
configure:20504: checking for abort
configure:20504: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
conftest.c:70:6: warning: conflicting types for built-in function 'abort' [enabled by default]
configure:20504: $? = 0
configure:20504: result: yes
configure:20515: checking for mallinfo
configure:20515: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20515: $? = 0
configure:20515: result: yes
configure:20532: checking size of char
configure:20537: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20537: $? = 0
configure:20537: ./conftest
configure:20537: $? = 0
configure:20551: result: 1
configure:20565: checking size of short
configure:20570: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20570: $? = 0
configure:20570: ./conftest
configure:20570: $? = 0
configure:20584: result: 2
configure:20598: checking size of int
configure:20603: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20603: $? = 0
configure:20603: ./conftest
configure:20603: $? = 0
configure:20617: result: 4
configure:20631: checking size of long
configure:20636: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20636: $? = 0
configure:20636: ./conftest
configure:20636: $? = 0
configure:20650: result: 8
configure:20664: checking size of long long
configure:20669: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20669: $? = 0
configure:20669: ./conftest
configure:20669: $? = 0
configure:20683: result: 8
configure:20697: checking size of unsigned int
configure:20702: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20702: $? = 0
configure:20702: ./conftest
configure:20702: $? = 0
configure:20716: result: 4
configure:20730: checking size of unsigned long
configure:20735: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20735: $? = 0
configure:20735: ./conftest
configure:20735: $? = 0
configure:20749: result: 8
configure:20763: checking size of unsigned long long
configure:20768: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20768: $? = 0
configure:20768: ./conftest
configure:20768: $? = 0
configure:20782: result: 8
configure:20796: checking size of float
configure:20801: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20801: $? = 0
configure:20801: ./conftest
configure:20801: $? = 0
configure:20815: result: 4
configure:20829: checking size of double
configure:20834: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20834: $? = 0
configure:20834: ./conftest
configure:20834: $? = 0
configure:20848: result: 8
configure:20862: checking size of long double
configure:20867: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20867: $? = 0
configure:20867: ./conftest
configure:20867: $? = 0
configure:20881: result: 16
configure:20895: checking size of size_t
configure:20900: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20900: $? = 0
configure:20900: ./conftest
configure:20900: $? = 0
configure:20914: result: 8
configure:20928: checking size of ptrdiff_t
configure:20933: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native         conftest.c  >&5
configure:20933: $? = 0
configure:20933: ./conftest
configure:20933: $? = 0
configure:20947: result: 8
configure:20958: checking for an ANSI C-conforming const
configure:21032: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:21032: $? = 0
configure:21039: result: yes
configure:21047: checking for size_t
configure:21047: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
configure:21047: $? = 0
configure:21047: gcc -m64 -c -m64 -g -O3 -mtune=native -march=native        conftest.c >&5
conftest.c: In function 'main':
conftest.c:106:21: error: expected expression before ')' token
configure:21047: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| #define HAVE_NUMPY 1
| #define HAVE_BZR_BRANCH 1
| #define ABINIT_TARGET "x86_64_linux_gnu4.7"
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MCHECK_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_SYS_RESOURCE_H 1
| #define HAVE_ABORT 1
| #define HAVE_MALLINFO 1
| #define SIZEOF_CHAR 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_UNSIGNED_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG_DOUBLE 16
| #define SIZEOF_SIZE_T 8
| #define SIZEOF_PTRDIFF_T 8
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #ifdef FC_DUMMY_MAIN
| #ifndef FC_DUMMY_MAIN_EQ_F77
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int FC_DUMMY_MAIN() { return 1; }
| #endif
| #endif
| int
| main ()
| {
| if (sizeof ((size_t)))
| 	    return 0;
|   ;
|   return 0;
| }
configure:21047: result: yes
configure:21065: checking whether the Fortran compiler supports EXECUTE_COMMAND_LINE
configure:21086: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21086: $? = 0
configure:21104: result: yes
configure:21110: checking whether the Fortran compiler accepts the CONTIGUOUS attribute
configure:21130: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21130: $? = 0
configure:21148: result: yes
configure:21154: checking whether the Fortran compiler supports allocatable arrays in datatypes
configure:21178: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21178: $? = 0
configure:21196: result: yes
configure:21202: checking whether the Fortran compiler supports IOMSG
configure:21224: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21224: $? = 0
configure:21242: result: yes
configure:21248: checking whether the Fortran compiler provides the iso_c_binding module
configure:21270: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21270: $? = 0
configure:21288: result: yes
configure:21294: checking whether the Fortran compiler accepts exit()
configure:21309: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21309: $? = 0
configure:21327: result: yes
configure:21333: checking whether the Fortran compiler accepts flush()
configure:21348: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21348: $? = 0
configure:21366: result: yes
configure:21372: checking whether the Fortran compiler accepts flush_()
configure:21387: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
/tmp/ccXruOWw.o: In function `MAIN__':
/home/ebousq/CODES/Abinit/Branches/7.3.3-private/conftest.F90:3: undefined reference to `flush__'
collect2: error: ld returned 1 exit status
configure:21387: $? = 1
configure: failed program was:
|       program main
| 
|             call flush_()
| 
|       end
configure:21405: result: no
configure:21411: checking whether the Fortran compiler accepts gamma()
configure:21427: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21427: $? = 0
configure:21445: result: yes
configure:21451: checking whether the Fortran compiler accepts getenv()
configure:21468: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21468: $? = 0
configure:21486: result: yes
configure:21504: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
/tmp/ccZ1OAFP.o: In function `MAIN__':
/home/ebousq/CODES/Abinit/Branches/7.3.3-private/conftest.F90:3: undefined reference to `getpid_'
collect2: error: ld returned 1 exit status
configure:21504: $? = 1
configure: failed program was:
|       program main
| 
|           call getpid()
| 
|       end
configure:21516: checking whether the Fortran compiler accepts getpid()
configure:21518: result: no
configure:21529: checking whether the Fortran compiler accepts the null() intrinsic
configure:21548: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21548: $? = 0
configure:21566: result: yes
configure:21572: checking whether the Fortran compiler accepts quadruple integers
configure:21588: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21588: $? = 0
configure:21607: result: yes
configure:21613: checking whether the Fortran compiler accepts long lines
configure:21628: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21628: $? = 0
configure:21646: result: yes
configure:21652: checking whether the Fortran compiler supports stream IO
configure:21676: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21676: $? = 0
configure:21694: result: yes
configure:21700: checking whether the Fortran compiler accepts cpu_time()
configure:21717: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
configure:21717: $? = 0
configure:21735: result: yes
configure:21743: checking whether the Fortran compiler accepts etime()
configure:21758: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none     conftest.F90  >&5
conftest.F90:3.25:

            call etime(1)
                         1
Error: Missing actual argument 'time' in call to 'etime' at (1)
configure:21758: $? = 1
configure: failed program was:
|       program main
| 
|             call etime(1)
| 
|       end
configure:21776: result: no
configure:21781: checking whether to use C clock for timings
configure:21783: result: no
configure:21831: checking whether to enable OpenMP support
configure:21833: result: no
configure:21911: checking whether to build MPI code
configure:21913: result: yes
configure:21922: checking whether the C compiler supports MPI
configure:22184: gcc -m64 -o conftest -m64 -g -O3 -mtune=native -march=native              conftest.c       >&5
conftest.c:77:17: fatal error: mpi.h: No such file or directory
compilation terminated.
configure:22184: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| #define HAVE_NUMPY 1
| #define HAVE_BZR_BRANCH 1
| #define ABINIT_TARGET "x86_64_linux_gnu4.7"
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MCHECK_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_SYS_RESOURCE_H 1
| #define HAVE_ABORT 1
| #define HAVE_MALLINFO 1
| #define SIZEOF_CHAR 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_UNSIGNED_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG_DOUBLE 16
| #define SIZEOF_SIZE_T 8
| #define SIZEOF_PTRDIFF_T 8
| #define HAVE_FC_COMMAND_LINE 1
| #define HAVE_FC_CONTIGUOUS 1
| #define HAVE_FC_ALLOCATABLE_DTARRAYS 1
| #define HAVE_FC_IOMSG 1
| #define HAVE_FC_ISO_C_BINDING 1
| #define HAVE_FC_EXIT 1
| #define HAVE_FC_FLUSH 1
| #define HAVE_FC_GAMMA 1
| #define HAVE_FC_GETENV 1
| #define HAVE_FC_NULL 1
| #define HAVE_FC_INT_QUAD 1
| #define HAVE_FC_LONG_LINES 1
| #define HAVE_FC_STREAM_IO 1
| #define HAVE_FC_CPUTIME 1
| /* end confdefs.h.  */
| #include <stdlib.h>
| #include "mpi.h"
| #ifdef FC_DUMMY_MAIN
| #ifndef FC_DUMMY_MAIN_EQ_F77
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int FC_DUMMY_MAIN() { return 1; }
| #endif
| #endif
| int
| main ()
| {
| 
|       int rc;
| 
|       MPI_Init(NULL,NULL);
|       rc = MPI_Finalize();
| 
|   ;
|   return 0;
| }
configure:22422: result: no
configure:22428: checking whether the C++ compiler supports MPI
configure:22687: g++ -m64 -o conftest -m64 -g -O3 -mtune=native -march=native              conftest.cpp       >&5
conftest.cpp:76:17: fatal error: mpi.h: No such file or directory
compilation terminated.
configure:22687: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ABINIT"
| #define PACKAGE_TARNAME "abinit"
| #define PACKAGE_VERSION "7.3.3"
| #define PACKAGE_STRING "ABINIT 7.3.3"
| #define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
| #define PACKAGE_URL ""
| #define PACKAGE "abinit"
| #define VERSION "7.3.3"
| #define ABINIT_VERSION "7.3.3"
| #define ABINIT_VERSION_MAJOR "7"
| #define ABINIT_VERSION_MINOR "3"
| #define ABINIT_VERSION_MICRO "3"
| #define ABINIT_VERSION_BUILD "20130604"
| #define ABINIT_VERSION_BASE "7.3"
| #define HAVE_OS_LINUX 1
| #define CC_GNU 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define CXX_GNU 1
| #define FC_GNU 1
| #define HAVE_FORTRAN2003 1
| #define FC_FUNC(name,NAME) name ## _
| #define FC_FUNC_(name,NAME) name ## _
| #define HAVE_NUMPY 1
| #define HAVE_BZR_BRANCH 1
| #define ABINIT_TARGET "x86_64_linux_gnu4.7"
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_MATH_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MCHECK_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_SYS_RESOURCE_H 1
| #define HAVE_ABORT 1
| #define HAVE_MALLINFO 1
| #define SIZEOF_CHAR 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_UNSIGNED_INT 4
| #define SIZEOF_UNSIGNED_LONG 8
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_FLOAT 4
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG_DOUBLE 16
| #define SIZEOF_SIZE_T 8
| #define SIZEOF_PTRDIFF_T 8
| #define HAVE_FC_COMMAND_LINE 1
| #define HAVE_FC_CONTIGUOUS 1
| #define HAVE_FC_ALLOCATABLE_DTARRAYS 1
| #define HAVE_FC_IOMSG 1
| #define HAVE_FC_ISO_C_BINDING 1
| #define HAVE_FC_EXIT 1
| #define HAVE_FC_FLUSH 1
| #define HAVE_FC_GAMMA 1
| #define HAVE_FC_GETENV 1
| #define HAVE_FC_NULL 1
| #define HAVE_FC_INT_QUAD 1
| #define HAVE_FC_LONG_LINES 1
| #define HAVE_FC_STREAM_IO 1
| #define HAVE_FC_CPUTIME 1
| /* end confdefs.h.  */
| #include "mpi.h"
| #ifdef FC_DUMMY_MAIN
| #ifndef FC_DUMMY_MAIN_EQ_F77
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int FC_DUMMY_MAIN() { return 1; }
| #endif
| #endif
| int
| main ()
| {
| 
|       MPI::Init();
|       MPI::Finalize();
| 
|   ;
|   return 0;
| }
configure:22925: result: no
configure:22931: checking whether the Fortran Compiler supports MPI
configure:23177: mpif90 -m64 -o conftest -m64 -g -ffree-line-length-none         conftest.F90       -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread  >&5
configure:23177: $? = 0
configure:23415: result: yes
configure:23424: checking whether MPI is usable
configure:23426: result: no
configure:23437: error: MPI support is broken - please fix your config parameters and/or MPI installation

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_c_bigendian=no
ac_cv_c_compiler_gnu=yes
ac_cv_c_const=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_ARFLAGS_DEBUG_set=
ac_cv_env_ARFLAGS_DEBUG_value=
ac_cv_env_ARFLAGS_EXTRA_set=
ac_cv_env_ARFLAGS_EXTRA_value=
ac_cv_env_ARFLAGS_OPTIM_set=
ac_cv_env_ARFLAGS_OPTIM_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_LDFLAGS_DEBUG_set=
ac_cv_env_CC_LDFLAGS_DEBUG_value=
ac_cv_env_CC_LDFLAGS_OPTIM_set=
ac_cv_env_CC_LDFLAGS_OPTIM_value=
ac_cv_env_CC_LDFLAGS_set=
ac_cv_env_CC_LDFLAGS_value=
ac_cv_env_CC_LIBS_DEBUG_set=
ac_cv_env_CC_LIBS_DEBUG_value=
ac_cv_env_CC_LIBS_OPTIM_set=
ac_cv_env_CC_LIBS_OPTIM_value=
ac_cv_env_CC_LIBS_set=
ac_cv_env_CC_LIBS_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_DEBUG_set=
ac_cv_env_CFLAGS_DEBUG_value=
ac_cv_env_CFLAGS_EXTRA_set=
ac_cv_env_CFLAGS_EXTRA_value=
ac_cv_env_CFLAGS_OPTIM_set=
ac_cv_env_CFLAGS_OPTIM_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_DEBUG_set=
ac_cv_env_CPPFLAGS_DEBUG_value=
ac_cv_env_CPPFLAGS_EXTRA_set=
ac_cv_env_CPPFLAGS_EXTRA_value=
ac_cv_env_CPPFLAGS_OPTIM_set=
ac_cv_env_CPPFLAGS_OPTIM_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_DEBUG_set=
ac_cv_env_CXXFLAGS_DEBUG_value=
ac_cv_env_CXXFLAGS_EXTRA_set=
ac_cv_env_CXXFLAGS_EXTRA_value=
ac_cv_env_CXXFLAGS_OPTIM_set=
ac_cv_env_CXXFLAGS_OPTIM_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_LDFLAGS_DEBUG_set=
ac_cv_env_CXX_LDFLAGS_DEBUG_value=
ac_cv_env_CXX_LDFLAGS_EXTRA_set=
ac_cv_env_CXX_LDFLAGS_EXTRA_value=
ac_cv_env_CXX_LDFLAGS_OPTIM_set=
ac_cv_env_CXX_LDFLAGS_OPTIM_value=
ac_cv_env_CXX_LDFLAGS_set=
ac_cv_env_CXX_LDFLAGS_value=
ac_cv_env_CXX_LIBS_DEBUG_set=
ac_cv_env_CXX_LIBS_DEBUG_value=
ac_cv_env_CXX_LIBS_OPTIM_set=
ac_cv_env_CXX_LIBS_OPTIM_value=
ac_cv_env_CXX_LIBS_set=
ac_cv_env_CXX_LIBS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_FCFLAGS_DEBUG_set=
ac_cv_env_FCFLAGS_DEBUG_value=
ac_cv_env_FCFLAGS_EXTRA_set=
ac_cv_env_FCFLAGS_EXTRA_value=
ac_cv_env_FCFLAGS_OPENMP_set=
ac_cv_env_FCFLAGS_OPENMP_value=
ac_cv_env_FCFLAGS_OPTIM_set=
ac_cv_env_FCFLAGS_OPTIM_value=
ac_cv_env_FCFLAGS_set=
ac_cv_env_FCFLAGS_value=
ac_cv_env_FC_LDFLAGS_DEBUG_set=
ac_cv_env_FC_LDFLAGS_DEBUG_value=
ac_cv_env_FC_LDFLAGS_EXTRA_set=
ac_cv_env_FC_LDFLAGS_EXTRA_value=
ac_cv_env_FC_LDFLAGS_OPTIM_set=
ac_cv_env_FC_LDFLAGS_OPTIM_value=
ac_cv_env_FC_LDFLAGS_set=
ac_cv_env_FC_LDFLAGS_value=
ac_cv_env_FC_LIBS_DEBUG_set=
ac_cv_env_FC_LIBS_DEBUG_value=
ac_cv_env_FC_LIBS_OPTIM_set=
ac_cv_env_FC_LIBS_OPTIM_value=
ac_cv_env_FC_LIBS_set=
ac_cv_env_FC_LIBS_value=
ac_cv_env_FC_set=
ac_cv_env_FC_value=
ac_cv_env_FPPFLAGS_DEBUG_set=
ac_cv_env_FPPFLAGS_DEBUG_value=
ac_cv_env_FPPFLAGS_EXTRA_set=
ac_cv_env_FPPFLAGS_EXTRA_value=
ac_cv_env_FPPFLAGS_OPTIM_set=
ac_cv_env_FPPFLAGS_OPTIM_value=
ac_cv_env_FPPFLAGS_set=
ac_cv_env_FPPFLAGS_value=
ac_cv_env_FPP_set=
ac_cv_env_FPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MPI_RUNNER_set=
ac_cv_env_MPI_RUNNER_value=
ac_cv_env_SERIAL_RUNNER_set=
ac_cv_env_SERIAL_RUNNER_value=
ac_cv_env_XPPFLAGS_DEBUG_set=
ac_cv_env_XPPFLAGS_DEBUG_value=
ac_cv_env_XPPFLAGS_EXTRA_set=
ac_cv_env_XPPFLAGS_EXTRA_value=
ac_cv_env_XPPFLAGS_OPTIM_set=
ac_cv_env_XPPFLAGS_OPTIM_value=
ac_cv_env_XPPFLAGS_set=
ac_cv_env_XPPFLAGS_value=
ac_cv_env_XPP_set=
ac_cv_env_XPP_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_fc_compiler_gnu=yes
ac_cv_fc_dummy_main=none
ac_cv_fc_libs=' -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread'
ac_cv_fc_mangling='lower case, underscore, no extra underscore'
ac_cv_fc_srcext_F90=none
ac_cv_fortran_dummy_main=none
ac_cv_func_abort=yes
ac_cv_func_mallinfo=yes
ac_cv_header_Python_h=yes
ac_cv_header_errno_h=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_malloc_h=yes
ac_cv_header_math_h=yes
ac_cv_header_mcheck_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_stdarg_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stddef_h=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdio_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_malloc_h=no
ac_cv_header_sys_resource_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_time_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_termios_h=yes
ac_cv_header_unistd_h=yes
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_objext=o
ac_cv_path_BOURNE_SHELL=/bin/sh
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_GREP=/bin/grep
ac_cv_path_MV=/bin/mv
ac_cv_path_PERL=/usr/bin/perl
ac_cv_path_RM=/bin/rm
ac_cv_path_SED=/bin/sed
ac_cv_path_abi_fc_path=/usr/bin/mpif90
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AR=ar
ac_cv_prog_AWK=gawk
ac_cv_prog_BAZAAR=bzr
ac_cv_prog_CPP='gcc -E'
ac_cv_prog_MPI_RUNNER=mpirun
ac_cv_prog_PATCH=patch
ac_cv_prog_PYTHON=python
ac_cv_prog_TAR=tar
ac_cv_prog_TRUE_CPP=cpp
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_ac_ct_RANLIB=ranlib
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_prog_fc_g=yes
ac_cv_prog_fc_v=-v
ac_cv_prog_make_make_set=yes
ac_cv_sizeof_char=1
ac_cv_sizeof_double=8
ac_cv_sizeof_float=4
ac_cv_sizeof_int=4
ac_cv_sizeof_long=8
ac_cv_sizeof_long_double=16
ac_cv_sizeof_long_long=8
ac_cv_sizeof_ptrdiff_t=8
ac_cv_sizeof_short=2
ac_cv_sizeof_size_t=8
ac_cv_sizeof_unsigned_int=4
ac_cv_sizeof_unsigned_long=8
ac_cv_sizeof_unsigned_long_long=8
ac_cv_target=x86_64-unknown-linux-gnu
ac_cv_type_size_t=yes
am_cv_CC_dependencies_compiler_type=gcc3
am_cv_CXX_dependencies_compiler_type=gcc3
ax_cv_f90_modext=mod

## ----------------- ##
## Output variables. ##
## ----------------- ##

ABINIT_BINARY_PACKAGE='abinit-7.3.3_x86_64_linux_gnu4.7'
ABINIT_TARGET='x86_64_linux_gnu4.7'
ABINIT_VERSION='7.3.3'
ABINIT_VERSION_BASE='7.3'
ABINIT_VERSION_BUILD='20130604'
ABINIT_VERSION_MAJOR='7'
ABINIT_VERSION_MICRO='3'
ABINIT_VERSION_MINOR='3'
ABI_CPPFLAGS=''
ACLOCAL='${SHELL} /home/ebousq/CODES/Abinit/Branches/7.3.3-private/config/gnu/missing --run aclocal-1.11'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AR='ar'
ARFLAGS='     rc'
ARFLAGS_64BITS=''
ARFLAGS_CMD='rc'
ARFLAGS_DEBUG=''
ARFLAGS_EXTRA=''
ARFLAGS_HINTS=''
ARFLAGS_OPTIM=''
ATOMPAW_BIN=''
AUTOCONF='${SHELL} /home/ebousq/CODES/Abinit/Branches/7.3.3-private/config/gnu/missing --run autoconf'
AUTOHEADER='${SHELL} /home/ebousq/CODES/Abinit/Branches/7.3.3-private/config/gnu/missing --run autoheader'
AUTOMAKE='${SHELL} /home/ebousq/CODES/Abinit/Branches/7.3.3-private/config/gnu/missing --run automake-1.11'
AWK='gawk'
BAZAAR='bzr'
BOURNE_SHELL='/bin/sh'
CC='gcc -m64'
CCDEPMODE='depmode=gcc3'
CC_LDFLAGS='    '
CC_LDFLAGS_64BITS=''
CC_LDFLAGS_DEBUG=''
CC_LDFLAGS_EXTRA=''
CC_LDFLAGS_GPU=''
CC_LDFLAGS_HINTS=''
CC_LDFLAGS_OPTIM=''
CC_LIBS='    '
CC_LIBS_64BITS=''
CC_LIBS_DEBUG=''
CC_LIBS_EXTRA=''
CC_LIBS_GPU=''
CC_LIBS_HINTS=''
CC_LIBS_OPTIM=''
CFLAGS='-m64 -g -O3 -mtune=native -march=native  '
CFLAGS_64BITS='-m64'
CFLAGS_DEBUG='-g'
CFLAGS_EXTRA=''
CFLAGS_GPU=''
CFLAGS_HINTS=''
CFLAGS_OPTIM='-O3 -mtune=native -march=native'
CPP='gcc -E'
CPPFLAGS='    '
CPPFLAGS_64BITS=''
CPPFLAGS_DEBUG=''
CPPFLAGS_EXTRA=''
CPPFLAGS_GPU=''
CPPFLAGS_HINTS=''
CPPFLAGS_HINTS_EXT='-P -std=c99'
CPPFLAGS_OPTIM=''
CXX='g++ -m64'
CXXDEPMODE='depmode=gcc3'
CXXFLAGS='-m64 -g -O3 -mtune=native -march=native  '
CXXFLAGS_64BITS='-m64'
CXXFLAGS_DEBUG='-g'
CXXFLAGS_EXTRA=''
CXXFLAGS_GPU=''
CXXFLAGS_HINTS=''
CXXFLAGS_OPTIM='-O3 -mtune=native -march=native'
CXX_LDFLAGS='    '
CXX_LDFLAGS_64BITS=''
CXX_LDFLAGS_DEBUG=''
CXX_LDFLAGS_EXTRA=''
CXX_LDFLAGS_GPU=''
CXX_LDFLAGS_HINTS=''
CXX_LDFLAGS_OPTIM=''
CXX_LIBS='    '
CXX_LIBS_64BITS=''
CXX_LIBS_DEBUG=''
CXX_LIBS_EXTRA=''
CXX_LIBS_GPU=''
CXX_LIBS_HINTS=''
CXX_LIBS_OPTIM=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DO_BUILD_01_GSL_EXT_FALSE=''
DO_BUILD_01_GSL_EXT_TRUE=''
DO_BUILD_01_MACROAVNEW_EXT_FALSE=''
DO_BUILD_01_MACROAVNEW_EXT_TRUE=''
DO_BUILD_02_CLIB_FALSE=''
DO_BUILD_02_CLIB_TRUE=''
DO_BUILD_15_GPU_TOOLBOX_FALSE=''
DO_BUILD_15_GPU_TOOLBOX_TRUE=''
DO_BUILD_32_CONTRACT_FALSE=''
DO_BUILD_32_CONTRACT_TRUE='#'
DO_BUILD_52_MANAGE_CUDA_FALSE=''
DO_BUILD_52_MANAGE_CUDA_TRUE=''
DO_BUILD_65_LOTF_BASE_FALSE=''
DO_BUILD_65_LOTF_BASE_TRUE=''
DO_BUILD_68_LOTF_FALSE=''
DO_BUILD_68_LOTF_TRUE=''
DO_BUILD_BINDINGS_FALSE=''
DO_BUILD_BINDINGS_TRUE=''
DO_BUILD_CCLOCK_FALSE=''
DO_BUILD_CCLOCK_TRUE='#'
DO_BUILD_DOC_FALSE=''
DO_BUILD_DOC_TRUE=''
DO_BUILD_EXPORTS_FALSE=''
DO_BUILD_EXPORTS_TRUE=''
DO_BUILD_GUI_FALSE=''
DO_BUILD_GUI_TRUE=''
DO_BUILD_MACROAVE_FALSE=''
DO_BUILD_MACROAVE_TRUE=''
DO_BUILD_TESTS_FALSE=''
DO_BUILD_TESTS_TRUE=''
DO_TEST_MPI_FALSE=''
DO_TEST_MPI_TRUE=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
EXEEXT=''
F77=''
FC='mpif90 -m64'
FCFLAGS='-m64 -g -ffree-line-length-none  '
FCFLAGS_64BITS='-m64'
FCFLAGS_DEBUG='-g'
FCFLAGS_EXTRA=''
FCFLAGS_F90=''
FCFLAGS_FIXEDFORM='-ffixed-form'
FCFLAGS_FREEFORM='-ffree-form'
FCFLAGS_HINTS='-ffree-line-length-none'
FCFLAGS_MODDIR='-J$(abinit_moddir)'
FCFLAGS_OPENMP=''
FCFLAGS_OPTIM='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
FCLIBS=' -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread'
FC_LDFLAGS='    '
FC_LDFLAGS_64BITS=''
FC_LDFLAGS_DEBUG=''
FC_LDFLAGS_EXTRA=''
FC_LDFLAGS_HINTS=''
FC_LDFLAGS_OPTIM=''
FC_LIBS='      -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread'
FC_LIBS_64BITS=''
FC_LIBS_DEBUG=''
FC_LIBS_EXTRA=''
FC_LIBS_HINTS=''
FC_LIBS_OPTIM=''
FC_NOWRAP=''
FFLAGS=''
FPP=''
FPPFLAGS='    '
FPPFLAGS_DEBUG=''
FPPFLAGS_EXTRA=''
FPPFLAGS_HINTS=''
FPPFLAGS_OPTIM=''
GRAPHATOM_BIN=''
GREP='/bin/grep'
GSL_CONFIG=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JAVA=''
LDFLAGS='    '
LIBOBJS=''
LIBS='      -L/usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.7/../../.. -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -lgfortran -lm -lquadmath -lpthread '
LN_S='ln -s'
LTLIBOBJS=''
LTXFLAGS=''
MAKEINFO='${SHELL} /home/ebousq/CODES/Abinit/Branches/7.3.3-private/config/gnu/missing --run makeinfo'
MDFLAGS=''
MKDIR_P='/bin/mkdir -p'
MODEXT='mod'
MPI_RUNNER='mpirun'
MV='/bin/mv'
NVCC=''
NVCC_CFLAGS=''
NVCC_CPPFLAGS=''
NVCC_LDFLAGS=''
NVCC_LIBS=''
OBJEXT='o'
PACKAGE='abinit'
PACKAGE_BUGREPORT='https://bugs.launchpad.net/abinit/'
PACKAGE_NAME='ABINIT'
PACKAGE_STRING='ABINIT 7.3.3'
PACKAGE_TARNAME='abinit'
PACKAGE_URL=''
PACKAGE_VERSION='7.3.3'
PATCH='patch'
PATH_SEPARATOR=':'
PDFFLAGS=''
PERL='/usr/bin/perl'
PYTHON='python'
PYTHON_CPPFLAGS='-I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include'
RANLIB='ranlib'
RM='/bin/rm'
SED='/bin/sed'
SERIAL_RUNNER=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
TAR='tar'
TRUE_CPP='cpp'
VERSION='7.3.3'
WANNIER90_X_BIN=''
XPP=''
XPPFLAGS='    '
XPPFLAGS_DEBUG=''
XPPFLAGS_EXTRA=''
XPPFLAGS_OPTIM=''
abi_ac_version='026900'
abi_am_version='011106'
abi_cc_path=''
abi_cc_vendor='gnu'
abi_cc_version='4.7'
abi_cpp_path=''
abi_cpu_64bits='yes'
abi_cpu_bits='64'
abi_cpu_model='unknown'
abi_cpu_platform='unknown'
abi_cpu_spec='unknown_unknown'
abi_cpu_vendor='unknown'
abi_cxx_path=''
abi_cxx_vendor='gnu'
abi_cxx_version='4.7'
abi_fc_path='/usr/bin/mpif90'
abi_fc_vendor='gnu'
abi_fc_version='4.7'
abi_fc_wrap='no'
abi_fpp_path=''
abi_lt_version='020402'
abi_m4_version='010416'
abi_mpi_runner_works=''
abi_sys_spec='linux-x86_64'
abi_test_atompaw=''
abi_test_bigdft=''
abi_test_etsf_io=''
abi_test_fox=''
abi_test_gui=''
abi_test_libxc=''
abi_test_netcdf=''
abi_test_wannier90=''
abinit_bindir='/usr/local/bin'
abinit_builddir='/home/ebousq/CODES/Abinit/Branches/7.3.3-private'
abinit_chkdir='/usr/local/share/abinit/tests'
abinit_datdir='/usr/local/share/abinit'
abinit_docdir='/usr/local/doc/abinit'
abinit_incdir='/usr/local/include'
abinit_libdir='/usr/local/lib'
abinit_mandir='/usr/local/share/man'
abinit_moddir='/home/ebousq/CODES/Abinit/Branches/7.3.3-private/src/mods'
abinit_prefix='/usr/local'
abinit_srcdir='/home/ebousq/CODES/Abinit/Branches/7.3.3-private'
abinit_tardir=''
ac_ct_CC='gcc'
ac_ct_CXX='g++'
ac_ct_FC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE='#'
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
bzr_branch='jean-michel.beuken@uclouvain.be-20130528064834-nhuugqf65beqcb29'
bzr_clean='0'
bzr_revno='385'
cc_for_timeout=''
cc_info_string='gcc (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3'
cxx_info_string='g++ (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
enable_64bit_flags='yes'
enable_bindings='no'
enable_bse_unpacked='no'
enable_cclock='no'
enable_clib='no'
enable_config_file='yes'
enable_connectors='yes'
enable_debug='basic'
enable_dev_timer='no'
enable_exports='no'
enable_fallbacks='yes'
enable_fast_check='no'
enable_fc_wrapper='no'
enable_gpu='no'
enable_gui='no'
enable_gw_dpc='no'
enable_hints='yes'
enable_lotf='no'
enable_macroave='yes'
enable_maintainer_checks='no'
enable_memory_profiling=''
enable_mpi='yes'
enable_mpi_inplace='no'
enable_mpi_io='yes'
enable_mpi_trace='no'
enable_openmp='no'
enable_optim='aggressive'
enable_pkg_check='no'
enable_shared=''
enable_static=''
enable_stdin='yes'
enable_test_timeout='no'
enable_vdwxc='no'
enable_zdot_bugfix='no'
exec_prefix='NONE'
fallbacks_incs=''
fallbacks_instdir=''
fc_info_string='GNU Fortran (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3'
fc_mod_incs=''
fc_timing='standard'
fcflags_opt_01_gsl_ext='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_01_interfaces_ext='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_01_linalg_ext='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_01_macroavnew_ext='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_02_clib='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_10_defs='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_11_memory_mpi='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_11_qespresso_ext='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_12_hide_mpi='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_14_hidewrite='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_15_gpu_toolbox='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_16_hideleave='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_18_timing='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_27_toolbox_oop='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_28_numeric_noabirule='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_32_util='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_41_geometry='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_42_nlstrain='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_42_parser='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_43_ptgroups='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_43_wvl_wrappers='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_44_abitypes_defs='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_45_geomoptim='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_47_xml='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_49_gw_toolbox_oop='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_51_manage_mpi='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_52_fft_mpi_noabirule='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_52_manage_cuda='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_53_abiutil='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_53_ffts='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_53_spacepar='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_56_mixing='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_56_recipspace='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_56_xc='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_57_iopsp_parser='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_57_iovars='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_59_io_mpi='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_61_ionetcdf='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_62_cg_noabirule='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_62_iowfdenpot='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_62_occeig='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_62_poisson='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_62_wvl_wfs='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_63_bader='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_64_atompaw='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_65_lotf_base='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_65_nonlocal='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_65_psp='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_66_paw='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_66_wfs='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_67_common='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_68_dmft='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_68_lotf='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_68_recursion='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_68_rsprc='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_69_wfdesc='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_70_gw='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_71_bse='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_72_response='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_77_ddb='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_77_lwf='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_77_suscep='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_79_seqpar_mpi='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_83_cut3d='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_95_drive='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_98_main='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_algo='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_atompaw='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_bigdft='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_etsf_io='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_fox='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_libpspio='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_libxc='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_linalg='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_netcdf='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
fcflags_opt_wannier90='-O3 -mtune=native -march=native -faggressive-function-elimination -fstack-arrays'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/ebousq/CODES/Abinit/Branches/7.3.3-private/config/gnu/install-sh'
lib_algo_fcflags=''
lib_algo_flavor=''
lib_algo_incs=''
lib_algo_ldflags=''
lib_algo_libs=''
lib_atompaw_bins=''
lib_atompaw_fcflags=''
lib_atompaw_incs=''
lib_atompaw_ldflags=''
lib_atompaw_libs=''
lib_bigdft_fcflags=''
lib_bigdft_incs=''
lib_bigdft_ldflags=''
lib_bigdft_libs=''
lib_dft_flavor=''
lib_etsf_io_fcflags=''
lib_etsf_io_incs=''
lib_etsf_io_ldflags=''
lib_etsf_io_libs=''
lib_fft_fcflags=''
lib_fft_flavor=''
lib_fft_incs=''
lib_fft_ldflags=''
lib_fft_libs=''
lib_fox_fcflags=''
lib_fox_incs=''
lib_fox_ldflags=''
lib_fox_libs=''
lib_gpu_fcflags=''
lib_gpu_flavor='none'
lib_gpu_incs=''
lib_gpu_ldflags=''
lib_gpu_libs=''
lib_libpspio_fcflags=''
lib_libpspio_incs=''
lib_libpspio_ldflags=''
lib_libpspio_libs=''
lib_libxc_fcflags=''
lib_libxc_incs=''
lib_libxc_ldflags=''
lib_libxc_libs=''
lib_linalg_fcflags=''
lib_linalg_flavor=''
lib_linalg_incs=''
lib_linalg_ldflags=''
lib_linalg_libs=''
lib_math_fcflags=''
lib_math_flavor=''
lib_math_incs=''
lib_math_ldflags=''
lib_math_libs=''
lib_mpi_fcflags=''
lib_mpi_incs=''
lib_mpi_ldflags=''
lib_mpi_libs=''
lib_netcdf_fcflags=''
lib_netcdf_incs=''
lib_netcdf_ldflags=''
lib_netcdf_libs=''
lib_timer_fcflags=''
lib_timer_flavor=''
lib_timer_incs=''
lib_timer_ldflags=''
lib_timer_libs=''
lib_trio_flavor=''
lib_wannier90_bins=''
lib_wannier90_fcflags=''
lib_wannier90_incs=''
lib_wannier90_ldflags=''
lib_wannier90_libs=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
nightly_timeout=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
run_atompaw=''
run_etsf_io=''
run_fox_config=''
run_graphatom=''
run_nc_config=''
run_nccopy=''
run_ncdump=''
run_ncgen3=''
run_ncgen=''
run_wannier90_x=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
src_01_gsl_ext_incs='-I$(top_builddir)/src/01_gsl_ext -I$(top_srcdir)/src/01_gsl_ext'
src_01_interfaces_ext_incs='-I$(top_builddir)/src/01_interfaces_ext -I$(top_srcdir)/src/01_interfaces_ext'
src_01_linalg_ext_incs='-I$(top_builddir)/src/01_linalg_ext -I$(top_srcdir)/src/01_linalg_ext'
src_01_macroavnew_ext_incs='-I$(top_builddir)/src/01_macroavnew_ext -I$(top_srcdir)/src/01_macroavnew_ext'
src_02_clib_incs='-I$(top_builddir)/src/02_clib -I$(top_srcdir)/src/02_clib'
src_10_defs_incs='-I$(top_builddir)/src/10_defs -I$(top_srcdir)/src/10_defs'
src_11_memory_mpi_incs='-I$(top_builddir)/src/11_memory_mpi -I$(top_srcdir)/src/11_memory_mpi'
src_11_qespresso_ext_incs='-I$(top_builddir)/src/11_qespresso_ext -I$(top_srcdir)/src/11_qespresso_ext'
src_12_hide_mpi_incs='-I$(top_builddir)/src/12_hide_mpi -I$(top_srcdir)/src/12_hide_mpi'
src_14_hidewrite_incs='-I$(top_builddir)/src/14_hidewrite -I$(top_srcdir)/src/14_hidewrite'
src_15_gpu_toolbox_incs='-I$(top_builddir)/src/15_gpu_toolbox -I$(top_srcdir)/src/15_gpu_toolbox'
src_16_hideleave_incs='-I$(top_builddir)/src/16_hideleave -I$(top_srcdir)/src/16_hideleave'
src_18_timing_incs='-I$(top_builddir)/src/18_timing -I$(top_srcdir)/src/18_timing'
src_27_toolbox_oop_incs='-I$(top_builddir)/src/27_toolbox_oop -I$(top_srcdir)/src/27_toolbox_oop'
src_28_numeric_noabirule_incs='-I$(top_builddir)/src/28_numeric_noabirule -I$(top_srcdir)/src/28_numeric_noabirule'
src_32_util_incs='-I$(top_builddir)/src/32_util -I$(top_srcdir)/src/32_util'
src_41_geometry_incs='-I$(top_builddir)/src/41_geometry -I$(top_srcdir)/src/41_geometry'
src_42_nlstrain_incs='-I$(top_builddir)/src/42_nlstrain -I$(top_srcdir)/src/42_nlstrain'
src_42_parser_incs='-I$(top_builddir)/src/42_parser -I$(top_srcdir)/src/42_parser'
src_43_ptgroups_incs='-I$(top_builddir)/src/43_ptgroups -I$(top_srcdir)/src/43_ptgroups'
src_43_wvl_wrappers_incs='-I$(top_builddir)/src/43_wvl_wrappers -I$(top_srcdir)/src/43_wvl_wrappers'
src_44_abitypes_defs_incs='-I$(top_builddir)/src/44_abitypes_defs -I$(top_srcdir)/src/44_abitypes_defs'
src_45_geomoptim_incs='-I$(top_builddir)/src/45_geomoptim -I$(top_srcdir)/src/45_geomoptim'
src_47_xml_incs='-I$(top_builddir)/src/47_xml -I$(top_srcdir)/src/47_xml'
src_49_gw_toolbox_oop_incs='-I$(top_builddir)/src/49_gw_toolbox_oop -I$(top_srcdir)/src/49_gw_toolbox_oop'
src_51_manage_mpi_incs='-I$(top_builddir)/src/51_manage_mpi -I$(top_srcdir)/src/51_manage_mpi'
src_52_fft_mpi_noabirule_incs='-I$(top_builddir)/src/52_fft_mpi_noabirule -I$(top_srcdir)/src/52_fft_mpi_noabirule'
src_52_manage_cuda_incs='-I$(top_builddir)/src/52_manage_cuda -I$(top_srcdir)/src/52_manage_cuda'
src_53_abiutil_incs='-I$(top_builddir)/src/53_abiutil -I$(top_srcdir)/src/53_abiutil'
src_53_ffts_incs='-I$(top_builddir)/src/53_ffts -I$(top_srcdir)/src/53_ffts'
src_53_spacepar_incs='-I$(top_builddir)/src/53_spacepar -I$(top_srcdir)/src/53_spacepar'
src_56_mixing_incs='-I$(top_builddir)/src/56_mixing -I$(top_srcdir)/src/56_mixing'
src_56_recipspace_incs='-I$(top_builddir)/src/56_recipspace -I$(top_srcdir)/src/56_recipspace'
src_56_xc_incs='-I$(top_builddir)/src/56_xc -I$(top_srcdir)/src/56_xc'
src_57_iopsp_parser_incs='-I$(top_builddir)/src/57_iopsp_parser -I$(top_srcdir)/src/57_iopsp_parser'
src_57_iovars_incs='-I$(top_builddir)/src/57_iovars -I$(top_srcdir)/src/57_iovars'
src_59_io_mpi_incs='-I$(top_builddir)/src/59_io_mpi -I$(top_srcdir)/src/59_io_mpi'
src_61_ionetcdf_incs='-I$(top_builddir)/src/61_ionetcdf -I$(top_srcdir)/src/61_ionetcdf'
src_62_cg_noabirule_incs='-I$(top_builddir)/src/62_cg_noabirule -I$(top_srcdir)/src/62_cg_noabirule'
src_62_iowfdenpot_incs='-I$(top_builddir)/src/62_iowfdenpot -I$(top_srcdir)/src/62_iowfdenpot'
src_62_occeig_incs='-I$(top_builddir)/src/62_occeig -I$(top_srcdir)/src/62_occeig'
src_62_poisson_incs='-I$(top_builddir)/src/62_poisson -I$(top_srcdir)/src/62_poisson'
src_62_wvl_wfs_incs='-I$(top_builddir)/src/62_wvl_wfs -I$(top_srcdir)/src/62_wvl_wfs'
src_63_bader_incs='-I$(top_builddir)/src/63_bader -I$(top_srcdir)/src/63_bader'
src_64_atompaw_incs='-I$(top_builddir)/src/64_atompaw -I$(top_srcdir)/src/64_atompaw'
src_65_lotf_base_incs='-I$(top_builddir)/src/65_lotf_base -I$(top_srcdir)/src/65_lotf_base'
src_65_nonlocal_incs='-I$(top_builddir)/src/65_nonlocal -I$(top_srcdir)/src/65_nonlocal'
src_65_psp_incs='-I$(top_builddir)/src/65_psp -I$(top_srcdir)/src/65_psp'
src_66_paw_incs='-I$(top_builddir)/src/66_paw -I$(top_srcdir)/src/66_paw'
src_66_wfs_incs='-I$(top_builddir)/src/66_wfs -I$(top_srcdir)/src/66_wfs'
src_67_common_incs='-I$(top_builddir)/src/67_common -I$(top_srcdir)/src/67_common'
src_68_dmft_incs='-I$(top_builddir)/src/68_dmft -I$(top_srcdir)/src/68_dmft'
src_68_lotf_incs='-I$(top_builddir)/src/68_lotf -I$(top_srcdir)/src/68_lotf'
src_68_recursion_incs='-I$(top_builddir)/src/68_recursion -I$(top_srcdir)/src/68_recursion'
src_68_rsprc_incs='-I$(top_builddir)/src/68_rsprc -I$(top_srcdir)/src/68_rsprc'
src_69_wfdesc_incs='-I$(top_builddir)/src/69_wfdesc -I$(top_srcdir)/src/69_wfdesc'
src_70_gw_incs='-I$(top_builddir)/src/70_gw -I$(top_srcdir)/src/70_gw'
src_71_bse_incs='-I$(top_builddir)/src/71_bse -I$(top_srcdir)/src/71_bse'
src_72_response_incs='-I$(top_builddir)/src/72_response -I$(top_srcdir)/src/72_response'
src_77_ddb_incs='-I$(top_builddir)/src/77_ddb -I$(top_srcdir)/src/77_ddb'
src_77_lwf_incs='-I$(top_builddir)/src/77_lwf -I$(top_srcdir)/src/77_lwf'
src_77_suscep_incs='-I$(top_builddir)/src/77_suscep -I$(top_srcdir)/src/77_suscep'
src_79_seqpar_mpi_incs='-I$(top_builddir)/src/79_seqpar_mpi -I$(top_srcdir)/src/79_seqpar_mpi'
src_83_cut3d_incs='-I$(top_builddir)/src/83_cut3d -I$(top_srcdir)/src/83_cut3d'
src_95_drive_incs='-I$(top_builddir)/src/95_drive -I$(top_srcdir)/src/95_drive'
src_incs_incs='-I$(top_builddir)/src/incs -I$(top_srcdir)/src/incs'
src_mods_incs='-I$(top_builddir)/src/mods -I$(top_srcdir)/src/mods'
subdirs=''
sysconfdir='${prefix}/etc'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'
with_algo_flavor='none'
with_algo_incs=''
with_algo_libs=''
with_atompaw_bins=''
with_atompaw_incs=''
with_atompaw_libs=''
with_bigdft_incs=''
with_bigdft_libs=''
with_config_file=''
with_dft_flavor='none'
with_etsf_io_incs=''
with_etsf_io_libs=''
with_fc_vendor=''
with_fc_version=''
with_fft_flavor='none'
with_fft_incs=''
with_fft_libs=''
with_fox_incs=''
with_fox_libs=''
with_gnu_ld=''
with_gpu_cflags=''
with_gpu_cppflags=''
with_gpu_flavor='cuda-double'
with_gpu_incs=''
with_gpu_ldflags=''
with_gpu_libs=''
with_gpu_prefix=''
with_libpspio_incs=''
with_libpspio_libs=''
with_libxc_incs=''
with_libxc_libs=''
with_linalg_flavor='netlib'
with_linalg_incs=''
with_linalg_libs=''
with_math_flavor='none'
with_math_incs=''
with_math_libs=''
with_mpi_incs=''
with_mpi_level=''
with_mpi_libs=''
with_mpi_prefix=''
with_netcdf_incs=''
with_netcdf_libs=''
with_tardir=''
with_test_timeout='0'
with_timer_flavor='abinit'
with_timer_incs=''
with_timer_libs=''
with_trio_flavor='none'
with_wannier90_bins=''
with_wannier90_incs=''
with_wannier90_libs=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "ABINIT"
#define PACKAGE_TARNAME "abinit"
#define PACKAGE_VERSION "7.3.3"
#define PACKAGE_STRING "ABINIT 7.3.3"
#define PACKAGE_BUGREPORT "https://bugs.launchpad.net/abinit/"
#define PACKAGE_URL ""
#define PACKAGE "abinit"
#define VERSION "7.3.3"
#define ABINIT_VERSION "7.3.3"
#define ABINIT_VERSION_MAJOR "7"
#define ABINIT_VERSION_MINOR "3"
#define ABINIT_VERSION_MICRO "3"
#define ABINIT_VERSION_BUILD "20130604"
#define ABINIT_VERSION_BASE "7.3"
#define HAVE_OS_LINUX 1
#define CC_GNU 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define CXX_GNU 1
#define FC_GNU 1
#define HAVE_FORTRAN2003 1
#define FC_FUNC(name,NAME) name ## _
#define FC_FUNC_(name,NAME) name ## _
#define HAVE_NUMPY 1
#define HAVE_BZR_BRANCH 1
#define ABINIT_TARGET "x86_64_linux_gnu4.7"
#define HAVE_STDDEF_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDIO_H 1
#define HAVE_MATH_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_ERRNO_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MCHECK_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_ABORT 1
#define HAVE_MALLINFO 1
#define SIZEOF_CHAR 1
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define SIZEOF_SIZE_T 8
#define SIZEOF_PTRDIFF_T 8
#define HAVE_FC_COMMAND_LINE 1
#define HAVE_FC_CONTIGUOUS 1
#define HAVE_FC_ALLOCATABLE_DTARRAYS 1
#define HAVE_FC_IOMSG 1
#define HAVE_FC_ISO_C_BINDING 1
#define HAVE_FC_EXIT 1
#define HAVE_FC_FLUSH 1
#define HAVE_FC_GAMMA 1
#define HAVE_FC_GETENV 1
#define HAVE_FC_NULL 1
#define HAVE_FC_INT_QUAD 1
#define HAVE_FC_LONG_LINES 1
#define HAVE_FC_STREAM_IO 1
#define HAVE_FC_CPUTIME 1

configure: exit 1
